window.GRAMMYS_DATA = [
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Henry Mancini",
  work: "The Music from Peter Gunn",
  year: 1959,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Henry_Mancini",
  artistDescription: null,
  spotify: "7oEvg2276GEaBmjNO2w1VL",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Domenico Modugno",
  work: "Nel blu, dipinto di blu (Volare)",
  year: 1959,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Domenico_Modugno",
  artistDescription: null,
  spotify: "2IKvYPWeWZufWdh3n306sK",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Domenico Modugno",
  work: "Nel blu, dipinto di blu (Volare)",
  year: 1959,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Domenico_Modugno",
  artistDescription: null,
  spotify: "2IKvYPWeWZufWdh3n306sK",
  spotifyType: "track"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Frank Sinatra",
  work: "Come Dance with Me!",
  year: 1960,
  artistWikidata: "Q40912",
  artistWikipedia: "https://en.wikipedia.org/wiki/Frank_Sinatra",
  artistDescription: "American singer and actor (1915–1998)",
  spotify: "2XgFfM6SNKtNLGcN3joZro",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Bobby Darin",
  work: "Mack the Knife",
  year: 1960,
  artistWikidata: "Q311267",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bobby_Darin",
  artistDescription: "American singer and actor (1936–1973)",
  spotify: "3E5ndyOfO6vFDEIE42HA8o",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Jimmy Driftwood",
  work: "The Battle of New Orleans",
  year: 1960,
  artistWikidata: "Q352930",
  artistWikipedia: "https://en.wikipedia.org/wiki/Jimmy_Driftwood",
  artistDescription: "singer (1907-1998)",
  spotify: "5DDgpkUGEjTJ3D1GunTaJs",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Bobby Darin",
  work: "",
  year: 1960,
  artistWikidata: "Q311267",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bobby_Darin",
  artistDescription: "American singer and actor (1936–1973)",
  spotify: "0EodhzA6yW1bIdD5B4tcmJ",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Bob Newhart",
  work: "The Button-Down Mind of Bob Newhart",
  year: 1961,
  artistWikidata: "Q718078",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bob_Newhart",
  artistDescription: "American stand-up comedian and actor (1929–2024)",
  spotify: "7hX0ROeIkqTmnMYr9aGvYV",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Percy Faith",
  work: "Theme from A Summer Place",
  year: 1961,
  artistWikidata: "Q712683",
  artistWikipedia: "https://en.wikipedia.org/wiki/Percy_Faith",
  artistDescription: "Canadian-born American bandleader, orchestrator, composer and conductor (1908-1976)",
  spotify: "6zwvB879PJSpTyFcg2wwnL",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Ernest Gold",
  work: "Theme from Exodus",
  year: 1961,
  artistWikidata: "Q215753",
  artistWikipedia: "https://en.wikipedia.org/wiki/Ernest_Gold",
  artistDescription: "Austrian American composer (1921-1999)",
  spotify: "5FC7xlD063UwCeJfWBzyyY",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Bob Newhart",
  work: "",
  year: 1961,
  artistWikidata: "Q718078",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bob_Newhart",
  artistDescription: "American stand-up comedian and actor (1929–2024)",
  spotify: "49mU7Sl98U8MkECsd6zVq0",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Judy Garland",
  work: "Judy at Carnegie Hall",
  year: 1962,
  artistWikidata: "Q11637",
  artistWikipedia: "https://en.wikipedia.org/wiki/Judy_Garland",
  artistDescription: "American actress, singer, dancer and vaudevillian (1922–1969)",
  spotify: "3M0RdVAdvPETjcEvPj7AI0",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Henry Mancini",
  work: "Moon River",
  year: 1962,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Henry_Mancini",
  artistDescription: null,
  spotify: "0gljCof9FFOHKvxznqNR23",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Henry Mancini and Johnny Mercer",
  work: "Moon River",
  year: 1962,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Henry_Mancini",
  artistDescription: null,
  spotify: "5WRXtJh4NBcpkv4G691gfG",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Peter Nero",
  work: "",
  year: 1962,
  artistWikidata: "Q7176071",
  artistWikipedia: "https://en.wikipedia.org/wiki/Peter_Nero",
  artistDescription: "American pianist and pops conductor (1934–2023)",
  spotify: "4LRsjW7ygBG4oiTRn08gEx",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Vaughn Meader",
  work: "The First Family",
  year: 1963,
  artistWikidata: "Q4009028",
  artistWikipedia: "https://en.wikipedia.org/wiki/Vaughn_Meader",
  artistDescription: "American comedian, musician, and impressionist",
  spotify: "7qRhMLb8cYKoA2hqiO7OjV",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Tony Bennett",
  work: "I Left My Heart in San Francisco",
  year: 1963,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Tony_Bennett",
  artistDescription: null,
  spotify: "1bYItjcPRtxZs6Ir71O5RB",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Leslie Bricusse and Anthony Newley",
  work: "What Kind of Fool Am I?",
  year: 1963,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Leslie_Bricusse",
  artistDescription: null,
  spotify: "4TshS8seImdgxhvNYmRDv6",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Robert Goulet",
  work: "",
  year: 1963,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Robert_Goulet",
  artistDescription: null,
  spotify: "6Qdqv5WM6z1WxWWjuuiogR",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Barbra Streisand",
  work: "The Barbra Streisand Album",
  year: 1964,
  artistWikidata: "Q4636",
  artistWikipedia: "https://en.wikipedia.org/wiki/Barbra_Streisand",
  artistDescription: null,
  spotify: "6lJaBPh4nMloLfWh2SQI6x",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Henry Mancini",
  work: "The Days of Wine and Roses",
  year: 1964,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Henry_Mancini",
  artistDescription: null,
  spotify: "4XD9xETG2OuWta7mXyUVVe",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Johnny Mercer and Henry Mancini",
  work: "Days of Wine and Roses",
  year: 1964,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Johnny_Mercer",
  artistDescription: null,
  spotify: "1UkXfrZXEWU3SF0ZIi6sRo",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Ward Swingle",
  work: "",
  year: 1964,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Ward_Swingle",
  artistDescription: null,
  spotify: "3iX21wC29wNK2XvYF95aS4",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Stan Getz and Joao Gilberto",
  work: "Getz/Gilberto",
  year: 1965,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Stan_Getz",
  artistDescription: null,
  spotify: "73ZRKdD3Ds43IjHrhKgucY",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Stan Getz and Astrud Gilberto",
  work: "The Girl from Ipanema",
  year: 1965,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Stan_Getz",
  artistDescription: null,
  spotify: "4qGfJb2KByjvzrwo8HNibg",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Jerry Herman",
  work: "Hello, Dolly!",
  year: 1965,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Jerry_Herman",
  artistDescription: null,
  spotify: "1QLw9hNAUEKKgrsmDkfFxK",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "The Beatles",
  work: "",
  year: 1965,
  artistWikidata: "Q1299",
  artistWikipedia: "https://en.wikipedia.org/wiki/The_Beatles",
  artistDescription: "English pop rock band (1960–1970)",
  spotify: "3WrFJ7ztbogyGnTHbHJFl2",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Frank Sinatra",
  work: "September of My Years",
  year: 1966,
  artistWikidata: "Q40912",
  artistWikipedia: "https://en.wikipedia.org/wiki/Frank_Sinatra",
  artistDescription: "American singer and actor (1915–1998)",
  spotify: "3DdN3GRJj8YS0V0fiyXtbt",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Herb Alpert & the Tijuana Brass",
  work: "A Taste of Honey",
  year: 1966,
  artistWikidata: "Q344822",
  artistWikipedia: "https://en.wikipedia.org/wiki/Herb_Alpert",
  artistDescription: "American trumpeter and recording industry executive (born 1935)",
  spotify: "2XmLd81D7jT8Ell9lmvApe",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Paul Francis Webster and Johnny Mandel",
  work: "The Shadow of Your Smile",
  year: 1966,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Paul_Francis_Webster",
  artistDescription: null,
  spotify: "5wpkwyTOUr1K8R4bmU7u6R",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Tom Jones",
  work: "",
  year: 1966,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Tom_Jones",
  artistDescription: null,
  spotify: "1T0wRBO0CK0vK8ouUMqEl5",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Frank Sinatra",
  work: "A Man and His Music",
  year: 1967,
  artistWikidata: "Q40912",
  artistWikipedia: "https://en.wikipedia.org/wiki/Frank_Sinatra",
  artistDescription: "American singer and actor (1915–1998)",
  spotify: "6lmuhQkwg4qkjytuho7Oxz",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Frank Sinatra",
  work: "Strangers in the Night",
  year: 1967,
  artistWikidata: "Q40912",
  artistWikipedia: "https://en.wikipedia.org/wiki/Frank_Sinatra",
  artistDescription: "American singer and actor (1915–1998)",
  spotify: "74VR3AkGPhbYXnxcOYa16x",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "John Lennon and Paul McCartney",
  work: "Michelle",
  year: 1967,
  artistWikidata: "Q239177",
  artistWikipedia: "https://en.wikipedia.org/wiki/Lennon%E2%80%93McCartney",
  artistDescription: "songwriting partnership between John Lennon and Paul McCartney",
  spotify: "1dzKDHSFIJeWvzm8EOif91",
  spotifyType: "track"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "The Beatles",
  work: "Sgt. Pepper's Lonely Hearts Club Band",
  year: 1968,
  artistWikidata: "Q1299",
  artistWikipedia: "https://en.wikipedia.org/wiki/The_Beatles",
  artistDescription: "English pop rock band (1960–1970)",
  spotify: "6QaVfG1pHYl1z15ZxkvVDW",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "5th Dimension",
  work: "Up, Up and Away",
  year: 1968,
  artistWikidata: "Q7213391",
  artistWikipedia: "https://en.wikipedia.org/wiki/5th_Dimension_%28album%29",
  artistDescription: "album by Momoiro Clover Z",
  spotify: "3JdToGxgvH9SnO1a605Ztr",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Jim Webb",
  work: "Up, Up and Away",
  year: 1968,
  artistWikidata: "Q532279",
  artistWikipedia: "https://en.wikipedia.org/wiki/Jim_Webb",
  artistDescription: "American politician, military officer and author (born 1946)",
  spotify: "3Ss16MKdgt5BsOpXWvkNuf",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Bobbie Gentry",
  work: "",
  year: 1968,
  artistWikidata: "Q272253",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bobbie_Gentry",
  artistDescription: "American singer-songwriter",
  spotify: "4E9w0bms6HcEppFlWjeW2d",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Glen Campbell",
  work: "By the Time I Get to Phoenix",
  year: 1969,
  artistWikidata: "Q162667",
  artistWikipedia: "https://en.wikipedia.org/wiki/Glen_Campbell",
  artistDescription: "American musician (1936–2017)",
  spotify: "29tTA46kurlOioRkjBqOMS",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Simon & Garfunkel",
  work: "Mrs. Robinson",
  year: 1969,
  artistWikidata: "Q484918",
  artistWikipedia: "https://en.wikipedia.org/wiki/Simon_%26_Garfunkel",
  artistDescription: "American folk music duo",
  spotify: "0iOZM63lendWRTTeKhZBSC",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Bobby Russell",
  work: "Little Green Apples",
  year: 1969,
  artistWikidata: "Q3641411",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bobby_Russell",
  artistDescription: "American singer-songwriter",
  spotify: "3cOBG6bm4NrCHTMHOWDr9P",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Jose Feliciano",
  work: "",
  year: 1969,
  artistWikidata: "Q315784",
  artistWikipedia: "https://en.wikipedia.org/wiki/Jos%C3%A9_Feliciano",
  artistDescription: "Puerto Rican musician",
  spotify: "7K78lVZ8XzkjfRSI7570FF",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Blood, Sweat & Tears",
  work: "Blood, Sweat & Tears",
  year: 1970,
  artistWikidata: "Q48995",
  artistWikipedia: "https://en.wikipedia.org/wiki/Blood%2C_Sweat_%26_Tears",
  artistDescription: "American rock music band",
  spotify: "7qFad1a6Q3kUJ1oAz6fT9m",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "5th Dimension",
  work: "Aquarius/Let the Sunshine In",
  year: 1970,
  artistWikidata: "Q7213391",
  artistWikipedia: "https://en.wikipedia.org/wiki/5th_Dimension_%28album%29",
  artistDescription: "album by Momoiro Clover Z",
  spotify: "0HZlND4giwzgolBpaNIRGV",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Joe South",
  work: "Games People Play",
  year: 1970,
  artistWikidata: "Q1333939",
  artistWikipedia: "https://en.wikipedia.org/wiki/Joe_South",
  artistDescription: null,
  spotify: "50t8gshcAtXiUdk7nHfYDp",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Crosby, Stills & Nash",
  work: "",
  year: 1970,
  artistWikidata: "Q733159",
  artistWikipedia: "https://en.wikipedia.org/wiki/Crosby%2C_Stills_%26_Nash",
  artistDescription: "American folk rock band",
  spotify: "2pdvghEHZJtgSXZ7cvNLou",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Simon & Garfunkel",
  work: "Bridge over Troubled Water",
  year: 1971,
  artistWikidata: "Q484918",
  artistWikipedia: "https://en.wikipedia.org/wiki/Simon_%26_Garfunkel",
  artistDescription: "American folk music duo",
  spotify: "0JwHz5SSvpYWuuCNbtYZoV",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Simon & Garfunkel",
  work: "Bridge over Troubled Water",
  year: 1971,
  artistWikidata: "Q484918",
  artistWikipedia: "https://en.wikipedia.org/wiki/Simon_%26_Garfunkel",
  artistDescription: "American folk music duo",
  spotify: "6l8EbYRtQMgKOyc1gcDHF9",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Paul Simon",
  work: "Bridge over Troubled Water",
  year: 1971,
  artistWikidata: "Q4028",
  artistWikipedia: "https://en.wikipedia.org/wiki/Paul_Simon",
  artistDescription: "American singer-songwriter (born 1941)",
  spotify: "65Q3jlvZkSp55H7mlDJlAz",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "The Carpenters",
  work: "",
  year: 1971,
  artistWikidata: "Q223495",
  artistWikipedia: "https://en.wikipedia.org/wiki/The_Carpenters",
  artistDescription: "American musical group; vocal sibling duo",
  spotify: "3WgGMYgYdn4WgtSI9B7AR2",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Carole King",
  work: "Tapestry",
  year: 1972,
  artistWikidata: "Q217787",
  artistWikipedia: "https://en.wikipedia.org/wiki/Carole_King",
  artistDescription: "American singer-songwriter and musician (born 1942)",
  spotify: "12n11cgnpjXKLeqrnIERoS",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Carole King",
  work: "It's Too Late",
  year: 1972,
  artistWikidata: "Q217787",
  artistWikipedia: "https://en.wikipedia.org/wiki/Carole_King",
  artistDescription: "American singer-songwriter and musician (born 1942)",
  spotify: "12q3V8ShACq2PSWINMc2rC",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Carole King",
  work: "You've Got a Friend",
  year: 1972,
  artistWikidata: "Q217787",
  artistWikipedia: "https://en.wikipedia.org/wiki/Carole_King",
  artistDescription: "American singer-songwriter and musician (born 1942)",
  spotify: "1qhp5owrFGeZ5Jgin28nwR",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Carly Simon",
  work: "",
  year: 1972,
  artistWikidata: "Q181683",
  artistWikipedia: "https://en.wikipedia.org/wiki/Carly_Simon",
  artistDescription: "American musician",
  spotify: "4FtSnMlCVxCswABUmdhwpm",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "George Harrison and friends",
  work: "The Concert for Bangladesh",
  year: 1973,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/George_Harrison",
  artistDescription: null,
  spotify: "6chnsCpxLbisc2CYyGqFzK",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Roberta Flack",
  work: "The First Time Ever I Saw Your Face",
  year: 1973,
  artistWikidata: "Q231484",
  artistWikipedia: "https://en.wikipedia.org/wiki/Roberta_Flack",
  artistDescription: null,
  spotify: "0SxFyA4FqmEQqZVuAlg8lf",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Ewan MacColl",
  work: "The First Time Ever I Saw Your Face",
  year: 1973,
  artistWikidata: "Q1192339",
  artistWikipedia: "https://en.wikipedia.org/wiki/Ewan_MacColl",
  artistDescription: "British folk singer, songwriter, communist, labour activist, actor, poet, playwright, and record producer (1915–1989)",
  spotify: "7z7fty8FffHCOI3zm3R3Ei",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "America",
  work: "",
  year: 1973,
  artistWikidata: "Q30",
  artistWikipedia: "https://en.wikipedia.org/wiki/United_States",
  artistDescription: "country located primarily in North America",
  spotify: "35U9lQaRWSQISxQAB94Meo",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Stevie Wonder",
  work: "Innervisions",
  year: 1974,
  artistWikidata: "Q714",
  artistWikipedia: "https://en.wikipedia.org/wiki/Stevie_Wonder",
  artistDescription: "American and Ghanaian singer-songwriter, composer and record producer (born 1950)",
  spotify: "5jgI8Eminx9MmLBontDWq8",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Roberta Flack",
  work: "Killing Me Softly with His Song",
  year: 1974,
  artistWikidata: "Q231484",
  artistWikipedia: "https://en.wikipedia.org/wiki/Roberta_Flack",
  artistDescription: null,
  spotify: "3gsCAGsWr6pUm1Vy7CPPob",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Norman Gimbel and Charles Fox",
  work: "Killing Me Softly with His Song",
  year: 1974,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Norman_Gimbel",
  artistDescription: null,
  spotify: "3u8G5T2V93Pvr3bf66tkuv",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Bette Midler",
  work: "",
  year: 1974,
  artistWikidata: "Q190631",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bette_Midler",
  artistDescription: "American singer and actress (born 1945)",
  spotify: "13y0kncDD4J9wxCyfKr10W",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Stevie Wonder",
  work: "Fulfillingness' First Finale",
  year: 1975,
  artistWikidata: "Q714",
  artistWikipedia: "https://en.wikipedia.org/wiki/Stevie_Wonder",
  artistDescription: "American and Ghanaian singer-songwriter, composer and record producer (born 1950)",
  spotify: "1kda4McF274Jl5x3aOAmPJ",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Olivia Newton-John",
  work: "I Honestly Love You",
  year: 1975,
  artistWikidata: "Q185165",
  artistWikipedia: "https://en.wikipedia.org/wiki/Olivia_Newton-John",
  artistDescription: "British–Australian singer (1948–2022)",
  spotify: "0u2U3YZDGOk6ROfpWAFIkv",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Marilyn Bergman, Alan Bergman, and Marvin Hamlisch",
  work: "The Way We Were",
  year: 1975,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Marilyn_Bergman%2C_Alan_Bergman%2C",
  artistDescription: null,
  spotify: "7mxVRxmeDZomtxfB2D0tL6",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Marvin Hamlisch",
  work: "",
  year: 1975,
  artistWikidata: "Q337206",
  artistWikipedia: "https://en.wikipedia.org/wiki/Marvin_Hamlisch",
  artistDescription: "American composer and conductor (1944-2012)",
  spotify: "1VN38ZSdtQnHLa8PfTTKZD",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Paul Simon",
  work: "Still Crazy After All These Years",
  year: 1976,
  artistWikidata: "Q4028",
  artistWikipedia: "https://en.wikipedia.org/wiki/Paul_Simon",
  artistDescription: "American singer-songwriter (born 1941)",
  spotify: "4A366gjTrYQwmRtkTezF2W",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Captain & Tennille",
  work: "Love Will Keep Us Together",
  year: 1976,
  artistWikidata: "Q1035077",
  artistWikipedia: "https://en.wikipedia.org/wiki/Captain_%26_Tennille",
  artistDescription: null,
  spotify: "4pCNJwixy2ImFncaPY2yE2",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Stephen Sondheim",
  work: "Send in the Clowns",
  year: 1976,
  artistWikidata: "Q153579",
  artistWikipedia: "https://en.wikipedia.org/wiki/Stephen_Sondheim",
  artistDescription: "American composer and lyricist (1930–2021)",
  spotify: "60rwCozHI55tnHCZHI8bJ2",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Natalie Cole",
  work: "",
  year: 1976,
  artistWikidata: "Q104077874",
  artistWikipedia: "https://en.wikipedia.org/wiki/Natalie_Cole",
  artistDescription: "American reality television participant",
  spotify: "5tTsrGPwQRWUsHR2Xf7Ke9",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Stevie Wonder",
  work: "Songs in the Key of Life",
  year: 1977,
  artistWikidata: "Q714",
  artistWikipedia: "https://en.wikipedia.org/wiki/Stevie_Wonder",
  artistDescription: "American and Ghanaian singer-songwriter, composer and record producer (born 1950)",
  spotify: "6YUCc2RiXcEKS9ibuZxjt0",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "George Benson",
  work: "This Masquerade",
  year: 1977,
  artistWikidata: "Q348459",
  artistWikipedia: "https://en.wikipedia.org/wiki/George_Benson",
  artistDescription: "American guitarist and singer (born 1943)",
  spotify: "7uhOlFq30tYkUZ70JwbRre",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Barbra Streisand and Paul Williams",
  work: "Evergreen",
  year: 1977,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Barbra_Streisand",
  artistDescription: null,
  spotify: "26GC9EEgNYqOlsZMhzeIab",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Starland Vocal Band",
  work: "",
  year: 1977,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Starland_Vocal_Band",
  artistDescription: null,
  spotify: "66QeIFuFJDNCImNHlFzrY1",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Fleetwood Mac",
  work: "Rumours",
  year: 1978,
  artistWikidata: "Q106648",
  artistWikipedia: "https://en.wikipedia.org/wiki/Fleetwood_Mac",
  artistDescription: "British-American rock band",
  spotify: "1bt6q2SruMsBtcerNVtpZB",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Eagles",
  work: "Hotel California",
  year: 1978,
  artistWikidata: "Q189635",
  artistWikipedia: "https://en.wikipedia.org/wiki/Eagles_%28band%29",
  artistDescription: "American country rock band",
  spotify: "40riOy7x9W7GXjyGp4pjAv",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Joe Brooks",
  work: "You Light Up My Life",
  year: 1978,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Joe_Brooks",
  artistDescription: null,
  spotify: "10tvWSprvDCd09pKTdc3c9",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Debby Boone",
  work: "",
  year: 1978,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Debby_Boone",
  artistDescription: null,
  spotify: "1UkHCANZmdkKyVNvTLMrcJ",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Bee Gees",
  work: "Saturday Night Fever",
  year: 1979,
  artistWikidata: "Q133405",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bee_Gees",
  artistDescription: null,
  spotify: "3xaCKtqadm4KnviPFKEjs7",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Billy Joel",
  work: "Just the Way You Are",
  year: 1979,
  artistWikidata: "Q194333",
  artistWikipedia: "https://en.wikipedia.org/wiki/Billy_Joel",
  artistDescription: null,
  spotify: "49MHCPzvMLXhRjDantBMVH",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Billy Joel",
  work: "Just the Way You Are",
  year: 1979,
  artistWikidata: "Q194333",
  artistWikipedia: "https://en.wikipedia.org/wiki/Billy_Joel",
  artistDescription: null,
  spotify: "49MHCPzvMLXhRjDantBMVH",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "A Taste of Honey",
  work: "",
  year: 1979,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/A_Taste_of_Honey",
  artistDescription: null,
  spotify: "1ii6e2pv8VIRwnTER71rMl",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Billy Joel",
  work: "52nd Street",
  year: 1980,
  artistWikidata: "Q194333",
  artistWikipedia: "https://en.wikipedia.org/wiki/Billy_Joel",
  artistDescription: null,
  spotify: "1HmCO8VK98AU6EXPOjGYyI",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "The Doobie Brothers",
  work: "What a Fool Believes",
  year: 1980,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/The_Doobie_Brothers",
  artistDescription: null,
  spotify: "2yBVeksU2EtrPJbTu4ZslK",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Kenny Loggins and Michael McDonald",
  work: "What a Fool Believes",
  year: 1980,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Kenny_Loggins",
  artistDescription: null,
  spotify: "7yukGUDEOcjug514T4qgvQ",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Rickie Lee Jones",
  work: "",
  year: 1980,
  artistWikidata: "Q258846",
  artistWikipedia: "https://en.wikipedia.org/wiki/Rickie_Lee_Jones",
  artistDescription: "American singer (born 1954)",
  spotify: "0dYkMe3wK29DulSa0uR8Rq",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Christopher Cross",
  work: "Christopher Cross",
  year: 1981,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Christopher_Cross",
  artistDescription: null,
  spotify: "4unLP4n9N8NB71dvSuI5Mt",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Christopher Cross",
  work: "Sailing",
  year: 1981,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Christopher_Cross",
  artistDescription: null,
  spotify: "6YIeSw2cTNQRWbuxWvRPsW",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Christopher Cross",
  work: "Sailing",
  year: 1981,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Christopher_Cross",
  artistDescription: null,
  spotify: "6YIeSw2cTNQRWbuxWvRPsW",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Christopher Cross",
  work: "",
  year: 1981,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Christopher_Cross",
  artistDescription: null,
  spotify: "695W5F2Ih8dYahLdjVOIoH",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "John Lennon and Yoko Ono",
  work: "Double Fantasy",
  year: 1982,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/John_Lennon",
  artistDescription: null,
  spotify: "15q7N7Wo307mfjqR29NpjF",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Kim Carnes",
  work: "Bette Davis Eyes",
  year: 1982,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Kim_Carnes",
  artistDescription: null,
  spotify: "0odIT9B9BvOCnXfS0e4lB5",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Donna Weiss and Jackie DeShannon",
  work: "Bette Davis Eyes",
  year: 1982,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Donna_Weiss",
  artistDescription: null,
  spotify: "0odIT9B9BvOCnXfS0e4lB5",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Sheena Easton",
  work: "",
  year: 1982,
  artistWikidata: "Q465977",
  artistWikipedia: "https://en.wikipedia.org/wiki/Sheena_Easton",
  artistDescription: null,
  spotify: "5dcOK4stT4JDkP6Dqhbz5s",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Toto",
  work: "Toto IV",
  year: 1983,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Toto",
  artistDescription: null,
  spotify: "62U7xIHcID94o20Of5ea4D",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Toto",
  work: "Rosanna",
  year: 1983,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Toto",
  artistDescription: null,
  spotify: "37BTh5g05cxBIRYMbw8g2T",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Johnny Christopher, Mark James, and Wayne Carson",
  work: "Always on My Mind",
  year: 1983,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Johnny_Christopher%2C_Mark_James%2C",
  artistDescription: null,
  spotify: "4VNN2qxRHAaqM3quoEwgDY",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Men at Work",
  work: "",
  year: 1983,
  artistWikidata: "Q831111",
  artistWikipedia: "https://en.wikipedia.org/wiki/Men_at_Work",
  artistDescription: "Australian rock band",
  spotify: "0f3EsoviYnRKTkmayI3cux",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Michael Jackson",
  work: "Thriller",
  year: 1984,
  artistWikidata: "Q2831",
  artistWikipedia: "https://en.wikipedia.org/wiki/Michael_Jackson",
  artistDescription: "American singer, songwriter, record producer, and dancer (1958–2009)",
  spotify: "2ANVost0y2y52ema1E9xAZ",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Michael Jackson",
  work: "Beat It",
  year: 1984,
  artistWikidata: "Q2831",
  artistWikipedia: "https://en.wikipedia.org/wiki/Michael_Jackson",
  artistDescription: "American singer, songwriter, record producer, and dancer (1958–2009)",
  spotify: "3BovdzfaX4jb5KFQwoPfAw",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Sting",
  work: "Every Breath You Take",
  year: 1984,
  artistWikidata: "Q483203",
  artistWikipedia: "https://en.wikipedia.org/wiki/Sting_%28musician%29",
  artistDescription: "British musician (born 1951)",
  spotify: "72s8HAZjlpevciwAFhhhBk",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Culture Club",
  work: "",
  year: 1984,
  artistWikidata: "Q50037",
  artistWikipedia: "https://en.wikipedia.org/wiki/Culture_Club",
  artistDescription: "English new wave band",
  spotify: "6kz53iCdBSqhQCZ21CoLcc",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Lionel Richie",
  work: "Can't Slow Down",
  year: 1985,
  artistWikidata: "Q26695",
  artistWikipedia: "https://en.wikipedia.org/wiki/Lionel_Richie",
  artistDescription: null,
  spotify: "609oTPBaxPzZUCHzQikOtC",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Tina Turner",
  work: "What's Love Got to Do with It",
  year: 1985,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Tina_Turner",
  artistDescription: null,
  spotify: "4kOfxxnW1ukZdsNbCKY9br",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Graham Lyle and Terry Britten",
  work: "What's Love Got to Do with It",
  year: 1985,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Graham_Lyle",
  artistDescription: null,
  spotify: "4kOfxxnW1ukZdsNbCKY9br",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Cyndi Lauper",
  work: "",
  year: 1985,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Cyndi_Lauper",
  artistDescription: null,
  spotify: "2BTZIqw0ntH9MvilQ3ewNY",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Phil Collins",
  work: "No Jacket Required",
  year: 1986,
  artistWikidata: "Q144622",
  artistWikipedia: "https://en.wikipedia.org/wiki/Phil_Collins",
  artistDescription: "English drummer, singer, and songwriter (born 1951)",
  spotify: "1rVhockt4RAiZFaK3M3zPB",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "USA for Africa",
  work: "We Are the World",
  year: 1986,
  artistWikidata: "Q1165609",
  artistWikipedia: "https://en.wikipedia.org/wiki/USA_for_Africa",
  artistDescription: "US supergroup",
  spotify: "3Z2tPWiNiIpg8UMMoowHIk",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Michael Jackson and Lionel Richie",
  work: "We Are the World",
  year: 1986,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Michael_Jackson",
  artistDescription: null,
  spotify: "1Y7mBMfW4rz8YFTMkVIyua",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Sade",
  work: "",
  year: 1986,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Sade",
  artistDescription: null,
  spotify: "0KdYhahrgZylBoBwA2DNIa",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Paul Simon",
  work: "Graceland",
  year: 1987,
  artistWikidata: "Q4028",
  artistWikipedia: "https://en.wikipedia.org/wiki/Paul_Simon",
  artistDescription: "American singer-songwriter (born 1941)",
  spotify: "4WoQ94qzwQj28n3nlSOVLB",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Steve Winwood",
  work: "Higher Love",
  year: 1987,
  artistWikidata: "Q314397",
  artistWikipedia: "https://en.wikipedia.org/wiki/Steve_Winwood",
  artistDescription: null,
  spotify: "4ZExvJvQXPEeYzGU0N3THi",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Burt Bacharach and Carole Bayer Sager",
  work: "That's What Friends Are For",
  year: 1987,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Burt_Bacharach",
  artistDescription: null,
  spotify: "1OzrlK57iLTIjmbZC1ppWM",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Bruce Hornsby and the Range",
  work: "",
  year: 1987,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bruce_Hornsby",
  artistDescription: null,
  spotify: "7CwJ4VEWs7HV7MWQt9cgyk",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "U2",
  work: "The Joshua Tree",
  year: 1988,
  artistWikidata: "Q396",
  artistWikipedia: "https://en.wikipedia.org/wiki/U2",
  artistDescription: null,
  spotify: "5vBZRYu2GLA65nfxBvG1a7",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Paul Simon",
  work: "Graceland",
  year: 1988,
  artistWikidata: "Q4028",
  artistWikipedia: "https://en.wikipedia.org/wiki/Paul_Simon",
  artistDescription: "American singer-songwriter (born 1941)",
  spotify: "51KKQAgYFoJHgVIuJWHdHb",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "James Horner, Barry Mann, and Cynthia Weil",
  work: "Somewhere Out There",
  year: 1988,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/James_Horner%2C_Barry_Mann%2C",
  artistDescription: null,
  spotify: "52mrJSJ5oEZRwsit1koWaK",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Jody Watley",
  work: "",
  year: 1988,
  artistWikidata: "Q465897",
  artistWikipedia: "https://en.wikipedia.org/wiki/Jody_Watley",
  artistDescription: "American singer",
  spotify: "71aKjsWKYqASAffyIQaocZ",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "George Michael",
  work: "Faith",
  year: 1989,
  artistWikidata: "Q130311",
  artistWikipedia: "https://en.wikipedia.org/wiki/George_Michael",
  artistDescription: "English singer (1963–2016)",
  spotify: "34K1Kvskt9arWy8E1Gz3Lw",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Bobby McFerrin",
  work: "Don't Worry, Be Happy",
  year: 1989,
  artistWikidata: "Q310894",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bobby_McFerrin",
  artistDescription: "American jazz vocalist and composer (born 1950)",
  spotify: "4hObp5bmIJ3PP3cKA9K9GY",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Bobby McFerrin",
  work: "Don't Worry, Be Happy",
  year: 1989,
  artistWikidata: "Q310894",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bobby_McFerrin",
  artistDescription: "American jazz vocalist and composer (born 1950)",
  spotify: "4hObp5bmIJ3PP3cKA9K9GY",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Tracy Chapman",
  work: "",
  year: 1989,
  artistWikidata: "Q187814",
  artistWikipedia: "https://en.wikipedia.org/wiki/Tracy_Chapman",
  artistDescription: null,
  spotify: "7oPgCQqMMXEXrNau5vxYZP",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Bonnie Raitt",
  work: "Nick of Time",
  year: 1990,
  artistWikidata: "Q234693",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bonnie_Raitt",
  artistDescription: "American musician (born 1949)",
  spotify: "6wxpS5o0ty5CLqyH5fIRln",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Bonnie Raitt",
  work: "Nick of Time",
  year: 1990,
  artistWikidata: "Q234693",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bonnie_Raitt",
  artistDescription: "American musician (born 1949)",
  spotify: "1gqk2dawfdLdn4XamF27cx",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Larry Henley and Jeff Silbar",
  work: "Wind Beneath My Wings",
  year: 1990,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Larry_Henley",
  artistDescription: null,
  spotify: "2pUPIxJUMfB1tDiEClligH",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Milli Vanilli",
  work: "",
  year: 1990,
  artistWikidata: "Q850540",
  artistWikipedia: "https://en.wikipedia.org/wiki/Milli_Vanilli",
  artistDescription: "German R&B/pop band",
  spotify: "3vRclCt9VnNhYIxFMQCxuM",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Quincy Jones",
  work: "Back on the Block",
  year: 1991,
  artistWikidata: "Q193645",
  artistWikipedia: "https://en.wikipedia.org/wiki/Quincy_Jones",
  artistDescription: "American record producer and composer (1933–2024)",
  spotify: "5DR4gcd3fj3E6XhbPTaF82",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Phil Collins",
  work: "Another Day in Paradise",
  year: 1991,
  artistWikidata: "Q144622",
  artistWikipedia: "https://en.wikipedia.org/wiki/Phil_Collins",
  artistDescription: "English drummer, singer, and songwriter (born 1951)",
  spotify: "1NCuYqMc8hKMb4cpNTcJbD",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Julie Gold",
  work: "From a Distance",
  year: 1991,
  artistWikidata: "Q104676598",
  artistWikipedia: "https://en.wikipedia.org/wiki/Julie_Gold",
  artistDescription: "Holocaust victim (born 1855)",
  spotify: "3K42Znx4j35Y9rXZQgg96J",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Mariah Carey",
  work: "",
  year: 1991,
  artistWikidata: "Q41076",
  artistWikipedia: "https://en.wikipedia.org/wiki/Mariah_Carey",
  artistDescription: "American singer (born 1969)",
  spotify: "4iHNK0tOyZPYnBU7nGAgpQ",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Natalie Cole",
  work: "Unforgettable... with Love",
  year: 1992,
  artistWikidata: "Q104077874",
  artistWikipedia: "https://en.wikipedia.org/wiki/Natalie_Cole",
  artistDescription: "American reality television participant",
  spotify: "4ilUfGGQXin7hr1srDDXF0",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Natalie Cole",
  work: "Unforgettable",
  year: 1992,
  artistWikidata: "Q104077874",
  artistWikipedia: "https://en.wikipedia.org/wiki/Natalie_Cole",
  artistDescription: "American reality television participant",
  spotify: "2MVQbDuhVs2muWFURtIdNb",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Irving Gordon",
  work: "Unforgettable",
  year: 1992,
  artistWikidata: "Q3802157",
  artistWikipedia: "https://en.wikipedia.org/wiki/Irving_Gordon",
  artistDescription: "American songwriter (1915–1996)",
  spotify: "6IeioFKUdA1EHZWW98FOXV",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Marc Cohn",
  work: "",
  year: 1992,
  artistWikidata: "Q1356434",
  artistWikipedia: "https://en.wikipedia.org/wiki/Marc_Cohn",
  artistDescription: "American folk rock singer-songwriter and musician",
  spotify: "2C8mKwk3z5DtqLcSwUdYJ9",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Eric Clapton",
  work: "Unplugged",
  year: 1993,
  artistWikidata: "Q48187",
  artistWikipedia: "https://en.wikipedia.org/wiki/Eric_Clapton",
  artistDescription: "British musician",
  spotify: "2lORE9lVX7YUCZfiFVnKWa",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Eric Clapton",
  work: "Tears in Heaven",
  year: 1993,
  artistWikidata: "Q48187",
  artistWikipedia: "https://en.wikipedia.org/wiki/Eric_Clapton",
  artistDescription: "British musician",
  spotify: "1kgdslQYmeTR4thk9whoRw",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Eric Clapton and Will Jennings",
  work: "Tears in Heaven",
  year: 1993,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Eric_Clapton",
  artistDescription: null,
  spotify: "1kgdslQYmeTR4thk9whoRw",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Arrested Development",
  work: "",
  year: 1993,
  artistWikidata: "Q11598",
  artistWikipedia: "https://en.wikipedia.org/wiki/Arrested_Development",
  artistDescription: null,
  spotify: "5Va9LuEmaZxnbk1gMnjMD7",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Whitney Houston",
  work: "The Bodyguard",
  year: 1994,
  artistWikidata: "Q34389",
  artistWikipedia: "https://en.wikipedia.org/wiki/Whitney_Houston",
  artistDescription: "American singer, actress, and film producer (1963–2012)",
  spotify: "7JVJlkNNobS0GSoy4tCS96",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Whitney Houston",
  work: "I Will Always Love You",
  year: 1994,
  artistWikidata: "Q34389",
  artistWikipedia: "https://en.wikipedia.org/wiki/Whitney_Houston",
  artistDescription: "American singer, actress, and film producer (1963–2012)",
  spotify: "4eHbdreAnSOrDDsFfc4Fpm",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Alan Menken and Tim Rice",
  work: "A Whole New World",
  year: 1994,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Alan_Menken",
  artistDescription: null,
  spotify: "2As6q9vyNF6JxeC1mkbFB4",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Toni Braxton",
  work: "",
  year: 1994,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Toni_Braxton",
  artistDescription: null,
  spotify: "3X458ddYA2YcVWuVIGGOYe",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Tony Bennett",
  work: "MTV Unplugged",
  year: 1995,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Tony_Bennett",
  artistDescription: null,
  spotify: "2y2RzWSrqQsOZwGlhkPp6D",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Sheryl Crow",
  work: "All I Wanna Do",
  year: 1995,
  artistWikidata: "Q200586",
  artistWikipedia: "https://en.wikipedia.org/wiki/Sheryl_Crow",
  artistDescription: "American musician (born 1962)",
  spotify: "3ZpQiJ78LKINrW9SQTgbXd",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Bruce Springsteen",
  work: "Streets of Philadelphia",
  year: 1995,
  artistWikidata: "Q1225",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bruce_Springsteen",
  artistDescription: "American rock singer (born 1949)",
  spotify: "3fbnbn6A5O5RNb08tlUEgd",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Sheryl Crow",
  work: "",
  year: 1995,
  artistWikidata: "Q200586",
  artistWikipedia: "https://en.wikipedia.org/wiki/Sheryl_Crow",
  artistDescription: "American musician (born 1962)",
  spotify: "4TKTii6gnOnUXQHyuo9JaD",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Alanis Morissette",
  work: "Jagged Little Pill",
  year: 1996,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Alanis_Morissette",
  artistDescription: null,
  spotify: "5Ap3F8CxjjsQKZGASDcHNA",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Seal",
  work: "Kiss from a Rose",
  year: 1996,
  artistWikidata: "Q218091",
  artistWikipedia: "https://en.wikipedia.org/wiki/Seal_%28musician%29",
  artistDescription: "British musician, singer, songwriter and record producer",
  spotify: "3YKptz29AsOlm7WAVnztBh",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Seal",
  work: "Kiss from a Rose",
  year: 1996,
  artistWikidata: "Q218091",
  artistWikipedia: "https://en.wikipedia.org/wiki/Seal_%28musician%29",
  artistDescription: "British musician, singer, songwriter and record producer",
  spotify: "3YKptz29AsOlm7WAVnztBh",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Hootie & the Blowfish",
  work: "",
  year: 1996,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Hootie_%26_the_Blowfish",
  artistDescription: null,
  spotify: "08ct2eZF5lUPdJpHwNKWof",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Celine Dion",
  work: "Falling into You",
  year: 1997,
  artistWikidata: "Q5105",
  artistWikipedia: "https://en.wikipedia.org/wiki/Celine_Dion",
  artistDescription: "Canadian singer (born 1968)",
  spotify: "2vk0n8aeQSO74VtQBbNDPR",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Eric Clapton",
  work: "Change the World",
  year: 1997,
  artistWikidata: "Q48187",
  artistWikipedia: "https://en.wikipedia.org/wiki/Eric_Clapton",
  artistDescription: "British musician",
  spotify: "5Ds0VGkTSQ1jf4KzLUpZPb",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Gordon Kennedy, Wayne Kirkpatrick, and Tommy Sims",
  work: "Change the World",
  year: 1997,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Gordon_Kennedy%2C_Wayne_Kirkpatrick%2C",
  artistDescription: null,
  spotify: "5qw5Frr09JiJf06mO0RIOj",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "LeAnn Rimes",
  work: "",
  year: 1997,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/LeAnn_Rimes",
  artistDescription: null,
  spotify: "2d3VHzlOEwXvmBdS4pzOPL",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Bob Dylan",
  work: "Time Out of Mind",
  year: 1998,
  artistWikidata: "Q392",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bob_Dylan",
  artistDescription: "American singer-songwriter (born 1941)",
  spotify: "185DHT5SvszXRrezx3lOjt",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Shawn Colvin",
  work: "Sunny Came Home",
  year: 1998,
  artistWikidata: "Q267438",
  artistWikipedia: "https://en.wikipedia.org/wiki/Shawn_Colvin",
  artistDescription: "American singer-songwriter",
  spotify: "4mOxpj82q6n3EO7HBZCelX",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Shawn Colvin and John Leventhal",
  work: "Sunny Came Home",
  year: 1998,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Shawn_Colvin",
  artistDescription: null,
  spotify: "4mOxpj82q6n3EO7HBZCelX",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Paula Cole",
  work: "",
  year: 1998,
  artistWikidata: "Q269462",
  artistWikipedia: "https://en.wikipedia.org/wiki/Paula_Cole",
  artistDescription: "American singer",
  spotify: "08DLZqQd6XDAVteF9nSEJ1",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Lauryn Hill",
  work: "The Miseducation of Lauryn Hill",
  year: 1999,
  artistWikidata: "Q214226",
  artistWikipedia: "https://en.wikipedia.org/wiki/Lauryn_Hill",
  artistDescription: "American singer, songwriter, rapper, and record producer (born 1975)",
  spotify: "1BZoqf8Zje5nGdwZhOjAtD",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Celine Dion",
  work: "My Heart Will Go On",
  year: 1999,
  artistWikidata: "Q5105",
  artistWikipedia: "https://en.wikipedia.org/wiki/Celine_Dion",
  artistDescription: "Canadian singer (born 1968)",
  spotify: "33LC84JgLvK2KuW43MfaNq",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "James Horner and Will Jennings",
  work: "My Heart Will Go On",
  year: 1999,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/James_Horner",
  artistDescription: null,
  spotify: "7F1yVPuJ4xRdrDvf8OL0HF",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Lauryn Hill",
  work: "",
  year: 1999,
  artistWikidata: "Q214226",
  artistWikipedia: "https://en.wikipedia.org/wiki/Lauryn_Hill",
  artistDescription: "American singer, songwriter, rapper, and record producer (born 1975)",
  spotify: "2Mu5NfyYm8n5iTomuKAEHl",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Santana",
  work: "Supernatural",
  year: 2000,
  artistWikidata: "Q1738801",
  artistWikipedia: "https://en.wikipedia.org/wiki/Santana_%28surname%29",
  artistDescription: "family name",
  spotify: "10aiDpdFGyfCFEcqpx6XTq",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Santana featuring Rob Thomas",
  work: "Smooth",
  year: 2000,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Santana",
  artistDescription: null,
  spotify: "2pX4FpOgwItRVPPUFdRcxA",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Itaal Shur and Rob Thomas",
  work: "Smooth",
  year: 2000,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Itaal_Shur",
  artistDescription: null,
  spotify: "2lxMH0NA8X98XQJBosau1n",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Christina Aguilera",
  work: "",
  year: 2000,
  artistWikidata: "Q41594",
  artistWikipedia: "https://en.wikipedia.org/wiki/Christina_Aguilera",
  artistDescription: "American singer, songwriter and actress",
  spotify: "1l7ZsJRRS8wlW3WfJfPfNS",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Steely Dan",
  work: "Two Against Nature",
  year: 2001,
  artistWikidata: "Q852435",
  artistWikipedia: "https://en.wikipedia.org/wiki/Steely_Dan",
  artistDescription: "American musical group",
  spotify: "2MJc2N3eFVT0ZabBN4zc32",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "U2",
  work: "Beautiful Day",
  year: 2001,
  artistWikidata: "Q396",
  artistWikipedia: "https://en.wikipedia.org/wiki/U2",
  artistDescription: null,
  spotify: "1VuBmEauSZywQVtqbxNqka",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "U2",
  work: "Beautiful Day",
  year: 2001,
  artistWikidata: "Q396",
  artistWikipedia: "https://en.wikipedia.org/wiki/U2",
  artistDescription: null,
  spotify: "1VuBmEauSZywQVtqbxNqka",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Shelby Lynne",
  work: "",
  year: 2001,
  artistWikidata: "Q538901",
  artistWikipedia: "https://en.wikipedia.org/wiki/Shelby_Lynne",
  artistDescription: "American singer-songwriter",
  spotify: "3xx17YXYvPl9PBx6Jzalk4",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Various Artists",
  work: "O Brother, Where Art Thou?",
  year: 2002,
  artistWikidata: "Q3108914",
  artistWikipedia: "https://en.wikipedia.org/wiki/Various_Artists",
  artistDescription: "special purpose performer (P175) credit used for compilations, tribute albums, soundtracks, etc.",
  spotify: "7gzX88qS3Vx2r87g5pbdfJ",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "U2",
  work: "Walk On",
  year: 2002,
  artistWikidata: "Q396",
  artistWikipedia: "https://en.wikipedia.org/wiki/U2",
  artistDescription: null,
  spotify: "3yjGZ9mlBxlGih186finfS",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Alicia Keys",
  work: "Fallin'",
  year: 2002,
  artistWikidata: "Q121507",
  artistWikipedia: "https://en.wikipedia.org/wiki/Alicia_Keys",
  artistDescription: "American singer-songwriter and pianist (born 1981)",
  spotify: "0KQx6HOpJueiSkztcS0r7D",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Alicia Keys",
  work: "",
  year: 2002,
  artistWikidata: "Q121507",
  artistWikipedia: "https://en.wikipedia.org/wiki/Alicia_Keys",
  artistDescription: "American singer-songwriter and pianist (born 1981)",
  spotify: "3DiDSECUqqY1AuBP8qtaIa",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Norah Jones",
  work: "Come Away with Me",
  year: 2003,
  artistWikidata: "Q549981",
  artistWikipedia: "https://en.wikipedia.org/wiki/Norah_Jones",
  artistDescription: "American musician (born 1979)",
  spotify: "7gJJme3euzF3kGQnIArnHR",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Norah Jones",
  work: "Don't Know Why",
  year: 2003,
  artistWikidata: "Q549981",
  artistWikipedia: "https://en.wikipedia.org/wiki/Norah_Jones",
  artistDescription: "American musician (born 1979)",
  spotify: "1zNXF2svmdlNxfS5XeNUgr",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Jesse Harris",
  work: "Don't Know Why",
  year: 2003,
  artistWikidata: "Q1458124",
  artistWikipedia: "https://en.wikipedia.org/wiki/Jesse_Harris",
  artistDescription: "American musician (born 1969)",
  spotify: "5zxIdU9TvcqSb4l59iy67T",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Norah Jones",
  work: "",
  year: 2003,
  artistWikidata: "Q549981",
  artistWikipedia: "https://en.wikipedia.org/wiki/Norah_Jones",
  artistDescription: "American musician (born 1979)",
  spotify: "2Kx7MNY7cI1ENniW7vT30N",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "OutKast",
  work: "Speakerboxxx/The Love Below",
  year: 2004,
  artistWikidata: "Q472595",
  artistWikipedia: "https://en.wikipedia.org/wiki/Outkast",
  artistDescription: "American hip hop duo",
  spotify: "11ScOUVhEgmsqSDhs7Ymt0",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Coldplay",
  work: "Clocks",
  year: 2004,
  artistWikidata: "Q45188",
  artistWikipedia: "https://en.wikipedia.org/wiki/Coldplay",
  artistDescription: "British rock band",
  spotify: "0BCPKOYdS2jbQ8iyB56Zns",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Luther Vandross and Richard Marx",
  work: "Dance with My Father",
  year: 2004,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Luther_Vandross",
  artistDescription: null,
  spotify: "7snmvZMLdGGk3l9PcvoYSM",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Evanescence",
  work: "",
  year: 2004,
  artistWikidata: "Q178345",
  artistWikipedia: "https://en.wikipedia.org/wiki/Evanescence_%28Evanescence_album%29",
  artistDescription: null,
  spotify: "5nGIFgo0shDenQYSE0Sn7c",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Ray Charles",
  work: "Genius Loves Company",
  year: 2005,
  artistWikidata: "Q544387",
  artistWikipedia: "https://en.wikipedia.org/wiki/Ray_Charles",
  artistDescription: "American singer, pianist and songwriter (1930–2004)",
  spotify: "1q7GZdqLKlHHwJ6vEISxKE",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Ray Charles and Norah Jones",
  work: "Here We Go Again",
  year: 2005,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Ray_Charles",
  artistDescription: null,
  spotify: "5PgeYGt6XuIbgGnGBl8fFU",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "John Mayer",
  work: "Daughters",
  year: 2005,
  artistWikidata: "Q215215",
  artistWikipedia: "https://en.wikipedia.org/wiki/John_Mayer",
  artistDescription: "American musician (born 1977)",
  spotify: "5FPnjikbwlDMULCCCa6ZCJ",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Maroon 5",
  work: "",
  year: 2005,
  artistWikidata: "Q182223",
  artistWikipedia: "https://en.wikipedia.org/wiki/Maroon_5",
  artistDescription: null,
  spotify: "04gDigrS5kc9YWfZHwBETP",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "U2",
  work: "How to Dismantle an Atomic Bomb",
  year: 2006,
  artistWikidata: "Q396",
  artistWikipedia: "https://en.wikipedia.org/wiki/U2",
  artistDescription: null,
  spotify: "5PQPur1PEZFDkI0AXbxFlB",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Green Day",
  work: "Boulevard of Broken Dreams",
  year: 2006,
  artistWikidata: "Q47871",
  artistWikipedia: "https://en.wikipedia.org/wiki/Green_Day",
  artistDescription: "American rock band",
  spotify: "1hwJKpe0BPUsq6UUrwBWTw",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Bono and U2",
  work: "Sometimes You Can't Make It on Your Own",
  year: 2006,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bono",
  artistDescription: null,
  spotify: "6fzcnVO0X2cpYjsHk19GJo",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "John Legend",
  work: "",
  year: 2006,
  artistWikidata: "Q44857",
  artistWikipedia: "https://en.wikipedia.org/wiki/John_Legend",
  artistDescription: null,
  spotify: "5y2Xq6xcjJb2jVM54GHK3t",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Dixie Chicks",
  work: "Taking the Long Way",
  year: 2007,
  artistWikidata: "Q142636",
  artistWikipedia: "https://en.wikipedia.org/wiki/The_Chicks",
  artistDescription: "American country band",
  spotify: "2NeJdEWras0uSuzLPlJZk5",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Dixie Chicks",
  work: "Not Ready to Make Nice",
  year: 2007,
  artistWikidata: "Q142636",
  artistWikipedia: "https://en.wikipedia.org/wiki/The_Chicks",
  artistDescription: "American country band",
  spotify: "6LCEyZZHFF4ebF1Mike1s5",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Dixie Chicks",
  work: "Not Ready to Make Nice",
  year: 2007,
  artistWikidata: "Q142636",
  artistWikipedia: "https://en.wikipedia.org/wiki/The_Chicks",
  artistDescription: "American country band",
  spotify: "6LCEyZZHFF4ebF1Mike1s5",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Carrie Underwood",
  work: "",
  year: 2007,
  artistWikidata: "Q215546",
  artistWikipedia: "https://en.wikipedia.org/wiki/Carrie_Underwood",
  artistDescription: "American singer and actor (born 1983)",
  spotify: "4xFUf1FHVy696Q1JQZMTRj",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Herbie Hancock",
  work: "River: The Joni Letters",
  year: 2008,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Herbie_Hancock",
  artistDescription: null,
  spotify: "3GwR5VxaMzB01ay6qIT3Yq",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Amy Winehouse",
  work: "Rehab",
  year: 2008,
  artistWikidata: "Q15897",
  artistWikipedia: "https://en.wikipedia.org/wiki/Amy_Winehouse",
  artistDescription: "British singer-songwriter (1983–2011)",
  spotify: "1L5tZi0izXsi5Kk5OJf4W0",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Amy Winehouse",
  work: "Rehab",
  year: 2008,
  artistWikidata: "Q15897",
  artistWikipedia: "https://en.wikipedia.org/wiki/Amy_Winehouse",
  artistDescription: "British singer-songwriter (1983–2011)",
  spotify: "1L5tZi0izXsi5Kk5OJf4W0",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Amy Winehouse",
  work: "",
  year: 2008,
  artistWikidata: "Q15897",
  artistWikipedia: "https://en.wikipedia.org/wiki/Amy_Winehouse",
  artistDescription: "British singer-songwriter (1983–2011)",
  spotify: "6Q192DXotxtaysaqNPy5yR",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Robert Plant and Alison Krauss",
  work: "Raising Sand",
  year: 2009,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Robert_Plant",
  artistDescription: null,
  spotify: "3E3qeXLdDtaX16OV4kbNoF",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Robert Plant and Alison Krauss",
  work: "Please Read the Letter",
  year: 2009,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Robert_Plant",
  artistDescription: null,
  spotify: "1m5N9YCZL4BXuSXdYmhRaj",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Coldplay",
  work: "Viva la Vida",
  year: 2009,
  artistWikidata: "Q45188",
  artistWikipedia: "https://en.wikipedia.org/wiki/Coldplay",
  artistDescription: "British rock band",
  spotify: "1mea3bSkSGXuIRvnydlB5b",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Adele",
  work: "",
  year: 2009,
  artistWikidata: "Q354370",
  artistWikipedia: "https://en.wikipedia.org/wiki/Adele_%28given_name%29",
  artistDescription: "female given name",
  spotify: "4dpARuHxo51G3z768sgnrY",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Taylor Swift",
  work: "Fearless",
  year: 2010,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Taylor_Swift",
  artistDescription: null,
  spotify: "2dqn5yOQWdyGwOpOIi9O4x",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Kings of Leon",
  work: "Use Somebody",
  year: 2010,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Kings_of_Leon",
  artistDescription: null,
  spotify: "5VGlqQANWDKJFl0MBG3sg2",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Beyonce",
  work: "Single Ladies (Put a Ring on It)",
  year: 2010,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Beyonce",
  artistDescription: null,
  spotify: "5R9a4t5t5O0IsznsrKPVro",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Zac Brown Band",
  work: "",
  year: 2010,
  artistWikidata: "Q139154",
  artistWikipedia: "https://en.wikipedia.org/wiki/Zac_Brown_Band",
  artistDescription: null,
  spotify: "6yJCxee7QumYr820xdIsjo",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Arcade Fire",
  work: "The Suburbs",
  year: 2011,
  artistWikidata: "Q58608",
  artistWikipedia: "https://en.wikipedia.org/wiki/Arcade_Fire",
  artistDescription: "Canadian indie rock band",
  spotify: "3DrgM5X3yX1JP1liNLAOHI",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Lady Antebellum",
  work: "Need You Now",
  year: 2011,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Lady_Antebellum",
  artistDescription: null,
  spotify: "11EX5yhxr9Ihl3IN1asrfK",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Lady Antebellum",
  work: "Need You Now",
  year: 2011,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Lady_Antebellum",
  artistDescription: null,
  spotify: "11EX5yhxr9Ihl3IN1asrfK",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Esperanza Spalding",
  work: "",
  year: 2011,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Esperanza_Spalding",
  artistDescription: null,
  spotify: "5bepW5vcdRzheNc0F8lHJ5",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Adele",
  work: "21",
  year: 2012,
  artistWikidata: "Q354370",
  artistWikipedia: "https://en.wikipedia.org/wiki/Adele_%28given_name%29",
  artistDescription: "female given name",
  spotify: "0Lg1uZvI312TPqxNWShFXL",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Adele",
  work: "Rolling in the Deep",
  year: 2012,
  artistWikidata: "Q354370",
  artistWikipedia: "https://en.wikipedia.org/wiki/Adele_%28given_name%29",
  artistDescription: "female given name",
  spotify: "1c8gk2PeTE04A1pIDH9YMk",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Adele and Paul Epworth",
  work: "Rolling in the Deep",
  year: 2012,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Adele",
  artistDescription: null,
  spotify: "1c8gk2PeTE04A1pIDH9YMk",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Bon Iver",
  work: "",
  year: 2012,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bon_Iver",
  artistDescription: null,
  spotify: "4LEiUm1SRbFMgfqnQTwUbQ",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Mumford & Sons",
  work: "Babel",
  year: 2013,
  artistWikidata: "Q953918",
  artistWikipedia: "https://en.wikipedia.org/wiki/Mumford_%26_Sons",
  artistDescription: "British folk rock band",
  spotify: "3Nh0tCxlg0iax1EGg6fjbh",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Gotye featuring Kimbra",
  work: "Somebody That I Used to Know",
  year: 2013,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Gotye",
  artistDescription: null,
  spotify: "4wCmqSrbyCgxEXROQE6vtV",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "fun.",
  work: "We Are Young",
  year: 2013,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/fun.",
  artistDescription: null,
  spotify: "7a86XRg84qjasly9f6bPSD",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "fun.",
  work: "",
  year: 2013,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/fun.",
  artistDescription: null,
  spotify: "6o2VsYOl5FxnOJYvod1Q8p",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Daft Punk",
  work: "Random Access Memories",
  year: 2014,
  artistWikidata: "Q185828",
  artistWikipedia: "https://en.wikipedia.org/wiki/Daft_Punk",
  artistDescription: "French electronic music band",
  spotify: "4m2880jivSbbyEGAKfITCa",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Daft Punk featuring Pharrell Williams and Nile Rodgers",
  work: "Get Lucky",
  year: 2014,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Daft_Punk",
  artistDescription: null,
  spotify: "69kOkLUCkxIZYexIgSG8rq",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Lorde",
  work: "Royals",
  year: 2014,
  artistWikidata: "Q13476175",
  artistWikipedia: "https://en.wikipedia.org/wiki/Lorde",
  artistDescription: "Croatian-New Zealand singer, songwriter and producer (born 1996)",
  spotify: "4SDWMFvYJKtK1QPhIOeZhd",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Macklemore & Ryan Lewis",
  work: "",
  year: 2014,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Macklemore_%26_Ryan_Lewis",
  artistDescription: null,
  spotify: "5BcAKTbp20cv7tC5VqPFoC",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Beck",
  work: "Morning Phase",
  year: 2015,
  artistWikidata: "Q2659856",
  artistWikipedia: "https://en.wikipedia.org/wiki/Beck_%28surname%29",
  artistDescription: "family name",
  spotify: "2Qx7dgA5VjX8JDQaXVxzHu",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Sam Smith",
  work: "Stay with Me",
  year: 2015,
  artistWikidata: "Q15123969",
  artistWikipedia: "https://en.wikipedia.org/wiki/Sam_Smith",
  artistDescription: "British singer-songwriter",
  spotify: "5Nm9ERjJZ5oyfXZTECKmRt",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Sam Smith",
  work: "Stay with Me",
  year: 2015,
  artistWikidata: "Q15123969",
  artistWikipedia: "https://en.wikipedia.org/wiki/Sam_Smith",
  artistDescription: "British singer-songwriter",
  spotify: "5Nm9ERjJZ5oyfXZTECKmRt",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Sam Smith",
  work: "",
  year: 2015,
  artistWikidata: "Q15123969",
  artistWikipedia: "https://en.wikipedia.org/wiki/Sam_Smith",
  artistDescription: "British singer-songwriter",
  spotify: "2wY79sveU1sp5g7SokKOiI",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Taylor Swift",
  work: "1989",
  year: 2016,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Taylor_Swift",
  artistDescription: null,
  spotify: "64LU4c1nfjz1t4VnGhagcg",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Mark Ronson featuring Bruno Mars",
  work: "Uptown Funk",
  year: 2016,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Mark_Ronson",
  artistDescription: null,
  spotify: "32OlwWuMpZ6b0aN2RZOeMS",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Ed Sheeran",
  work: "Thinking Out Loud",
  year: 2016,
  artistWikidata: "Q47447",
  artistWikipedia: "https://en.wikipedia.org/wiki/Ed_Sheeran",
  artistDescription: "English singer-songwriter (born 1991)",
  spotify: "34gCuhDGsG4bRPIf9bb02f",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Meghan Trainor",
  work: "",
  year: 2016,
  artistWikidata: "Q17403494",
  artistWikipedia: "https://en.wikipedia.org/wiki/Meghan_Trainor",
  artistDescription: "American singer-songwriter (born 1993)",
  spotify: "6JL8zeS1NmiOftqZTRgdTz",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Adele",
  work: "25",
  year: 2017,
  artistWikidata: "Q354370",
  artistWikipedia: "https://en.wikipedia.org/wiki/Adele_%28given_name%29",
  artistDescription: "female given name",
  spotify: "3AvPX1B1HiFROvYjLb5Qwi",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Adele",
  work: "Hello",
  year: 2017,
  artistWikidata: "Q354370",
  artistWikipedia: "https://en.wikipedia.org/wiki/Adele_%28given_name%29",
  artistDescription: "female given name",
  spotify: "62PaSfnXSMyLshYJrlTuL3",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Adele",
  work: "Hello",
  year: 2017,
  artistWikidata: "Q354370",
  artistWikipedia: "https://en.wikipedia.org/wiki/Adele_%28given_name%29",
  artistDescription: "female given name",
  spotify: "62PaSfnXSMyLshYJrlTuL3",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Chance the Rapper",
  work: "",
  year: 2017,
  artistWikidata: "Q12470060",
  artistWikipedia: "https://en.wikipedia.org/wiki/Chance_the_Rapper",
  artistDescription: "American rapper, singer and record producer (born 1993)",
  spotify: "1anyVhU62p31KFi8MEzkbf",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Bruno Mars",
  work: "24K Magic",
  year: 2018,
  artistWikidata: "Q1450",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bruno_Mars",
  artistDescription: "American singer-songwriter and record producer (born 1985)",
  spotify: "4PgleR09JVnm3zY1fW3XBA",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Bruno Mars",
  work: "24K Magic",
  year: 2018,
  artistWikidata: "Q1450",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bruno_Mars",
  artistDescription: "American singer-songwriter and record producer (born 1985)",
  spotify: "6b8Be6ljOzmkOmFslEb23P",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Bruno Mars",
  work: "That's What I Like",
  year: 2018,
  artistWikidata: "Q1450",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bruno_Mars",
  artistDescription: "American singer-songwriter and record producer (born 1985)",
  spotify: "0KKkJNfGyhkQ5aFogxQAPU",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Alessia Cara",
  work: "",
  year: 2018,
  artistWikidata: "Q20090091",
  artistWikipedia: "https://en.wikipedia.org/wiki/Alessia_Cara",
  artistDescription: "Italian-Canadian singer, songwriter and actress",
  spotify: "2wUjUUtkb5lvLKcGKsKqsR",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Kacey Musgraves",
  work: "Golden Hour",
  year: 2019,
  artistWikidata: "Q2783855",
  artistWikipedia: "https://en.wikipedia.org/wiki/Kacey_Musgraves",
  artistDescription: "American singer (born 1988)",
  spotify: "7f6xPqyaolTiziKf5R5Z0c",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Childish Gambino",
  work: "This Is America",
  year: 2019,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Childish_Gambino",
  artistDescription: null,
  spotify: "0b9oOr2ZgvyQu88wzixux9",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Childish Gambino",
  work: "This Is America",
  year: 2019,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Childish_Gambino",
  artistDescription: null,
  spotify: "0b9oOr2ZgvyQu88wzixux9",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Dua Lipa",
  work: "",
  year: 2019,
  artistWikidata: "Q21914464",
  artistWikipedia: "https://en.wikipedia.org/wiki/Dua_Lipa",
  artistDescription: "British singer-songwriter",
  spotify: "6M2wZ9GZgrQXHCFfjv46we",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Billie Eilish",
  work: "When We All Fall Asleep, Where Do We Go?",
  year: 2020,
  artistWikidata: "Q29564107",
  artistWikipedia: "https://en.wikipedia.org/wiki/Billie_Eilish",
  artistDescription: "American singer-songwriter (born 2001)",
  spotify: "0S0KGZnfBGSIssfF54WSJh",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Billie Eilish",
  work: "Bad Guy",
  year: 2020,
  artistWikidata: "Q29564107",
  artistWikipedia: "https://en.wikipedia.org/wiki/Billie_Eilish",
  artistDescription: "American singer-songwriter (born 2001)",
  spotify: "2Fxmhks0bxGSBdJ92vM42m",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Billie Eilish",
  work: "Bad Guy",
  year: 2020,
  artistWikidata: "Q29564107",
  artistWikipedia: "https://en.wikipedia.org/wiki/Billie_Eilish",
  artistDescription: "American singer-songwriter (born 2001)",
  spotify: "2Fxmhks0bxGSBdJ92vM42m",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Billie Eilish",
  work: "",
  year: 2020,
  artistWikidata: "Q29564107",
  artistWikipedia: "https://en.wikipedia.org/wiki/Billie_Eilish",
  artistDescription: "American singer-songwriter (born 2001)",
  spotify: "6qqNVTkY8uBg9cP3Jd7DAH",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Taylor Swift",
  work: "Folklore",
  year: 2021,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Taylor_Swift",
  artistDescription: null,
  spotify: "2fenSS68JI1h4Fo296JfGr",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Billie Eilish",
  work: "Everything I Wanted",
  year: 2021,
  artistWikidata: "Q29564107",
  artistWikipedia: "https://en.wikipedia.org/wiki/Billie_Eilish",
  artistDescription: "American singer-songwriter (born 2001)",
  spotify: "3ZCTVFBt2Brf31RLEnCkWJ",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "H.E.R.",
  work: "I Can't Breathe",
  year: 2021,
  artistWikidata: "Q30639849",
  artistWikipedia: "https://en.wikipedia.org/wiki/H.E.R.",
  artistDescription: "American R&B singer",
  spotify: "4CPszpSnlbgnQLIQYyzIR2",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Megan Thee Stallion",
  work: "",
  year: 2021,
  artistWikidata: "Q59268408",
  artistWikipedia: "https://en.wikipedia.org/wiki/Megan_Thee_Stallion",
  artistDescription: "American rapper, singer and songwriter",
  spotify: "181bsRPaVXVlUKXrxwZfHK",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Jon Batiste",
  work: "We Are",
  year: 2022,
  artistWikidata: "Q6272528",
  artistWikipedia: "https://en.wikipedia.org/wiki/Jon_Batiste",
  artistDescription: "American musician and singer (b. 1986)",
  spotify: "6kHFkPvL2X3rZPuS3CEMUE",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Silk Sonic",
  work: "Leave the Door Open",
  year: 2022,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Silk_Sonic",
  artistDescription: null,
  spotify: "4pryE6cN2gFL1FVF5fYINl",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Silk Sonic",
  work: "Leave the Door Open",
  year: 2022,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Silk_Sonic",
  artistDescription: null,
  spotify: "4pryE6cN2gFL1FVF5fYINl",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Olivia Rodrigo",
  work: "",
  year: 2022,
  artistWikidata: "Q63243883",
  artistWikipedia: "https://en.wikipedia.org/wiki/Olivia_Rodrigo",
  artistDescription: "American singer-songwriter and actress",
  spotify: "1McMsnEElThX1knmY4oliG",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Harry Styles",
  work: "Harry's House",
  year: 2023,
  artistWikidata: "Q3626966",
  artistWikipedia: "https://en.wikipedia.org/wiki/Harry_Styles",
  artistDescription: null,
  spotify: "6XCpLLxr9adk3jwrHLqRLQ",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Lizzo",
  work: "About Damn Time",
  year: 2023,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Lizzo",
  artistDescription: null,
  spotify: "6HMtHNpW6YPi1hrw9tgF8P",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Bonnie Raitt",
  work: "Just Like That",
  year: 2023,
  artistWikidata: "Q234693",
  artistWikipedia: "https://en.wikipedia.org/wiki/Bonnie_Raitt",
  artistDescription: "American musician (born 1949)",
  spotify: "4yYi79a3MEQ0pCRCvuxcuU",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Samara Joy",
  work: "",
  year: 2023,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Samara_Joy",
  artistDescription: null,
  spotify: "5LkbTSqXfMBjFSGi9LOGjq",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Taylor Swift",
  work: "Midnights",
  year: 2024,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Taylor_Swift",
  artistDescription: null,
  spotify: "151w1FgRZfnKZA9FEcg9Z3",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Miley Cyrus",
  work: "Flowers",
  year: 2024,
  artistWikidata: "Q4235",
  artistWikipedia: "https://en.wikipedia.org/wiki/Miley_Cyrus",
  artistDescription: null,
  spotify: "7DSAEUvxU8FajXtRloy8M0",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Billie Eilish",
  work: "What Was I Made For?",
  year: 2024,
  artistWikidata: "Q29564107",
  artistWikipedia: "https://en.wikipedia.org/wiki/Billie_Eilish",
  artistDescription: "American singer-songwriter (born 2001)",
  spotify: "6wf7Yu7cxBSPrRlWeSeK0Q",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Victoria Monet",
  work: "",
  year: 2024,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Victoria_Monet",
  artistDescription: null,
  spotify: "63XBtGSEZINSyXylZxEUbv",
  spotifyType: "artist"
},
{
  category: "Album of the Year",
  categoryShort: "AOTY",
  artist: "Beyonce",
  work: "Cowboy Carter",
  year: 2025,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Beyonce",
  artistDescription: null,
  spotify: "6BzxX6zkDsYKFJ04ziU5xQ",
  spotifyType: "album"
},
{
  category: "Record of the Year",
  categoryShort: "ROTY",
  artist: "Beyonce",
  work: "Texas Hold 'Em",
  year: 2025,
  artistWikidata: "",
  artistWikipedia: "https://en.wikipedia.org/wiki/Beyonce",
  artistDescription: null,
  spotify: "0Z7nGFVCLfixWctgePsRk9",
  spotifyType: "track"
},
{
  category: "Song of the Year",
  categoryShort: "SOTY",
  artist: "Shaboozey",
  work: "A Bar Song (Tipsy)",
  year: 2025,
  artistWikidata: "Q125295750",
  artistWikipedia: "https://en.wikipedia.org/wiki/Shaboozey",
  artistDescription: "American singer (born 1995)",
  spotify: "2FQrifJ1N335Ljm3TjTVVf",
  spotifyType: "track"
},
{
  category: "Best New Artist",
  categoryShort: "BNA",
  artist: "Chappell Roan",
  work: "",
  year: 2025,
  artistWikidata: "Q110281146",
  artistWikipedia: "https://en.wikipedia.org/wiki/Chappell_Roan",
  artistDescription: "American singer (born 1998)",
  spotify: "7GlBOeep6PqTfFi59PTUUN",
  spotifyType: "artist"
}
];
