window.SONGS_DATA = [
{
  song: "The Continental",
  film: "The Gay Divorcee",
  year: 1935,
  filmYear: 1934,
  songwriters: ["Con Conrad", "Herb Magidson"],
  performers: ["Ginger Rogers"],
  spotify: "5zPMzOLIyKspjGM3nRa7zy",
  wikipedia: null,
  wikidata: "Q7730754"
},
{
  song: "Lullaby of Broadway",
  film: "Gold Diggers of 1935",
  year: 1936,
  filmYear: 1935,
  songwriters: ["Harry Warren", "Al Dubin"],
  performers: ["Wini Shaw"],
  spotify: "7tC6UY03PQQUzOjWAbdZmZ",
  wikipedia: null,
  wikidata: "Q1872255"
},
{
  song: "The Way You Look Tonight",
  film: "Swing Time",
  year: 1937,
  filmYear: 1936,
  songwriters: ["Jerome Kern", "Dorothy Fields"],
  performers: ["Fred Astaire"],
  spotify: "6ALpCzjVWFQJRwKIM8he8F",
  wikipedia: "https://en.wikipedia.org/wiki/Garabandal_apparitions",
  wikidata: "Q1066282"
},
{
  song: "Sweet Leilani",
  film: "Waikiki Wedding",
  year: 1938,
  filmYear: 1937,
  songwriters: ["Harry Owens"],
  performers: ["Bing Crosby"],
  spotify: "1HOtHVowS8frSOJvZoqOJ9",
  wikipedia: "https://en.wikipedia.org/wiki/Swede_Youngstrom",
  wikidata: "Q7654271"
},
{
  song: "Thanks for the Memory",
  film: "The Big Broadcast of 1938",
  year: 1939,
  filmYear: 1938,
  songwriters: ["Ralph Rainger", "Leo Robin"],
  performers: ["Bob Hope", "Shirley Ross"],
  spotify: "1qVwptCd8xqwr2zzO1djvi",
  wikipedia: "https://en.wikipedia.org/wiki/J._M._Weston",
  wikidata: "Q2399832"
},
{
  song: "Over the Rainbow",
  film: "The Wizard of Oz",
  year: 1940,
  filmYear: 1939,
  songwriters: ["Harold Arlen", "Yip Harburg"],
  performers: ["Judy Garland"],
  spotify: "1p7C97Xibwh0jL85jhdOZv",
  wikipedia: null,
  wikidata: "Q209346"
},
{
  song: "When You Wish Upon a Star",
  film: "Pinocchio",
  year: 1941,
  filmYear: 1940,
  songwriters: ["Leigh Harline", "Ned Washington"],
  performers: ["Cliff Edwards"],
  spotify: "1WrPa4lrIddctGWAIYYfP9",
  wikipedia: null,
  wikidata: "Q1140279"
},
{
  song: "The Last Time I Saw Paris",
  film: "Lady Be Good",
  year: 1942,
  filmYear: 1941,
  songwriters: ["Jerome Kern", "Oscar Hammerstein II"],
  performers: ["Ann Sothern"],
  spotify: "0DapUVR8Vgw7b6NQbw1jxr",
  wikipedia: "https://en.wikipedia.org/wiki/Lawas",
  wikidata: "Q6503576"
},
{
  song: "White Christmas",
  film: "Holiday Inn",
  year: 1943,
  filmYear: 1942,
  songwriters: ["Irving Berlin"],
  performers: ["Bing Crosby"],
  spotify: "7134tEHq45eL6am9oVazZU",
  wikipedia: "https://en.wikipedia.org/wiki/Berezina",
  wikidata: "Q207927"
},
{
  song: "You'll Never Know",
  film: "Hello, Frisco, Hello",
  year: 1944,
  filmYear: 1943,
  songwriters: ["Harry Warren", "Mack Gordon"],
  performers: ["Alice Faye"],
  spotify: "06UY42Kc7qFYw9TT4gr5Kz",
  wikipedia: "https://en.wikipedia.org/wiki/Yorkshire_Volunteers",
  wikidata: "Q8055759"
},
{
  song: "Swinging on a Star",
  film: "Going My Way",
  year: 1945,
  filmYear: 1944,
  songwriters: ["Jimmy Van Heusen", "Johnny Burke"],
  performers: ["Bing Crosby"],
  spotify: "7xy0PAZxzGDOcYzyptvprd",
  wikipedia: "https://en.wikipedia.org/wiki/Mickey_Simmonds",
  wikidata: "Q3511236"
},
{
  song: "It Might as Well Be Spring",
  film: "State Fair",
  year: 1946,
  filmYear: 1945,
  songwriters: ["Richard Rodgers", "Oscar Hammerstein II"],
  performers: ["Louanne Hogan"],
  spotify: "4hf3hI4k42IHygDrKG3lg5",
  wikipedia: null,
  wikidata: "Q6090099"
},
{
  song: "On the Atchison, Topeka and the Santa Fe",
  film: "The Harvey Girls",
  year: 1947,
  filmYear: 1946,
  songwriters: ["Harry Warren", "Johnny Mercer"],
  performers: ["Judy Garland"],
  spotify: "2LWVbs3KBWiG80qxM2oa64",
  wikipedia: null,
  wikidata: "Q7090254"
},
{
  song: "Zip-a-Dee-Doo-Dah",
  film: "Song of the South",
  year: 1948,
  filmYear: 1946,
  songwriters: ["Allie Wrubel", "Ray Gilbert"],
  performers: ["James Baskett"],
  spotify: "1fQ2pN9MLxxi399nlHEth7",
  wikipedia: "https://en.wikipedia.org/wiki/Vranovice_%28Brno-Country_District%29",
  wikidata: "Q2002948"
},
{
  song: "Buttons and Bows",
  film: "The Paleface",
  year: 1949,
  filmYear: 1948,
  songwriters: ["Jay Livingston", "Ray Evans"],
  performers: ["Bob Hope"],
  spotify: "4WhRgJ2UPL1GO2bOlFnnHD",
  wikipedia: null,
  wikidata: "Q4001968"
},
{
  song: "Baby, It's Cold Outside",
  film: "Neptune's Daughter",
  year: 1950,
  filmYear: 1949,
  songwriters: ["Frank Loesser"],
  performers: ["Esther Williams", "Ricardo Montalban"],
  spotify: "3TKJfv3RJRYfmi4Pg825nk",
  wikipedia: null,
  wikidata: "Q2878523"
},
{
  song: "Mona Lisa",
  film: "Captain Carey, U.S.A.",
  year: 1951,
  filmYear: 1950,
  songwriters: ["Jay Livingston", "Ray Evans"],
  performers: ["Nat King Cole"],
  spotify: "5dae01pKNjRQtgOeAkFzPY",
  wikipedia: "https://en.wikipedia.org/wiki/Moritz_Rittinghausen",
  wikidata: "Q1948042"
},
{
  song: "In the Cool, Cool, Cool of the Evening",
  film: "Here Comes the Groom",
  year: 1952,
  filmYear: 1951,
  songwriters: ["Hoagy Carmichael", "Johnny Mercer"],
  performers: ["Bing Crosby", "Jane Wyman"],
  spotify: "0ebXSj5HKwZ9gH78O2xjYR",
  wikipedia: null,
  wikidata: "Q6016908"
},
{
  song: "High Noon (Do Not Forsake Me, Oh My Darlin')",
  film: "High Noon",
  year: 1953,
  filmYear: 1952,
  songwriters: ["Dimitri Tiomkin", "Ned Washington"],
  performers: ["Tex Ritter"],
  spotify: "3brwF7h3utczuzDWaDVviL",
  wikipedia: "https://en.wikipedia.org/wiki/Hilaria_Kramer",
  wikidata: "Q1618096"
},
{
  song: "Secret Love",
  film: "Calamity Jane",
  year: 1954,
  filmYear: 1953,
  songwriters: ["Sammy Fain", "Paul Francis Webster"],
  performers: ["Doris Day"],
  spotify: "5wzjc23Qsn7wN75eLMvFEc",
  wikipedia: "https://en.wikipedia.org/wiki/W._Scott_Darling",
  wikidata: "Q3476195"
},
{
  song: "Three Coins in the Fountain",
  film: "Three Coins in the Fountain",
  year: 1955,
  filmYear: 1954,
  songwriters: ["Jule Styne", "Sammy Cahn"],
  performers: ["Frank Sinatra"],
  spotify: "2LnTydfDh8VOvJH7cSLqjS",
  wikipedia: null,
  wikidata: "Q2329994"
},
{
  song: "Love Is a Many-Splendored Thing",
  film: "Love Is a Many-Splendored Thing",
  year: 1956,
  filmYear: 1955,
  songwriters: ["Sammy Fain", "Paul Francis Webster"],
  performers: ["The Four Aces"],
  spotify: "5koEBSDfDV8MQVN0tg67z5",
  wikipedia: "https://en.wikipedia.org/wiki/Li_Fan_%28Tang_dynasty%29",
  wikidata: "Q6538757"
},
{
  song: "Whatever Will Be, Will Be (Que Sera, Sera)",
  film: "The Man Who Knew Too Much",
  year: 1957,
  filmYear: 1956,
  songwriters: ["Jay Livingston", "Ray Evans"],
  performers: ["Doris Day"],
  spotify: "6yhLR2sVn1IfsScVrR4ocr",
  wikipedia: "https://en.wikipedia.org/wiki/Sailor_Saturn",
  wikidata: "Q913373"
},
{
  song: "All the Way",
  film: "The Joker Is Wild",
  year: 1958,
  filmYear: 1957,
  songwriters: ["Jimmy Van Heusen", "Sammy Cahn"],
  performers: ["Frank Sinatra"],
  spotify: "1ktkBoXdDHD2N856EVKKTp",
  wikipedia: "https://en.wikipedia.org/wiki/Alicia_Le_Fanu",
  wikidata: "Q4726268"
},
{
  song: "Gigi",
  film: "Gigi",
  year: 1959,
  filmYear: 1958,
  songwriters: ["Frederick Loewe", "Alan Jay Lerner"],
  performers: ["Louis Jourdan"],
  spotify: "6j7o72c7jVIlvJOW6PgWeT",
  wikipedia: "https://en.wikipedia.org/wiki/K%C3%B6penick%27s_week_of_bloodshed",
  wikidata: "Q1524823"
},
{
  song: "High Hopes",
  film: "A Hole in the Head",
  year: 1960,
  filmYear: 1959,
  songwriters: ["Jimmy Van Heusen", "Sammy Cahn"],
  performers: ["Frank Sinatra"],
  spotify: "68sTztCNUapkQL0nEKfrM5",
  wikipedia: "https://en.wikipedia.org/wiki/Mastani",
  wikidata: "Q3785174"
},
{
  song: "Never on Sunday",
  film: "Never on Sunday",
  year: 1961,
  filmYear: 1960,
  songwriters: ["Manos Hadjidakis"],
  performers: ["Melina Mercouri"],
  spotify: "4qQ7eddVdtio09WkiNWEhu",
  wikipedia: null,
  wikidata: "Q3338067"
},
{
  song: "Moon River",
  film: "Breakfast at Tiffany's",
  year: 1962,
  filmYear: 1961,
  songwriters: ["Henry Mancini", "Johnny Mercer"],
  performers: ["Audrey Hepburn"],
  spotify: "1XwAKjAZ1xDZOcuyZoqce4",
  wikipedia: "https://en.wikipedia.org/wiki/Bhimashankar_Wildlife_Sanctuary",
  wikidata: "Q854971"
},
{
  song: "Days of Wine and Roses",
  film: "Days of Wine and Roses",
  year: 1963,
  filmYear: 1962,
  songwriters: ["Henry Mancini", "Johnny Mercer"],
  performers: ["Andy Williams"],
  spotify: "3tvqPPpXyIgKrm4PR9HCf0",
  wikipedia: "https://en.wikipedia.org/wiki/Y%C5%ABta",
  wikidata: "Q3018082"
},
{
  song: "Call Me Irresponsible",
  film: "Papa's Delicate Condition",
  year: 1964,
  filmYear: 1963,
  songwriters: ["Jimmy Van Heusen", "Sammy Cahn"],
  performers: ["Jackie Gleason"],
  spotify: "5LAwJN9tqGeyduMb4B4r4G",
  wikipedia: "https://en.wikipedia.org/wiki/Calm_Down_%28Killing_Heidi_song%29",
  wikidata: "Q5023026"
},
{
  song: "Chim Chim Cher-ee",
  film: "Mary Poppins",
  year: 1965,
  filmYear: 1964,
  songwriters: ["Richard M. Sherman", "Robert B. Sherman"],
  performers: ["Dick Van Dyke", "Julie Andrews"],
  spotify: "0IKYsgkoaylTKGzrlfrpu7",
  wikipedia: null,
  wikidata: "Q1073399"
},
{
  song: "The Shadow of Your Smile",
  film: "The Sandpiper",
  year: 1966,
  filmYear: 1965,
  songwriters: ["Johnny Mandel", "Paul Francis Webster"],
  performers: ["Tony Bennett"],
  spotify: "66YI4JFp7BcMcepibGprsN",
  wikipedia: null,
  wikidata: "Q3523429"
},
{
  song: "Born Free",
  film: "Born Free",
  year: 1967,
  filmYear: 1966,
  songwriters: ["John Barry", "Don Black"],
  performers: ["Matt Monro"],
  spotify: "2c2WEz0vMVvR7Gc27O3sLs",
  wikipedia: "https://en.wikipedia.org/wiki/Phrynocephalus_versicolor",
  wikidata: "Q2665620"
},
{
  song: "Talk to the Animals",
  film: "Doctor Dolittle",
  year: 1968,
  filmYear: 1967,
  songwriters: ["Leslie Bricusse"],
  performers: ["Rex Harrison"],
  spotify: "1Mf27cnAF1Q6Ko83XTM5d1",
  wikipedia: "https://en.wikipedia.org/wiki/Talmadge_River",
  wikidata: "Q7680236"
},
{
  song: "The Windmills of Your Mind",
  film: "The Thomas Crown Affair",
  year: 1969,
  filmYear: 1968,
  songwriters: ["Michel Legrand", "Alan Bergman", "Marilyn Bergman"],
  performers: ["Noel Harrison"],
  spotify: "0LAJmyoZLS5ay5zFLtWDgM",
  wikipedia: "https://en.wikipedia.org/wiki/1963_NFL_season",
  wikidata: "Q1753757"
},
{
  song: "Raindrops Keep Fallin' on My Head",
  film: "Butch Cassidy and the Sundance Kid",
  year: 1970,
  filmYear: 1969,
  songwriters: ["Burt Bacharach", "Hal David"],
  performers: ["B.J. Thomas"],
  spotify: "0oMTxTIHAt3hstaoObsmFs",
  wikipedia: null,
  wikidata: "Q1501922"
},
{
  song: "For All We Know",
  film: "Lovers and Other Strangers",
  year: 1971,
  filmYear: 1970,
  songwriters: ["Fred Karlin", "Robb Royer", "James Griffin"],
  performers: ["Larry Meredith"],
  spotify: "4QNpBfC0zvjKqPJcyqBy9W",
  wikipedia: "https://en.wikipedia.org/wiki/Football_at_the_2011_Pan_American_Games_%E2%80%93_Men%27s_team_squads",
  wikidata: "Q5466139"
},
{
  song: "Theme from Shaft",
  film: "Shaft",
  year: 1972,
  filmYear: 1971,
  songwriters: ["Isaac Hayes"],
  performers: ["Isaac Hayes"],
  spotify: "7KMILVTQdVS4zQ8ilTcpRO",
  wikipedia: "https://en.wikipedia.org/wiki/The_Girl_Who_Returned",
  wikidata: "Q3987260"
},
{
  song: "The Morning After",
  film: "The Poseidon Adventure",
  year: 1973,
  filmYear: 1972,
  songwriters: ["Al Kasha", "Joel Hirschhorn"],
  performers: ["Maureen McGovern"],
  spotify: "62QRbVm7DqR3eoqgT7pEfs",
  wikipedia: "https://en.wikipedia.org/wiki/The_Moodists",
  wikidata: "Q3521912"
},
{
  song: "The Way We Were",
  film: "The Way We Were",
  year: 1974,
  filmYear: 1973,
  songwriters: ["Marvin Hamlisch", "Alan Bergman", "Marilyn Bergman"],
  performers: ["Barbra Streisand"],
  spotify: "1vZTgn4JXWMahR8r99ug5H",
  wikipedia: "https://en.wikipedia.org/wiki/%C4%8Cachrov",
  wikidata: "Q2538389"
},
{
  song: "We May Never Love Like This Again",
  film: "The Towering Inferno",
  year: 1975,
  filmYear: 1974,
  songwriters: ["Al Kasha", "Joel Hirschhorn"],
  performers: ["Maureen McGovern"],
  spotify: "4k8AOuix44BSULHnrnAnEq",
  wikipedia: "https://en.wikipedia.org/wiki/We%27re_Coming_Home",
  wikidata: "Q7977090"
},
{
  song: "I'm Easy",
  film: "Nashville",
  year: 1976,
  filmYear: 1975,
  songwriters: ["Keith Carradine"],
  performers: ["Keith Carradine"],
  spotify: "4UN5z3IkTamNxngTsS3Qrm",
  wikipedia: null,
  wikidata: "Q5918918"
},
{
  song: "Evergreen",
  film: "A Star Is Born",
  year: 1977,
  filmYear: 1976,
  songwriters: ["Barbra Streisand", "Paul Williams"],
  performers: ["Barbra Streisand"],
  spotify: "0j3GgpDSr6ROmp49hcocNR",
  wikipedia: null,
  wikidata: "Q5417407"
},
{
  song: "You Light Up My Life",
  film: "You Light Up My Life",
  year: 1978,
  filmYear: 1977,
  songwriters: ["Joseph Brooks"],
  performers: ["Debby Boone"],
  spotify: "3dFR132gzO8jxD57R2gid3",
  wikipedia: "https://en.wikipedia.org/wiki/York_River_%28Ontario%29",
  wikidata: "Q8055530"
},
{
  song: "Last Dance",
  film: "Thank God It's Friday",
  year: 1979,
  filmYear: 1978,
  songwriters: ["Paul Jabara"],
  performers: ["Donna Summer"],
  spotify: "5fKTkCOpnyJko7jZqpbJnX",
  wikipedia: null,
  wikidata: "Q6495758"
},
{
  song: "It Goes Like It Goes",
  film: "Norma Rae",
  year: 1980,
  filmYear: 1979,
  songwriters: ["David Shire", "Norman Gimbel"],
  performers: ["Jennifer Warnes"],
  spotify: "2p26s1c9ARKwSeTrXUGt2O",
  wikipedia: null,
  wikidata: "Q6090029"
},
{
  song: "Fame",
  film: "Fame",
  year: 1981,
  filmYear: 1980,
  songwriters: ["Michael Gore", "Dean Pitchford"],
  performers: ["Irene Cara"],
  spotify: "5CI1FP2Volc9wjz2MBZsGx",
  wikipedia: "https://en.wikipedia.org/wiki/Near-Earth_Asteroid_Tracking",
  wikidata: "Q1140499"
},
{
  song: "Arthur's Theme (Best That You Can Do)",
  film: "Arthur",
  year: 1982,
  filmYear: 1981,
  songwriters: ["Burt Bacharach", "Carole Bayer Sager", "Christopher Cross", "Peter Allen"],
  performers: ["Christopher Cross"],
  spotify: "5fnOrhQ4KgT5irGCjIccGH",
  wikipedia: "https://en.wikipedia.org/wiki/Arthur_James_Mason",
  wikidata: "Q4799230"
},
{
  song: "Up Where We Belong",
  film: "An Officer and a Gentleman",
  year: 1983,
  filmYear: 1982,
  songwriters: ["Jack Nitzsche", "Buffy Sainte-Marie", "Will Jennings"],
  performers: ["Joe Cocker", "Jennifer Warnes"],
  spotify: "4U6mBgGP8FXN6UH4T3AJhu",
  wikipedia: "https://en.wikipedia.org/wiki/Opera_Theatre_of_Saint_Louis",
  wikidata: "Q2497917"
},
{
  song: "Flashdance... What a Feeling",
  film: "Flashdance",
  year: 1984,
  filmYear: 1983,
  songwriters: ["Giorgio Moroder", "Keith Forsey", "Irene Cara"],
  performers: ["Irene Cara"],
  spotify: "3cbV252akVZInSvJk7jAYX",
  wikipedia: null,
  wikidata: "Q1434095"
},
{
  song: "I Just Called to Say I Love You",
  film: "The Woman in Red",
  year: 1985,
  filmYear: 1984,
  songwriters: ["Stevie Wonder"],
  performers: ["Stevie Wonder"],
  spotify: "6RNDeRnWsRMjPdNVgupZCs",
  wikipedia: null,
  wikidata: "Q1323577"
},
{
  song: "Say You, Say Me",
  film: "White Nights",
  year: 1986,
  filmYear: 1985,
  songwriters: ["Lionel Richie"],
  performers: ["Lionel Richie"],
  spotify: "17CPezzLWzvGfpZW6X8XT0",
  wikipedia: null,
  wikidata: "Q2040064"
},
{
  song: "Take My Breath Away",
  film: "Top Gun",
  year: 1987,
  filmYear: 1986,
  songwriters: ["Giorgio Moroder", "Tom Whitlock"],
  performers: ["Berlin"],
  spotify: "15MJ5NThPjj6xhPcts8MiY",
  wikipedia: null,
  wikidata: "Q1073369"
},
{
  song: "(I've Had) The Time of My Life",
  film: "Dirty Dancing",
  year: 1988,
  filmYear: 1987,
  songwriters: ["Franke Previte", "John DeNicola", "Donald Markowitz"],
  performers: ["Bill Medley", "Jennifer Warnes"],
  spotify: "6W7ztLBiRzBN46ZaPAcQ0F",
  wikipedia: "https://en.wikipedia.org/wiki/Gumerovo%2C_Kushnarenkovsky_District%2C_Republic_of_Bashkortostan",
  wikidata: "Q1069831"
},
{
  song: "Let the River Run",
  film: "Working Girl",
  year: 1989,
  filmYear: 1988,
  songwriters: ["Carly Simon"],
  performers: ["Carly Simon"],
  spotify: "6zv8T4vuevldBjH65XjLXH",
  wikipedia: null,
  wikidata: "Q1822527"
},
{
  song: "Under the Sea",
  film: "The Little Mermaid",
  year: 1990,
  filmYear: 1989,
  songwriters: ["Alan Menken", "Howard Ashman"],
  performers: ["Samuel E. Wright"],
  spotify: "4qqfI5oNO53a6W7nWfutKH",
  wikipedia: "https://en.wikipedia.org/wiki/Dino_%28marque%29",
  wikidata: "Q577775"
},
{
  song: "Sooner or Later (I Always Get My Man)",
  film: "Dick Tracy",
  year: 1991,
  filmYear: 1990,
  songwriters: ["Stephen Sondheim"],
  performers: ["Madonna"],
  spotify: "3LTinH60rltyAZiMmHF7JH",
  wikipedia: "https://en.wikipedia.org/wiki/Sofiene_Chaari",
  wikidata: "Q3488863"
},
{
  song: "Beauty and the Beast",
  film: "Beauty and the Beast",
  year: 1992,
  filmYear: 1991,
  songwriters: ["Alan Menken", "Howard Ashman"],
  performers: ["Celine Dion", "Peabo Bryson"],
  spotify: "7B3UAPLYAbwXVgbHSKEaTw",
  wikipedia: null,
  wikidata: "Q2334872"
},
{
  song: "A Whole New World",
  film: "Aladdin",
  year: 1993,
  filmYear: 1992,
  songwriters: ["Alan Menken", "Tim Rice"],
  performers: ["Brad Kane", "Lea Salonga"],
  spotify: "1hwdPQtFHISvZ9SXMkNrIK",
  wikipedia: null,
  wikidata: "Q1855902"
},
{
  song: "Streets of Philadelphia",
  film: "Philadelphia",
  year: 1994,
  filmYear: 1993,
  songwriters: ["Bruce Springsteen"],
  performers: ["Bruce Springsteen"],
  spotify: "3fbnbn6A5O5RNb08tlUEgd",
  wikipedia: "https://en.wikipedia.org/wiki/Olbia_Costa_Smeralda_Airport",
  wikidata: "Q1432236"
},
{
  song: "Can You Feel the Love Tonight",
  film: "The Lion King",
  year: 1995,
  filmYear: 1994,
  songwriters: ["Elton John", "Tim Rice"],
  performers: ["Elton John"],
  spotify: "67HKtdqchK0rmODxsBeWT8",
  wikipedia: "https://en.wikipedia.org/wiki/Gilli_%28Hebridean_earl%29",
  wikidata: "Q1032927"
},
{
  song: "Colors of the Wind",
  film: "Pocahontas",
  year: 1996,
  filmYear: 1995,
  songwriters: ["Alan Menken", "Stephen Schwartz"],
  performers: ["Vanessa Williams"],
  spotify: "7xG1fakElLbxwyr9eyGEK6",
  wikipedia: null,
  wikidata: "Q2993233"
},
{
  song: "You Must Love Me",
  film: "Evita",
  year: 1997,
  filmYear: 1996,
  songwriters: ["Andrew Lloyd Webber", "Tim Rice"],
  performers: ["Madonna"],
  spotify: "78JPL7uIfs6Imm57r1QETk",
  wikipedia: null,
  wikidata: "Q2606093"
},
{
  song: "My Heart Will Go On",
  film: "Titanic",
  year: 1998,
  filmYear: 1997,
  songwriters: ["James Horner", "Will Jennings"],
  performers: ["Celine Dion"],
  spotify: "33LC84JgLvK2KuW43MfaNq",
  wikipedia: "https://en.wikipedia.org/wiki/Jaws_%28film%29",
  wikidata: "Q189505"
},
{
  song: "When You Believe",
  film: "The Prince of Egypt",
  year: 1999,
  filmYear: 1998,
  songwriters: ["Stephen Schwartz"],
  performers: ["Mariah Carey", "Whitney Houston"],
  spotify: "0JN7vUgUolHGHFrOR8xk7S",
  wikipedia: null,
  wikidata: "Q2564289"
},
{
  song: "You'll Be in My Heart",
  film: "Tarzan",
  year: 2000,
  filmYear: 1999,
  songwriters: ["Phil Collins"],
  performers: ["Phil Collins"],
  spotify: "4Y8vb1uy9IjM2V1hqvrAid",
  wikipedia: null,
  wikidata: "Q2606147"
},
{
  song: "Things Have Changed",
  film: "Wonder Boys",
  year: 2001,
  filmYear: 2000,
  songwriters: ["Bob Dylan"],
  performers: ["Bob Dylan"],
  spotify: "5KOi77ameCimkAdw0DMNoy",
  wikipedia: "https://en.wikipedia.org/wiki/ThinkPad_Z60m",
  wikidata: "Q7784455"
},
{
  song: "If I Didn't Have You",
  film: "Monsters, Inc.",
  year: 2002,
  filmYear: 2001,
  songwriters: ["Randy Newman"],
  performers: ["Billy Crystal", "John Goodman"],
  spotify: "7xf3S6Bv8hDqOtevZou602",
  wikipedia: null,
  wikidata: "Q1569714"
},
{
  song: "Lose Yourself",
  film: "8 Mile",
  year: 2003,
  filmYear: 2002,
  songwriters: ["Eminem", "Jeff Bass", "Luis Resto"],
  performers: ["Eminem"],
  spotify: "5Z01UMMf7V1o0MzF86s6WJ",
  wikipedia: null,
  wikidata: "Q483882"
},
{
  song: "Into the West",
  film: "The Lord of the Rings: The Return of the King",
  year: 2004,
  filmYear: 2003,
  songwriters: ["Annie Lennox", "Fran Walsh", "Howard Shore"],
  performers: ["Annie Lennox"],
  spotify: "0gSEyG7pOFuHM05433EibX",
  wikipedia: "https://en.wikipedia.org/wiki/Pocket_Money",
  wikidata: "Q945735"
},
{
  song: "Al otro lado del río",
  film: "The Motorcycle Diaries",
  year: 2005,
  filmYear: 2004,
  songwriters: ["Jorge Drexler"],
  performers: ["Jorge Drexler"],
  spotify: "5BudpQ0Ct9sss8c9Fqv9MJ",
  wikipedia: "https://en.wikipedia.org/wiki/Runcinia_depressa",
  wikidata: "Q2831625"
},
{
  song: "It's Hard Out Here for a Pimp",
  film: "Hustle & Flow",
  year: 2006,
  filmYear: 2005,
  songwriters: ["Jordan Houston", "Cedric Coleman", "Paul Beauregard"],
  performers: ["Three 6 Mafia"],
  spotify: "17ZCxegdCt1y0reBkHVmMB",
  wikipedia: null,
  wikidata: "Q1546927"
},
{
  song: "I Need to Wake Up",
  film: "An Inconvenient Truth",
  year: 2007,
  filmYear: 2006,
  songwriters: ["Melissa Etheridge"],
  performers: ["Melissa Etheridge"],
  spotify: "7mOfeDExZHCImmcmGYrv3T",
  wikipedia: "https://en.wikipedia.org/wiki/Isabella_Grimaldi",
  wikidata: "Q6078012"
},
{
  song: "Falling Slowly",
  film: "Once",
  year: 2008,
  filmYear: 2007,
  songwriters: ["Glen Hansard", "Markéta Irglová"],
  performers: ["Glen Hansard", "Markéta Irglová"],
  spotify: "6EIVLz5xM1xE29r0OmIkWt",
  wikipedia: "https://en.wikipedia.org/wiki/Paul_Haines_%28poet%29",
  wikidata: "Q1396268"
},
{
  song: "Jai Ho",
  film: "Slumdog Millionaire",
  year: 2009,
  filmYear: 2008,
  songwriters: ["A. R. Rahman", "Gulzar"],
  performers: ["Sukhwinder Singh", "Tanvi Shah", "Mahalaxmi Iyer", "Vijay Prakash"],
  spotify: "0BlMvHfyilCmgKrNUQabR6",
  wikipedia: "https://en.wikipedia.org/wiki/Federico_Ruiz_%28composer%29",
  wikidata: "Q1396254"
},
{
  song: "The Weary Kind",
  film: "Crazy Heart",
  year: 2010,
  filmYear: 2009,
  songwriters: ["Ryan Bingham", "T Bone Burnett"],
  performers: ["Ryan Bingham"],
  spotify: "5uqQQtXsY2HJLbPVPwcz6C",
  wikipedia: null,
  wikidata: "Q3524015"
},
{
  song: "We Belong Together",
  film: "Toy Story 3",
  year: 2011,
  filmYear: 2010,
  songwriters: ["Randy Newman"],
  performers: ["Randy Newman"],
  spotify: "2m1mYan1nvOMORlb12q2Y9",
  wikipedia: null,
  wikidata: "Q1552850"
},
{
  song: "Man or Muppet",
  film: "The Muppets",
  year: 2012,
  filmYear: 2011,
  songwriters: ["Bret McKenzie"],
  performers: ["Jason Segel", "Walter"],
  spotify: "1JyG5yuwpN0VIi4wbqvDfB",
  wikipedia: null,
  wikidata: "Q1621399"
},
{
  song: "Skyfall",
  film: "Skyfall",
  year: 2013,
  filmYear: 2012,
  songwriters: ["Adele", "Paul Epworth"],
  performers: ["Adele"],
  spotify: "6VObnIkLVruX4UVyxWhlqm",
  wikipedia: "https://en.wikipedia.org/wiki/Corn%C3%A9lie_Wouters_de_Vass%C3%A9",
  wikidata: "Q2997612"
},
{
  song: "Let It Go",
  film: "Frozen",
  year: 2014,
  filmYear: 2013,
  songwriters: ["Kristen Anderson-Lopez", "Robert Lopez"],
  performers: ["Idina Menzel"],
  spotify: "0qcr5FMsEO85NAQjrlDRKo",
  wikipedia: null,
  wikidata: "Q15055360"
},
{
  song: "Glory",
  film: "Selma",
  year: 2015,
  filmYear: 2014,
  songwriters: ["Common", "John Legend", "Che Smith"],
  performers: ["Common", "John Legend"],
  spotify: "6AXIgQRvorhGyeBM0Jby9E",
  wikipedia: "https://en.wikipedia.org/wiki/Poker_Night_%28film%29",
  wikidata: "Q18703030"
},
{
  song: "Writing's on the Wall",
  film: "Spectre",
  year: 2016,
  filmYear: 2015,
  songwriters: ["Sam Smith", "Jimmy Napes"],
  performers: ["Sam Smith"],
  spotify: "1PWnAEQcbwQwK759otUbta",
  wikipedia: null,
  wikidata: "Q20899840"
},
{
  song: "City of Stars",
  film: "La La Land",
  year: 2017,
  filmYear: 2016,
  songwriters: ["Justin Hurwitz", "Benj Pasek", "Justin Paul"],
  performers: ["Ryan Gosling", "Emma Stone"],
  spotify: "6XQHlsNu6so4PdglFkJQRJ",
  wikipedia: null,
  wikidata: "Q27888326"
},
{
  song: "Remember Me",
  film: "Coco",
  year: 2018,
  filmYear: 2017,
  songwriters: ["Kristen Anderson-Lopez", "Robert Lopez"],
  performers: ["Anthony Gonzalez"],
  spotify: "3uCcoxif1cNSDivDOsi69C",
  wikipedia: null,
  wikidata: "Q37107779"
},
{
  song: "Shallow",
  film: "A Star Is Born",
  year: 2019,
  filmYear: 2018,
  songwriters: ["Lady Gaga", "Mark Ronson", "Anthony Rossomando", "Andrew Wyatt"],
  performers: ["Lady Gaga", "Bradley Cooper"],
  spotify: "2VxeLyX666F8uXCJ0dZF8B",
  wikipedia: null,
  wikidata: "Q56556519"
},
{
  song: "(I'm Gonna) Love Me Again",
  film: "Rocketman",
  year: 2020,
  filmYear: 2019,
  songwriters: ["Elton John", "Bernie Taupin"],
  performers: ["Elton John"],
  spotify: "1q8lLOgfciaGLwXCvOpH6w",
  wikipedia: null,
  wikidata: "Q65081885"
},
{
  song: "Fight for You",
  film: "Judas and the Black Messiah",
  year: 2021,
  filmYear: 2021,
  songwriters: ["H.E.R.", "Dernst Emile II", "Tiara Thomas"],
  performers: ["H.E.R."],
  spotify: "2UJsKjM595pEyWUcd8JEIR",
  wikipedia: null,
  wikidata: "Q104925291"
},
{
  song: "No Time to Die",
  film: "No Time to Die",
  year: 2022,
  filmYear: 2021,
  songwriters: ["Billie Eilish", "Finneas O'Connell"],
  performers: ["Billie Eilish"],
  spotify: "73SpzrcaHk0RQPFP73vqVR",
  wikipedia: null,
  wikidata: "Q87416078"
},
{
  song: "Naatu Naatu",
  film: "RRR",
  year: 2023,
  filmYear: 2022,
  songwriters: ["M. M. Keeravani", "Chandrabose"],
  performers: ["Rahul Sipligunj", "Kaala Bhairava"],
  spotify: "4iKGu3xtvm90eBw0EIPWJP",
  wikipedia: null,
  wikidata: "Q109936888"
},
{
  song: "What Was I Made For?",
  film: "Barbie",
  year: 2024,
  filmYear: 2023,
  songwriters: ["Billie Eilish", "Finneas O'Connell"],
  performers: ["Billie Eilish"],
  spotify: "6wf7Yu7cxBSPrRlWeSeK0Q",
  wikipedia: null,
  wikidata: "Q117155553"
},
{
  song: "El Mal",
  film: "Emilia Pérez",
  year: 2025,
  filmYear: 2024,
  songwriters: ["Camille", "Clément Ducol"],
  performers: ["Zoe Saldaña"],
  spotify: "0mKR0vmt8jj6Z3mWpxITF1",
  wikipedia: null,
  wikidata: "Q131576779"
}
];
