window.SONGS_DATA = [
{
  song: "The Continental",
  film: "The Gay Divorcee",
  year: 1935,
  filmYear: 1934,
  songwriters: ["Con Conrad","Herb Magidson"],
  performers: ["Ginger Rogers"],
  spotify: "67aSleHfmiBhT1x9MtDbOf",
  wikipedia: "https://en.wikipedia.org/wiki/The_Continental_(song)",
  wikidata: "Q7730754",
  summary: "\"The Continental\" is a dance to a song written by Con Conrad with lyrics by Herb Magidson, and was introduced by Ginger Rogers and Fred Astaire in the 1934 film The Gay Divorcee. \"The Continental\" was the first song to win the Academy Award for Best Original Song. In the film it was sung by Ginger Rogers, Erik Rhodes and Lillian Miles.",
  filmDirector: "Mark Sandrich",
  filmSummary: "Seeking a divorce from her absentee husband, Mimi Glossop travels to an English seaside resort. There she falls in love with dancer Guy Holden, whom she later mistakes for the corespondent her lawyer hired.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Gay_Divorcee"
},
{
  song: "Lullaby of Broadway",
  film: "Gold Diggers of 1935",
  year: 1936,
  filmYear: 1935,
  songwriters: ["Harry Warren","Al Dubin"],
  performers: ["Wini Shaw"],
  spotify: "7tC6UY03PQQUzOjWAbdZmZ",
  wikipedia: "https://en.wikipedia.org/wiki/Lullaby_of_Broadway_(song)",
  wikidata: "Q1872255",
  summary: "\"Lullaby of Broadway\" is a popular song with music written by Harry Warren and lyrics by Al Dubin, published in 1935. The lyrics salute the nightlife of Broadway and its denizens, who \"don't sleep tight until the dawn.\" The song was introduced by Wini Shaw in the musical film Gold Diggers of 1935, and, in an unusual move, it was used as background music in a sequence in the Bette Davis film Special Agent that same year.",
  filmDirector: "Busby Berkeley",
  filmSummary: "Romance strikes when a vacationing millionairess and her daughter and son spend their vacation at a posh New England resort.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Gold_Diggers_of_1935"
},
{
  song: "The Way You Look Tonight",
  film: "Swing Time",
  year: 1937,
  filmYear: 1936,
  songwriters: ["Jerome Kern","Dorothy Fields"],
  performers: ["Fred Astaire"],
  spotify: "6ALpCzjVWFQJRwKIM8he8F",
  wikipedia: "https://en.wikipedia.org/wiki/The_Way_You_Look_Tonight",
  wikidata: "Q1066282",
  summary: "\"The Way You Look To-night\" is a song from the film Swing Time that was performed by Fred Astaire and composed by Jerome Kern with lyrics written by Dorothy Fields. It won the Academy Award for Best Original Song in 1936. Fields remarked, \"The first time Jerry played that melody for me I went out and started to cry. The release absolutely killed me. I couldn't stop, it was so beautiful.\" In the movie, Astaire sang \"The Way You Look To-night\" to Ginger Rogers while she was washing her hair in an...",
  filmDirector: "George Stevens",
  filmSummary: "Lucky is tricked into missing his own wedding to Margaret and has to make $25,000 so her father will allow him to marry her. He and business partner Pop go to New York where they run into dancing instructor Penny.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Swing_Time_(film)"
},
{
  song: "Sweet Leilani",
  film: "Waikiki Wedding",
  year: 1938,
  filmYear: 1937,
  songwriters: ["Harry Owens"],
  performers: ["Bing Crosby"],
  spotify: "1HOtHVowS8frSOJvZoqOJ9",
  wikipedia: "https://en.wikipedia.org/wiki/Sweet_Leilani",
  wikidata: "Q7654271",
  summary: "\"Sweet Leilani\" is a song featured in the 1937 film, Waikiki Wedding. It won the Academy Award for Best Original Song, and Bing Crosby's record became one of the biggest hits of 1937. Harry Owens wrote the song on October 20, 1934 for his daughter Leilani, who was born the previous day. Leilani is a popular Hawaiian name, meaning \"heavenly garland of flowers\" (not \"heavenly flower\").",
  filmDirector: "Frank Tuttle",
  filmSummary: "Tony Marvin is a laid back but incredibly successful promoter and fair-haired boy for J. P. Todhunter's pineapple company located in beautiful Hawaii. He gets the company to sponsor a contest in which the winner gets a Hawaiian vacation and is obligated to write articles on the islands which, when...",
  filmWikipedia: "https://en.wikipedia.org/wiki/Waikiki_Wedding"
},
{
  song: "Thanks for the Memory",
  film: "The Big Broadcast of 1938",
  year: 1939,
  filmYear: 1938,
  songwriters: ["Ralph Rainger","Leo Robin"],
  performers: ["Bob Hope","Shirley Ross"],
  spotify: "1qVwptCd8xqwr2zzO1djvi",
  wikipedia: "https://en.wikipedia.org/wiki/Thanks_for_the_Memory",
  wikidata: "Q2399832",
  summary: "\"Thanks for the Memory\" (1938) is a popular song composed by Ralph Rainger with lyrics by Leo Robin. It was introduced in the 1938 film The Big Broadcast of 1938 by Bob Hope and Shirley Ross, and recorded by Shep Fields and His Orchestra featuring John Serry Sr. on accordion in the film and vocals by Bob Goday on Bluebird Records (B-7318, 1937). Dorothy Lamour's solo recording of the song was also popular, and has led to many mistakenly believing over the years that it was she who sang the tune...",
  filmDirector: "Mitchell Leisen",
  filmSummary: "The Bellows family causes comic confusion on an ocean liner, with time out for radio-style musical acts.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Big_Broadcast_of_1938"
},
{
  song: "Over the Rainbow",
  film: "The Wizard of Oz",
  year: 1940,
  filmYear: 1939,
  songwriters: ["Harold Arlen","Yip Harburg"],
  performers: ["Judy Garland"],
  spotify: "1p7C97Xibwh0jL85jhdOZv",
  wikipedia: "https://en.wikipedia.org/wiki/Over_the_Rainbow",
  wikidata: "Q209346",
  summary: "\"Over the Rainbow\", also known as \"Somewhere Over the Rainbow\", is a ballad by Harold Arlen with lyrics by Yip Harburg. It was written for the 1939 film The Wizard of Oz, in which it was sung by actress Judy Garland in her starring role as Dorothy Gale. About five minutes into the film, Dorothy sings the song after failing to get Aunt Em, Uncle Henry, and the farmhands to listen to her story of an unpleasant incident involving her dog, Toto, and the town spinster, Miss Gulch (Margaret...",
  filmDirector: "Victor Fleming",
  filmSummary: "Young Dorothy finds herself in a magical world where she makes friends with a lion, a scarecrow and a tin man as they make their way along the yellow brick road to talk with the Wizard and ask for the things they miss most in their lives.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Wizard_of_Oz"
},
{
  song: "When You Wish Upon a Star",
  film: "Pinocchio",
  year: 1941,
  filmYear: 1940,
  songwriters: ["Leigh Harline","Ned Washington"],
  performers: ["Cliff Edwards"],
  spotify: "1WrPa4lrIddctGWAIYYfP9",
  wikipedia: "https://en.wikipedia.org/wiki/When_You_Wish_Upon_a_Star",
  wikidata: "Q1140279",
  summary: "\"When You Wish Upon a Star\" is a song written by Leigh Harline and Ned Washington for the 1940 Disney animated film Pinocchio, based on the children's fairy tale novel The Adventures of Pinocchio by Italian author Carlo Collodi. The original version was sung by Cliff Edwards in the character of Jiminy Cricket, and is heard over the opening credits and in the final scene of the film.",
  filmDirector: "Hamilton Luske, Ben Sharpsteen, T. Hee, Wilfred Jackson, Norman Ferguson, Jack Kinney, Bill Roberts",
  filmSummary: "When the gentle woodcarver Geppetto builds a marionette to be his substitute son, a benevolent fairy brings the toy to life. The puppet, named Pinocchio, is not yet a human boy. He must earn the right to be real by proving that he is brave, truthful, and unselfish.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Pinocchio"
},
{
  song: "The Last Time I Saw Paris",
  film: "Lady Be Good",
  year: 1942,
  filmYear: 1941,
  songwriters: ["Jerome Kern","Oscar Hammerstein II"],
  performers: ["Ann Sothern"],
  spotify: "0DapUVR8Vgw7b6NQbw1jxr",
  wikipedia: "https://en.wikipedia.org/wiki/The_Last_Time_I_Saw_Paris_(song)",
  wikidata: "Q6503576",
  summary: "\"The Last Time I Saw Paris\" is a song composed by Jerome Kern, with lyrics by Oscar Hammerstein II, published in 1940. It was sung in the 1941 film Lady Be Good by Ann Sothern. By December 1940, six versions of the song were on the charts, with Kate Smith having exclusive radio rights for the song for six weeks. The song catered to a wartime nostalgia for songs about European cities following the Second World War Battle of France (which brought Paris under Nazi control), with \"A Nightingale...",
  filmDirector: "Norman Z. McLeod, Busby Berkeley",
  filmSummary: "Married songwriters almost split up while putting on a big show.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Lady_Be_Good"
},
{
  song: "White Christmas",
  film: "Holiday Inn",
  year: 1943,
  filmYear: 1942,
  songwriters: ["Irving Berlin"],
  performers: ["Bing Crosby"],
  spotify: "7134tEHq45eL6am9oVazZU",
  wikipedia: "https://en.wikipedia.org/wiki/White_Christmas_(song)",
  wikidata: "Q207927",
  summary: "\"White Christmas\" is a song reminiscing about an old-fashioned Christmas setting. Written by Irving Berlin for the 1942 musical film Holiday Inn, the song won the Academy Award for Best Original Song at the 15th Academy Awards. Introduced by Bing Crosby, it topped the Billboard chart for 11 weeks and returned to the number one position again in December 1943 and 1944. His version would return to the top 40 a dozen times in subsequent years, the most recent being 2025.",
  filmDirector: "Mark Sandrich",
  filmSummary: "Lovely Linda Mason has crooner Jim Hardy head over heels, but suave stepper Ted Hanover wants her for his new dance partner after fickle Lila Dixon gives him the brush. Jim's supper club, Holiday Inn, is the setting for the chase by Hanover and his manager.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Holiday_Inn_(film)"
},
{
  song: "You'll Never Know",
  film: "Hello, Frisco, Hello",
  year: 1944,
  filmYear: 1943,
  songwriters: ["Harry Warren","Mack Gordon"],
  performers: ["Alice Faye"],
  spotify: "06UY42Kc7qFYw9TT4gr5Kz",
  wikipedia: "https://en.wikipedia.org/wiki/You%27ll_Never_Know",
  wikidata: "Q8055759",
  summary: "\"You'll Never Know\", sometimes referred to as \"You'll Never Know (Just How Much I Love You)\" in later years, is a popular song with music written by Harry Warren and the lyrics by Mack Gordon. The song is based on a poem written by a young Oklahoma war bride named Dorothy Fern Norris. The song was introduced in the 1943 movie Hello, Frisco, Hello where it was sung by Alice Faye. The song won the 1943 Academy Award for Best Original Song, one of nine nominated songs that year.",
  filmDirector: "H. Bruce Humberstone",
  filmSummary: "In turn-of-the-century San Francisco, an ambitious vaudevillian takes his quartet from a honky tonk to the big time, while spurning the love of his troupe's star singer for a selfish heiress.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Hello%2C_Frisco%2C_Hello"
},
{
  song: "Swinging on a Star",
  film: "Going My Way",
  year: 1945,
  filmYear: 1944,
  songwriters: ["Jimmy Van Heusen","Johnny Burke"],
  performers: ["Bing Crosby"],
  spotify: "7xy0PAZxzGDOcYzyptvprd",
  wikipedia: "https://en.wikipedia.org/wiki/Swinging_on_a_Star",
  wikidata: "Q3511236",
  summary: "\"Swinging on a Star\" is an American pop standard with music composed by Jimmy Van Heusen and lyrics by Johnny Burke. It was introduced by Bing Crosby in the 1944 film Going My Way, winning an Academy Award for Best Original Song that year, and has been recorded by numerous artists since then. In 2004, it finished at No. 37 in AFI's 100 Years...100 Songs survey of top tunes in American cinema. Many artists have recorded it under the title \"Would You Like to Swing on a Star\".",
  filmDirector: "Leo McCarey",
  filmSummary: "Youthful Father Chuck O'Malley led a colorful life of sports, song, and romance before joining the Roman Catholic clergy. After being appointed to a run-down New York parish, O'Malley's worldly knowledge helps him connect with a gang of boys looking for direction, eventually winning over the aging...",
  filmWikipedia: "https://en.wikipedia.org/wiki/Going_My_Way"
},
{
  song: "It Might as Well Be Spring",
  film: "State Fair",
  year: 1946,
  filmYear: 1945,
  songwriters: ["Richard Rodgers","Oscar Hammerstein II"],
  performers: ["Louanne Hogan"],
  spotify: "2T9TnBcmbEQPC9NUBYBgMI",
  wikipedia: "https://en.wikipedia.org/wiki/It_Might_as_Well_Be_Spring",
  wikidata: "Q6090099",
  summary: "\"It Might as Well Be Spring\" is a song from the 1945 film State Fair, which features the only original film score by the songwriting team of Richard Rodgers and Oscar Hammerstein II. \"It Might as Well Be Spring\" won the Academy Award for Best Original Song for that year.",
  filmDirector: "Walter Lang",
  filmSummary: "During their annual visit to the Iowa State Fair, the Frake family enjoy many adventures. Proud patriarch Abel has high hopes for his champion swine Blueboy; and his wife Melissa enters the mincemeat and pickles contest...with hilarious results.",
  filmWikipedia: "https://en.wikipedia.org/wiki/State_Fair"
},
{
  song: "On the Atchison, Topeka and the Santa Fe",
  film: "The Harvey Girls",
  year: 1947,
  filmYear: 1946,
  songwriters: ["Harry Warren","Johnny Mercer"],
  performers: ["Judy Garland"],
  spotify: "2LWVbs3KBWiG80qxM2oa64",
  wikipedia: "https://en.wikipedia.org/wiki/On_the_Atchison,_Topeka_and_the_Santa_Fe",
  wikidata: "Q7090254",
  summary: "\"On the Atchison, Topeka and the Santa Fe\" is a pop song written by Harry Warren with lyrics by Johnny Mercer. The song was published in 1944, spanned the hit chart in mid-1945, and won the 1946 Academy Award for Best Original Song, the first win for Mercer. The song refers to the famous eponymous fallen flag railroad, and was featured in the 1946 Western film, The Harvey Girls (about the famous 19th century nation-wide railroad lines of chain restaurants of Harvey Houses, established by...",
  filmDirector: "George Sidney",
  filmSummary: "On a train trip out west to become a mail-order bride, Susan Bradley meets a cheery crew of young women traveling out to open a \"Harvey House\" restaurant at a remote whistle-stop.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Harvey_Girls"
},
{
  song: "Zip-a-Dee-Doo-Dah",
  film: "Song of the South",
  year: 1948,
  filmYear: 1946,
  songwriters: ["Allie Wrubel","Ray Gilbert"],
  performers: ["James Baskett"],
  spotify: "1fQ2pN9MLxxi399nlHEth7",
  wikipedia: "https://en.wikipedia.org/wiki/Zip-a-Dee-Doo-Dah",
  wikidata: "Q2002948",
  summary: "\"Zip-a-Dee-Doo-Dah\" is a song composed by Allie Wrubel with lyrics by Ray Gilbert for Disney's 1946 live action and animated movie Song of the South, sung by James Baskett. \"Zip-a-Dee-Doo-Dah\" won the Academy Award for Best Original Song and was the second Disney song to win this award, after \"When You Wish upon a Star\" from Pinocchio (1940). In 2004, it finished at number 47 in AFI's 100 Years...100 Songs, a survey of top tunes in American cinema.",
  filmDirector: "Harve Foster, Wilfred Jackson",
  filmSummary: "Uncle Remus draws upon his tales of Br'er Rabbit to help little Johnny deal with his confusion over his parents' separation as well as his new life on the plantation.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Song_of_the_South"
},
{
  song: "Buttons and Bows",
  film: "The Paleface",
  year: 1949,
  filmYear: 1948,
  songwriters: ["Jay Livingston","Ray Evans"],
  performers: ["Bob Hope"],
  spotify: "4WhRgJ2UPL1GO2bOlFnnHD",
  wikipedia: "https://en.wikipedia.org/wiki/Buttons_and_Bows",
  wikidata: "Q4001968",
  summary: "\"Buttons and Bows\" is a popular song with music written by Jay Livingston and lyrics by Ray Evans. The song was published on February 25, 1948 (1948-02-25) by Famous Music Corp., New York. The song was written for and appeared in the Bob Hope and Jane Russell film The Paleface and won the Academy Award for Best Original Song. It was originally written with a Native American theme, but was changed when the director said that would not work in the movie.",
  filmDirector: "Norman Z. McLeod",
  filmSummary: "Bob Hope stars in this laugh-packed wild west spoof co-starring Jane Russell as a sexy Calamity Jane, Hope is a meek frontier dentist, \"Painless\" Peter Potter, who finds himself gunslinging alongside the fearless Calamity as she fights off outlaws and Indians.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Paleface"
},
{
  song: "Baby, It's Cold Outside",
  film: "Neptune's Daughter",
  year: 1950,
  filmYear: 1949,
  songwriters: ["Frank Loesser"],
  performers: ["Esther Williams","Ricardo Montalban"],
  spotify: "1K6EMJhvDVkiwweBH886bo",
  wikipedia: "https://en.wikipedia.org/wiki/Baby%2C_It%27s_Cold_Outside",
  wikidata: "Q2878523",
  summary: "\"Baby, It's Cold Outside\" is a popular song written by Frank Loesser in 1944 and popularized in the 1949 film Neptune's Daughter. While the lyrics make no mention of a holiday, it is commonly regarded as a Christmas song owing to its winter theme.  The song was released in eight recordings in 1949—including well-known versions by Ella Fitzgerald and Louis Jordan, Hot Lips Page and Pearl Bailey, and Dean Martin and Marilyn Maxwell—and has been covered hundreds of times since.",
  filmDirector: "Edward Buzzell",
  filmSummary: "Scatterbrained Betty Barrett mistakes masseur Jack Spratt for Jose O'Rourke, the captain of the South American polo team. Spratt goes along with the charade, but the situation becomes more complicated when they fall in love.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Neptune%27s_Daughter"
},
{
  song: "Mona Lisa",
  film: "Captain Carey, U.S.A.",
  year: 1951,
  filmYear: 1950,
  songwriters: ["Jay Livingston","Ray Evans"],
  performers: ["Nat King Cole"],
  spotify: "5dae01pKNjRQtgOeAkFzPY",
  wikipedia: "https://en.wikipedia.org/wiki/Mona_Lisa_%28Nat_King_Cole_song%29",
  wikidata: "Q1948042",
  summary: "\"Mona Lisa\" is a popular song written by Ray Evans and Jay Livingston for the Paramount Pictures film Captain Carey, U.S.A. (1949), in which it was performed by Sergio de Karlo and a recurrent accordion motif. \nThe title and lyrics refer to the renaissance portrait Mona Lisa painted by Leonardo da Vinci.\nThe song won the Academy Award for Best Original Song in 1950.",
  filmDirector: "Mitchell Leisen",
  filmSummary: "Near the end of World War II, a secret American raid on an enemy transportation hub goes very wrong when a turncoat warns the enemy. Led by Capt. Webster Carey, the mission causes the deaths of many bystanders -- among them, Carey believes, his Italian girlfriend, Giulia de Graffi.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Captain_Carey,_U.S.A."
},
{
  song: "In the Cool, Cool, Cool of the Evening",
  film: "Here Comes the Groom",
  year: 1952,
  filmYear: 1951,
  songwriters: ["Hoagy Carmichael","Johnny Mercer"],
  performers: ["Bing Crosby","Jane Wyman"],
  spotify: "0ebXSj5HKwZ9gH78O2xjYR",
  wikipedia: "https://en.wikipedia.org/wiki/In_the_Cool,_Cool,_Cool_of_the_Evening",
  wikidata: "Q6016908",
  summary: "\"In the Cool, Cool, Cool of the Evening\" is a popular song with music by Hoagy Carmichael, and lyrics by Johnny Mercer. It was originally planned to feature it in a Paramount Pictures film written for Betty Hutton, that never took off, which was to be called The Mack Sennett Girl, or Keystone Girl. The song was buried in Paramount's files until it was rediscovered and then used in the 1951 film Here Comes the Groom and won the Academy Award for Best Original Song.",
  filmDirector: "Frank Capra",
  filmSummary: "Foreign correspondent Pete Garvey has 5 days to win back his former fiancée, or he'll lose the orphans he adopted.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Here_Comes_the_Groom"
},
{
  song: "High Noon (Do Not Forsake Me, Oh My Darlin')",
  film: "High Noon",
  year: 1953,
  filmYear: 1952,
  songwriters: ["Dimitri Tiomkin","Ned Washington"],
  performers: ["Tex Ritter"],
  spotify: "3brwF7h3utczuzDWaDVviL",
  wikipedia: "https://en.wikipedia.org/wiki/The_Ballad_of_High_Noon",
  wikidata: "Q1618096",
  summary: "\"The Ballad of High Noon\" (also known simply as \"High Noon\", or by its opening lyric and better known title, \"Do Not Forsake Me, Oh My Darlin'\") is a popular song published in 1952, with music by Dimitri Tiomkin and lyrics by Ned Washington. It is the theme song of the 1952 multiple Academy Award-winning movie High Noon (and titled onscreen as such in the film's opening credits as sung by popular country music singer and actor Tex Ritter), with its tune repeated throughout the film.",
  filmDirector: "Fred Zinnemann",
  filmSummary: "Will Kane, the sheriff of a small town in New Mexico, learns a notorious outlaw he put in jail has been freed, and will be arriving on the noon train. Knowing the outlaw and his gang are coming to kill him, Kane is determined to stand his ground, so he attempts to gather a posse from among the...",
  filmWikipedia: "https://en.wikipedia.org/wiki/High_Noon"
},
{
  song: "Secret Love",
  film: "Calamity Jane",
  year: 1954,
  filmYear: 1953,
  songwriters: ["Sammy Fain","Paul Francis Webster"],
  performers: ["Doris Day"],
  spotify: "5wzjc23Qsn7wN75eLMvFEc",
  wikipedia: "https://en.wikipedia.org/wiki/Secret_Love_%28Doris_Day_song%29",
  wikidata: "Q3476195",
  summary: "\"Secret Love\" is a song composed by Sammy Fain (music) and Paul Francis Webster (lyrics) for Calamity Jane, a 1953 musical film in which it was introduced by Doris Day in the title role. Ranked as a number 1 hit for Day on both the Billboard and Cash Box, the song also afforded Day a number 1 hit in the UK.  \"Secret Love\" has subsequently been recorded by a wide range of artists, becoming a C&W hit firstly for Slim Whitman and later for Freddy Fender, with the song also becoming an R&B hit for...",
  filmDirector: "David Butler",
  filmSummary: "Sharpshooter Calamity Jane takes it upon herself to recruit a famous actress and bring her back to the local saloon, but jealousy soon gets in the way.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Calamity_Jane"
},
{
  song: "Three Coins in the Fountain",
  film: "Three Coins in the Fountain",
  year: 1955,
  filmYear: 1954,
  songwriters: ["Jule Styne","Sammy Cahn"],
  performers: ["Frank Sinatra"],
  spotify: "2LnTydfDh8VOvJH7cSLqjS",
  wikipedia: "https://en.wikipedia.org/wiki/Three_Coins_in_the_Fountain_(song)",
  wikidata: "Q2329994",
  summary: "\"Three Coins in the Fountain\" is a popular song which received the Academy Award for Best Original Song in 1955. The song was first recorded by Frank Sinatra in 1954.",
  filmDirector: "Jean Negulesco",
  filmSummary: "Three American roommates working in Italy wish for the man of their dreams after throwing coins into Rome's magnificent Trevi Fountain. Frances, a secretary at a government agency, sets out to win the heart of her smooth-talking novelist employer; Anita, her coworker, defies office regulations by...",
  filmWikipedia: "https://en.wikipedia.org/wiki/Three_Coins_in_the_Fountain_(film)"
},
{
  song: "Love Is a Many-Splendored Thing",
  film: "Love Is a Many-Splendored Thing",
  year: 1956,
  filmYear: 1955,
  songwriters: ["Sammy Fain","Paul Francis Webster"],
  performers: ["The Four Aces"],
  spotify: "5koEBSDfDV8MQVN0tg67z5",
  wikipedia: "https://en.wikipedia.org/wiki/Love_Is_a_Many-Splendored_Thing_(song)",
  wikidata: "Q6538757",
  summary: "\"Love Is a Many-Splendored Thing\" is a popular song with music by Sammy Fain and lyrics by Paul Francis Webster. The song appeared first in the movie Love Is a Many-Splendored Thing (1955), and it won the Academy Award for Best Original Song in 1956. From 1967 to 1973, it was also used as the theme song to Love is a Many Splendored Thing, the soap opera based on the movie. Many versions of the song have been released.",
  filmDirector: "Henry King",
  filmSummary: "A widowed doctor of both Chinese and European descent falls in love with a married American correspondent in Hong Kong during China's Communist revolution.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Love_Is_a_Many-Splendored_Thing"
},
{
  song: "Whatever Will Be, Will Be (Que Sera, Sera)",
  film: "The Man Who Knew Too Much",
  year: 1957,
  filmYear: 1956,
  songwriters: ["Jay Livingston","Ray Evans"],
  performers: ["Doris Day"],
  spotify: "6yhLR2sVn1IfsScVrR4ocr",
  wikipedia: "https://en.wikipedia.org/wiki/Que_Sera,_Sera_(Whatever_Will_Be,_Will_Be)",
  wikidata: "Q913373",
  summary: "\"Qué Será, Será (Whatever Will Be, Will Be)\" is a song written by Jay Livingston and Ray Evans and first published in 1955. Doris Day introduced it in the Alfred Hitchcock film The Man Who Knew Too Much (1956), singing it as a cue to their onscreen kidnapped son. The three verses of the song progress through the life of the narrator—from childhood, through young adulthood and falling in love, to parenthood—and each asks \"What will I be?\" or \"What lies ahead?\" The chorus repeats the answer...",
  filmDirector: "Alfred Hitchcock",
  filmSummary: "An American doctor and his wife, a former singing star, witness a murder while vacationing in Morocco, and are drawn into a twisting plot of international intrigue when their young son is kidnapped.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Man_Who_Knew_Too_Much"
},
{
  song: "All the Way",
  film: "The Joker Is Wild",
  year: 1958,
  filmYear: 1957,
  songwriters: ["Jimmy Van Heusen","Sammy Cahn"],
  performers: ["Frank Sinatra"],
  spotify: "1ktkBoXdDHD2N856EVKKTp",
  wikipedia: "https://en.wikipedia.org/wiki/All_the_Way_%28Frank_Sinatra_song%29",
  wikidata: "Q4726268",
  summary: "\"All the Way\" is a song published in 1957 by Maraville Music Corporation. The music was written by Jimmy Van Heusen with lyrics by Sammy Cahn.",
  filmDirector: "Charles Vidor",
  filmSummary: "A Prohibition-era nightclub crooner has his career is cut short when his throat is slashed by a mob boss.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Joker_Is_Wild"
},
{
  song: "Gigi",
  film: "Gigi",
  year: 1959,
  filmYear: 1958,
  songwriters: ["Frederick Loewe","Alan Jay Lerner"],
  performers: ["Louis Jourdan"],
  spotify: "6j7o72c7jVIlvJOW6PgWeT",
  wikipedia: "https://en.wikipedia.org/wiki/Gigi_(song)",
  wikidata: "Q1524823",
  summary: "\"Gigi\" is the title song from the 1958 Academy Award–winning film, directed by Vincente Minnelli. It was written by Frederick Loewe (music) and Alan Jay Lerner (words), sung by Louis Jourdan in the film. It then went on to win the Academy Award for Best Original Song in 1958.",
  filmDirector: "Vincente Minnelli",
  filmSummary: "A home, a motorcar, servants, the latest fashions: the most eligible and most finicky bachelor in Paris offers them all to Gigi. But she, who's gone from girlish gawkishness to cultured glamour before our eyes, yearns for that wonderful something money can't buy.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Gigi"
},
{
  song: "High Hopes",
  film: "A Hole in the Head",
  year: 1960,
  filmYear: 1959,
  songwriters: ["Jimmy Van Heusen","Sammy Cahn"],
  performers: ["Frank Sinatra"],
  spotify: "68sTztCNUapkQL0nEKfrM5",
  wikipedia: "https://en.wikipedia.org/wiki/High_Hopes_(Frank_Sinatra_song)",
  wikidata: "Q3785174",
  summary: "\"High Hopes\" is a popular song first popularized by Frank Sinatra, with music written by James Van Heusen and lyrics by Sammy Cahn. It was introduced by Sinatra and child actor Eddie Hodges in the 1959 film A Hole in the Head, was nominated for a Grammy, and won an Oscar for Best Original Song at the 32nd Academy Awards.",
  filmDirector: "Frank Capra",
  filmSummary: "An impractical widower tries to hang onto his Miami hotel and his 12-year-old son.",
  filmWikipedia: "https://en.wikipedia.org/wiki/A_Hole_in_the_Head"
},
{
  song: "Never on Sunday",
  film: "Never on Sunday",
  year: 1961,
  filmYear: 1960,
  songwriters: ["Manos Hadjidakis"],
  performers: ["Melina Mercouri"],
  spotify: "4qQ7eddVdtio09WkiNWEhu",
  wikipedia: "https://en.wikipedia.org/wiki/Never_on_Sunday",
  wikidata: "Q3338067",
  summary: "Never on Sunday (Greek: Ποτέ την Κυριακή, Poté tin Kyriakí) is a 1960 Greek romantic comedy film starring, written by, and directed by Jules Dassin. The film tells the story of Ilya, a contented Greek prostitute (Melina Mercouri), and Homer (Dassin), an earnest American classicist. Homer attempts to steer her toward morality, while Ilya attempts to make Homer more relaxed. The original screenplay examines the impact of intellectual imperialism upon indigenous joie de vivre.",
  filmDirector: "Jules Dassin",
  filmSummary: "An American scholar in Greece sets about improving the local prostitute with whom he is infatuated.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Never_on_Sunday"
},
{
  song: "Moon River",
  film: "Breakfast at Tiffany's",
  year: 1962,
  filmYear: 1961,
  songwriters: ["Henry Mancini","Johnny Mercer"],
  performers: ["Audrey Hepburn"],
  spotify: "1XwAKjAZ1xDZOcuyZoqce4",
  wikipedia: "https://en.wikipedia.org/wiki/Moon_River",
  wikidata: "Q854971",
  summary: "\"Moon River\" is a song composed by Henry Mancini with lyrics by Johnny Mercer. It was originally performed by Audrey Hepburn in the 1961 film Breakfast at Tiffany's, winning an Academy Award for Best Original Song. The song also won the 1962 Grammy Awards for Record of the Year and Song of the Year. In 1999, Mancini's recording was inducted into the Grammy Hall of Fame. The song has been recorded by many other artists.",
  filmDirector: "Blake Edwards",
  filmSummary: "Holly Golightly is an eccentric New York City playgirl determined to marry a Brazilian millionaire. But when young writer Paul Varjak moves into her apartment building, her past threatens to get in their way.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Breakfast_at_Tiffany%27s_(film)"
},
{
  song: "Days of Wine and Roses",
  film: "Days of Wine and Roses",
  year: 1963,
  filmYear: 1962,
  songwriters: ["Henry Mancini","Johnny Mercer"],
  performers: ["Andy Williams"],
  spotify: "3tvqPPpXyIgKrm4PR9HCf0",
  wikipedia: "https://en.wikipedia.org/wiki/Days_of_Wine_and_Roses_(song)",
  wikidata: "Q3018082",
  summary: "\"Days of Wine and Roses\" is a popular song, from the 1962 film of the same name. The music was written by Henry Mancini with lyrics by Johnny Mercer. They received the Academy Award for Best Original Song for their work, as well as the 1964 Grammy Awards for Record of the Year and Song of the Year. In 2004 it finished at #39 in AFI's 100 Years...100 Songs survey of top tunes in American cinema.",
  filmDirector: "Blake Edwards",
  filmSummary: "An alcoholic falls in love with and gets married to a young woman, whom he systematically addicts to booze so they can share his \"passion\" together.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Days_of_Wine_and_Roses_(film)"
},
{
  song: "Call Me Irresponsible",
  film: "Papa's Delicate Condition",
  year: 1964,
  filmYear: 1963,
  songwriters: ["Jimmy Van Heusen","Sammy Cahn"],
  performers: ["Jackie Gleason"],
  spotify: "5LAwJN9tqGeyduMb4B4r4G",
  wikipedia: "https://en.wikipedia.org/wiki/Call_Me_Irresponsible",
  wikidata: "Q5023026",
  summary: "\"Call Me Irresponsible\" is a 1962 song composed by Jimmy Van Heusen with lyrics written by Sammy Cahn which won the Academy Award for Best Original Song in 1963.",
  filmDirector: "George Marshall",
  filmSummary: "A jolly, family-oriented railroad superintendent tries to get his act together when his love for the bottle starts to alienate him from his wife and oldest daughter.  His younger daughter, however, still remains unflinchingly loyal to him, and they share many fun misadventures over the course of...",
  filmWikipedia: "https://en.wikipedia.org/wiki/Papa%27s_Delicate_Condition"
},
{
  song: "Chim Chim Cher-ee",
  film: "Mary Poppins",
  year: 1965,
  filmYear: 1964,
  songwriters: ["Richard M. Sherman","Robert B. Sherman"],
  performers: ["Dick Van Dyke","Julie Andrews"],
  spotify: "0IKYsgkoaylTKGzrlfrpu7",
  wikipedia: "https://en.wikipedia.org/wiki/Chim_Chim_Cher-ee",
  wikidata: "Q1073399",
  summary: "\"Chim Chim Cher-ee\" is a song from Mary Poppins, the 1964 musical film, and is also featured in the 2004 Mary Poppins musical. It won Best Original Song at the 37th Academy Awards. In 2005, Julie Andrews included this song as part of Julie Andrews Selects Her Favorite Disney Songs.",
  filmDirector: "Robert Stevenson",
  filmSummary: "In turn of the century London, a magical nanny employs music and adventure to help two neglected children become closer to their father.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Mary_Poppins"
},
{
  song: "The Shadow of Your Smile",
  film: "The Sandpiper",
  year: 1966,
  filmYear: 1965,
  songwriters: ["Johnny Mandel","Paul Francis Webster"],
  performers: ["Tony Bennett"],
  spotify: "66YI4JFp7BcMcepibGprsN",
  wikipedia: "https://en.wikipedia.org/wiki/The_Shadow_of_Your_Smile",
  wikidata: "Q3523429",
  summary: "\"The Shadow of Your Smile\", also known as \"Love Theme from The Sandpiper\", is a popular song and jazz standard with music by Johnny Mandel and lyrics by Paul Francis Webster. The song was introduced in the 1965 film The Sandpiper and later became an Easy Listening hit for Tony Bennett in a version arranged and conducted by Mandel. It won the Grammy Award for Song of the Year and the Academy Award for Best Original Song.",
  filmDirector: "Vincente Minnelli",
  filmSummary: "A free-spirited single mother forms a connection with the wedded headmaster of an Episcopalian boarding school in Monterey, California.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Sandpiper"
},
{
  song: "Born Free",
  film: "Born Free",
  year: 1967,
  filmYear: 1966,
  songwriters: ["John Barry","Don Black"],
  performers: ["Matt Monro"],
  spotify: "2c2WEz0vMVvR7Gc27O3sLs",
  wikipedia: "https://en.wikipedia.org/wiki/Born_Free_(Matt_Monro_song)",
  wikidata: "Q2665620",
  summary: "\"Born Free\" is a popular song with music by John Barry and lyrics by Don Black. It was written for the 1966 film of the same name and won an Academy Award for Best Original Song.",
  filmDirector: "James Hill, Tom McGowan",
  filmSummary: "At a national park in Kenya, English game warden George Adamson and his wife, Joy, care for three orphaned lion cubs. After the two larger lions are shipped off to a zoo in the Netherlands, the smallest of the three, Elsa, stays with the couple.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Born_Free"
},
{
  song: "Talk to the Animals",
  film: "Doctor Dolittle",
  year: 1968,
  filmYear: 1967,
  songwriters: ["Leslie Bricusse"],
  performers: ["Rex Harrison"],
  spotify: null,
  wikipedia: "https://en.wikipedia.org/wiki/Talk_to_the_Animals",
  wikidata: "Q7680236",
  summary: "\"Talk to the Animals\" is a song written by British composer Leslie Bricusse. Written for the 1967 film Doctor Dolittle, it won the Academy Award for Best Original Song at the 40th Academy Awards. It was performed in the film by Rex Harrison. The song was not generally well appreciated, and in some cases was disliked, by those who were working on the film during the time of its production.",
  filmDirector: "Richard Fleischer",
  filmSummary: "A veterinarian who can communicate with animals travels abroad to search for a giant sea snail.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Doctor_Dolittle"
},
{
  song: "The Windmills of Your Mind",
  film: "The Thomas Crown Affair",
  year: 1969,
  filmYear: 1968,
  songwriters: ["Michel Legrand","Alan Bergman","Marilyn Bergman"],
  performers: ["Noel Harrison"],
  spotify: "0LAJmyoZLS5ay5zFLtWDgM",
  wikipedia: "https://en.wikipedia.org/wiki/The_Windmills_of_Your_Mind",
  wikidata: "Q1753757",
  summary: "\"The Windmills of Your Mind\" is a song with music by French composer Michel Legrand and English lyrics written by American lyricists Alan and Marilyn Bergman. French lyrics, under the title \"Les Moulins de mon cœur\", were written by Eddy Marnay. It was originally recorded by the English actor Noel Harrison in 1968. The song (with the English lyrics) was introduced in the film The Thomas Crown Affair (1968), and won the Academy Award for Best Original Song.",
  filmDirector: "Norman Jewison",
  filmSummary: "Bored young businessman Thomas Crown decides to plan a robbery and assigns a professional agent with the right information to the job. However, Crown is soon betrayed yet cannot blow his cover as he’s fallen in love.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Thomas_Crown_Affair"
},
{
  song: "Raindrops Keep Fallin' on My Head",
  film: "Butch Cassidy and the Sundance Kid",
  year: 1970,
  filmYear: 1969,
  songwriters: ["Burt Bacharach","Hal David"],
  performers: ["B.J. Thomas"],
  spotify: "0oMTxTIHAt3hstaoObsmFs",
  wikipedia: "https://en.wikipedia.org/wiki/Raindrops_Keep_Fallin%27_on_My_Head",
  wikidata: "Q1501922",
  summary: "\"Raindrops Keep Fallin' on My Head\" is a song written by Burt Bacharach and Hal David for the 1969 film Butch Cassidy and the Sundance Kid. The uplifting lyrics describe somebody who overcomes his troubles and worries by realizing that \"it won't be long till happiness steps up to greet me.\" The single by B. J. Thomas reached No. 1 on charts in the United States, Canada and Norway, and reached No. 38 on the UK Singles Chart.",
  filmDirector: "George Roy Hill",
  filmSummary: "As the west rapidly becomes civilized, a pair of outlaws in 1890s Wyoming find themselves pursued by a posse and decide to flee to South America in hopes of evading the law.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Butch_Cassidy_and_the_Sundance_Kid"
},
{
  song: "For All We Know",
  film: "Lovers and Other Strangers",
  year: 1971,
  filmYear: 1970,
  songwriters: ["Fred Karlin","Robb Royer","James Griffin"],
  performers: ["Larry Meredith"],
  spotify: "5llfFWv1tH61nENrsjg3KZ",
  wikipedia: "https://en.wikipedia.org/wiki/For_All_We_Know_%281970_song%29",
  wikidata: "Q5466139",
  summary: "\"For All We Know\" is a soft rock song written for the 1970 film Lovers and Other Strangers, with music by Fred Karlin and lyrics by Robb Wilson (Robb Royer) and James Arthur Griffin (Jimmy Griffin), both from the American soft rock group Bread. It was originally performed, for the film's soundtrack, by Larry Meredith and won the Academy Award for Best Original Song in 1971.\nThe best known version of the song is by American pop duo the Carpenters which reached No. 3 on the US Billboard Hot 100...",
  filmDirector: "Cy Howard",
  filmSummary: "Mike Vecchio and Susan Henderson are preparing for their upcoming wedding. However, they seem to be the only two people at the wedding that are happy. Mike's brother Richie and his wife Joan are going through a divorce, which is upsetting his overly devout Catholic mother Beatrice.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Lovers_and_Other_Strangers"
},
{
  song: "Theme from Shaft",
  film: "Shaft",
  year: 1972,
  filmYear: 1971,
  songwriters: ["Isaac Hayes"],
  performers: ["Isaac Hayes"],
  spotify: "7KMILVTQdVS4zQ8ilTcpRO",
  wikipedia: "https://en.wikipedia.org/wiki/Theme_from_Shaft",
  wikidata: "Q3987260",
  summary: "\"Theme from Shaft\", written and recorded by Isaac Hayes in 1971, is the soul and funk-styled theme song to the Metro-Goldwyn-Mayer film Shaft. \nThe theme was released as a single (shortened and edited from the longer album version) two months after the movie's soundtrack by Stax Records' Enterprise label. \"Theme from Shaft\" went to no. 2 on the Billboard Soul Singles chart (behind \"Inner City Blues (Make Me Wanna Holler)\" by Marvin Gaye) and to number one on the Billboard Hot 100 in the United...",
  filmDirector: "Gordon Parks",
  filmSummary: "Cool Black private eye John Shaft is hired by a crime lord to find and retrieve his kidnapped daughter.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Shaft"
},
{
  song: "The Morning After",
  film: "The Poseidon Adventure",
  year: 1973,
  filmYear: 1972,
  songwriters: ["Al Kasha","Joel Hirschhorn"],
  performers: ["Maureen McGovern"],
  spotify: "62QRbVm7DqR3eoqgT7pEfs",
  wikipedia: "https://en.wikipedia.org/wiki/The_Morning_After_(Maureen_McGovern_song)",
  wikidata: "Q3521912",
  summary: "\"The Morning After\" is a song written by Al Kasha and Joel Hirschhorn for the 1972 film The Poseidon Adventure, which won Best Original Song at the 45th Academy Awards. Following this success, Maureen McGovern recorded a single version that became a No. 1 hit in the US for two weeks during August 1973, with Gold record sales. Billboard ranked it as the No. 28 song for 1973.",
  filmDirector: "Ronald Neame",
  filmSummary: "When their ocean liner capsizes, a group of passengers struggle to survive and escape.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Poseidon_Adventure"
},
{
  song: "The Way We Were",
  film: "The Way We Were",
  year: 1974,
  filmYear: 1973,
  songwriters: ["Marvin Hamlisch","Alan Bergman","Marilyn Bergman"],
  performers: ["Barbra Streisand"],
  spotify: "1vZTgn4JXWMahR8r99ug5H",
  wikipedia: "https://en.wikipedia.org/wiki/The_Way_We_Were_(song)",
  wikidata: "Q2538389",
  summary: "\"The Way We Were\" is a song by American singer Barbra Streisand from her fifteenth studio album of the same name. It was released as the album's lead single on September 27, 1973, on Columbia Records. The 7\" single was distributed in two different formats, with the standard edition featuring B-side track \"What Are You Doing the Rest of Your Life?\" and the Mexican release instead included an instrumental B-side.",
  filmDirector: "Sydney Pollack",
  filmSummary: "Opposites attract when, during their college days, Katie Morosky, a politically active Jew, meets Hubbell Gardiner, a feckless WASP. Years later, in the wake of World War II, they meet once again and, despite their obvious differences, attempt to make their love for each other work.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Way_We_Were"
},
{
  song: "We May Never Love Like This Again",
  film: "The Towering Inferno",
  year: 1975,
  filmYear: 1974,
  songwriters: ["Al Kasha","Joel Hirschhorn"],
  performers: ["Maureen McGovern"],
  spotify: "4k8AOuix44BSULHnrnAnEq",
  wikipedia: "https://en.wikipedia.org/wiki/We_May_Never_Love_Like_This_Again",
  wikidata: "Q7977090",
  summary: "\"We May Never Love Like This Again\" is a song written by Al Kasha and Joel Hirschhorn for the 1974 disaster film The Towering Inferno. It won the Academy Award for Best Original Song, and was performed by Maureen McGovern both for the film score and, briefly, in the film itself with McGovern portraying a singer.\nHer recording was issued as a single along with her rendition of \"Wherever Love Takes Me\", a song from the film Gold, which would compete with \"We May Never Love Like This Again\" for...",
  filmDirector: "John Guillermin",
  filmSummary: "At the opening party of a colossal—but poorly constructed—skyscraper, a massive fire breaks out, threatening to destroy the tower and everyone in it.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Towering_Inferno"
},
{
  song: "I'm Easy",
  film: "Nashville",
  year: 1976,
  filmYear: 1975,
  songwriters: ["Keith Carradine"],
  performers: ["Keith Carradine"],
  spotify: "4UN5z3IkTamNxngTsS3Qrm",
  wikipedia: "https://en.wikipedia.org/wiki/I%27m_Easy_%28Keith_Carradine_song%29",
  wikidata: "Q5918918",
  summary: "\"I'm Easy\" is an Academy Award-winning song written and performed by Keith Carradine for the 1975 movie Nashville. Carradine recorded a slightly faster version that became a popular music hit in 1976 in the United States.",
  filmDirector: "Robert Altman",
  filmSummary: "The intersecting stories of twenty-four characters—from country star to wannabe to reporter to waitress—connect to the music business in Nashville, Tennessee.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Nashville_(film)"
},
{
  song: "Evergreen",
  film: "A Star Is Born",
  year: 1977,
  filmYear: 1976,
  songwriters: ["Barbra Streisand","Paul Williams"],
  performers: ["Barbra Streisand"],
  spotify: "0j3GgpDSr6ROmp49hcocNR",
  wikipedia: "https://en.wikipedia.org/wiki/Evergreen_(Love_Theme_from_A_Star_Is_Born)",
  wikidata: "Q5417407",
  summary: "\"Evergreen\" (also called \"Love Theme from A Star Is Born\") is the theme song from the 1976 film A Star Is Born. It was composed and performed by American singer, songwriter, actress and director Barbra Streisand with lyrics by Paul Williams, and arranged by Ian Freebairn-Smith. The song was released on the soundtrack album for A Star Is Born.",
  filmDirector: "Frank Pierson",
  filmSummary: "Drunken, has-been rock star John Norman Howard falls in love with unknown singer Esther Hoffman after seeing her perform at a club. He lets her sing a few songs at one of his shows and she becomes the talk of the music industry. Esther's star begins to rise, while John's continues to fall.",
  filmWikipedia: "https://en.wikipedia.org/wiki/A_Star_Is_Born"
},
{
  song: "You Light Up My Life",
  film: "You Light Up My Life",
  year: 1978,
  filmYear: 1977,
  songwriters: ["Joseph Brooks"],
  performers: ["Debby Boone"],
  spotify: "3dFR132gzO8jxD57R2gid3",
  wikipedia: "https://en.wikipedia.org/wiki/You_Light_Up_My_Life_(song)",
  wikidata: "Q8055530",
  summary: "\"You Light Up My Life\" is a ballad written by Joseph Brooks, and originally recorded by Kasey Cisyk for the soundtrack album to the 1977 film of the same title. The song was lip synced in the film by its lead actress, Didi Conn. The cover version of the song by Debby Boone, the daughter of singer Pat Boone, was number one on the Billboard Hot 100 chart for ten consecutive weeks in 1977 and topped Record World magazine's Top 100 Singles Chart for a record 13 weeks.",
  filmDirector: "Joseph Brooks",
  filmSummary: "Laurie has been in show business since she was a child. Her dream is to be a singer, songwriter and actress. Her father wants her to be a comedian like him and Laurie only tries because it pleases her father. But she is a lousy comedian.",
  filmWikipedia: "https://en.wikipedia.org/wiki/You_Light_Up_My_Life_(film)"
},
{
  song: "Last Dance",
  film: "Thank God It's Friday",
  year: 1979,
  filmYear: 1978,
  songwriters: ["Paul Jabara"],
  performers: ["Donna Summer"],
  spotify: "5fKTkCOpnyJko7jZqpbJnX",
  wikipedia: "https://en.wikipedia.org/wiki/Last_Dance_%28Donna_Summer_song%29",
  wikidata: "Q6495758",
  summary: "\"Last Dance\" is a song by American singer-songwriter Donna Summer from the soundtrack to the 1978 film Thank God It's Friday. It was written by Paul Jabara, co-produced by Summer's regular collaborator Giorgio Moroder and Pete Bellotte, and mixed by Grammy Award-winning producer Stephen Short, whose backing vocals are featured in the song. \"Last Dance\" became a critical and commercial success, winning the Academy Award for Best Original Song at the 51st Academy Awards, Golden Globe Award for...",
  filmDirector: "Robert Klane",
  filmSummary: "It's Friday and everyone is going to the hottest new disco in Los Angeles. The Commodores are scheduled to play if Floyd shows up with the instruments and Nicole dreams of becoming a disco star. Other characters are there to win the dance contest, or to put a little excitement into a fifth...",
  filmWikipedia: "https://en.wikipedia.org/wiki/Thank_God_It%27s_Friday"
},
{
  song: "It Goes Like It Goes",
  film: "Norma Rae",
  year: 1980,
  filmYear: 1979,
  songwriters: ["David Shire","Norman Gimbel"],
  performers: ["Jennifer Warnes"],
  spotify: "2p26s1c9ARKwSeTrXUGt2O",
  wikipedia: "https://en.wikipedia.org/wiki/It_Goes_Like_It_Goes",
  wikidata: "Q6090029",
  summary: "\"It Goes Like It Goes\" is a song written by David Shire and Norman Gimbel. Jennifer Warnes sang the vocals for the Norma Rae soundtrack in 1979. \"It Goes Like It Goes\" won an Academy Award for Best Original Song in 1979, defeating such fellow nominees as \"Through the Eyes of Love\" from Ice Castles and \"Rainbow Connection\" from The Muppet Movie, to the consternation of some critics. Shortly after its Oscar win, the song was covered and released as a single by Dusty Springfield.",
  filmDirector: "Martin Ritt",
  filmSummary: "Norma Rae is a southern textile worker employed in a factory with intolerable working conditions. This concern about the situation gives her the gumption to be the key associate to a visiting labor union organizer.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Norma_Rae"
},
{
  song: "Fame",
  film: "Fame",
  year: 1981,
  filmYear: 1980,
  songwriters: ["Michael Gore","Dean Pitchford"],
  performers: ["Irene Cara"],
  spotify: "5CI1FP2Volc9wjz2MBZsGx",
  wikipedia: "https://en.wikipedia.org/wiki/Fame_%28Irene_Cara_song%29",
  wikidata: "Q1140499",
  summary: "\"Fame\" is a song written by Michael Gore (music) and Dean Pitchford (lyrics) and released in 1980, that achieved chart success as the theme song to the Fame film and TV series. The song was performed by Irene Cara, who played the role of Coco Hernandez in the original film. It was also her debut single as a recording artist. The song won the Academy Award for Best Original Song in 1980, and the Golden Globe Award the same year. In 2004, it finished at number 51 on AFI's 100 Years...100 Songs...",
  filmDirector: "Alan Parker",
  filmSummary: "A chronicle of the lives of several teenagers who attend a New York high school for students gifted in the performing arts.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Fame"
},
{
  song: "Arthur's Theme (Best That You Can Do)",
  film: "Arthur",
  year: 1982,
  filmYear: 1981,
  songwriters: ["Burt Bacharach","Carole Bayer Sager","Christopher Cross","Peter Allen"],
  performers: ["Christopher Cross"],
  spotify: "5fnOrhQ4KgT5irGCjIccGH",
  wikipedia: "https://en.wikipedia.org/wiki/Arthur%27s_Theme_(Best_That_You_Can_Do)",
  wikidata: "Q4799230",
  summary: "\"Arthur's Theme (Best That You Can Do)\" is a song performed and co-written by American singer-songwriter Christopher Cross as the main theme for the 1981 film Arthur. It was recognized as the year's Best Original Song at both the 54th Academy Awards and 39th Golden Globe Awards. A commercial success in the United States, it reached the top of both the Billboard Hot 100 and Hot Adult Contemporary charts in October 1981, remaining at the top of the Hot 100 for three consecutive weeks.",
  filmDirector: "Steve Gordon",
  filmSummary: "Arthur is a 30-year-old child who will inherit $750 million if he complies with his family's demands and marries the woman of their choosing.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Arthur"
},
{
  song: "Up Where We Belong",
  film: "An Officer and a Gentleman",
  year: 1983,
  filmYear: 1982,
  songwriters: ["Jack Nitzsche","Buffy Sainte-Marie","Will Jennings"],
  performers: ["Joe Cocker","Jennifer Warnes"],
  spotify: "4U6mBgGP8FXN6UH4T3AJhu",
  wikipedia: "https://en.wikipedia.org/wiki/Up_Where_We_Belong",
  wikidata: "Q2497917",
  summary: "\"Up Where We Belong\" is a song written by Jack Nitzsche, Buffy Sainte-Marie and Will Jennings that was recorded by Joe Cocker and Jennifer Warnes for the 1982 film An Officer and a Gentleman. Warnes was recommended to sing a song from the film because of her previous soundtrack successes, and she had the idea for the song to be a duet that she would perform with Cocker.",
  filmDirector: "Taylor Hackford",
  filmSummary: "Zack Mayo is an aloof, taciturn man who aspires to be a navy pilot. Once he arrives at training camp for his 13-week officer's course, Mayo runs afoul of abrasive, no-nonsense drill Sergeant Emil Foley.",
  filmWikipedia: "https://en.wikipedia.org/wiki/An_Officer_and_a_Gentleman"
},
{
  song: "Flashdance... What a Feeling",
  film: "Flashdance",
  year: 1984,
  filmYear: 1983,
  songwriters: ["Giorgio Moroder","Keith Forsey","Irene Cara"],
  performers: ["Irene Cara"],
  spotify: "3cbV252akVZInSvJk7jAYX",
  wikipedia: "https://en.wikipedia.org/wiki/Flashdance..._What_a_Feeling",
  wikidata: "Q1434095",
  summary: "\"Flashdance... What a Feeling\" is a song from the 1983 film Flashdance with music by Giorgio Moroder and lyrics by Keith Forsey and the song's performer, Irene Cara. The song spent six weeks at number one on the Billboard Hot 100 and topped the charts around the world. It was awarded Gold certification by the Recording Industry Association of America for sales of one million copies and won the Academy Award and Golden Globe for Best Original Song and earned Cara the Grammy Award for Best Female...",
  filmDirector: "Adrian Lyne",
  filmSummary: "Alex Owens, a young woman juggling between two odd jobs, aspires to become a successful ballet dancer. Nick, who is her boss and lover, supports and encourages her to fulfil her dream.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Flashdance"
},
{
  song: "I Just Called to Say I Love You",
  film: "The Woman in Red",
  year: 1985,
  filmYear: 1984,
  songwriters: ["Stevie Wonder"],
  performers: ["Stevie Wonder"],
  spotify: "6RNDeRnWsRMjPdNVgupZCs",
  wikipedia: "https://en.wikipedia.org/wiki/I_Just_Called_to_Say_I_Love_You",
  wikidata: "Q1323577",
  summary: "\"I Just Called to Say I Love You\" is a ballad written, produced, and performed by American R&B singer and songwriter Stevie Wonder. It was a major international hit, and remains Wonder's best-selling single to date, reaching number one in 28 countries worldwide. The song was the lead single from the 1984 soundtrack album The Woman in Red, along with two other songs by Wonder, and scored number one on the Billboard Hot 100 for three weeks from October 13 to 27, 1984.",
  filmDirector: "Gene Wilder",
  filmSummary: "When a happily married family man, who would never consider an affair, meets a beautiful woman in red, he is totally infatuated and desperate to make her acquaintance. However, as he tries out various schemes to sneak out to meet her, he realizes that adultery is not quite as easy as it looks.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Woman_in_Red"
},
{
  song: "Say You, Say Me",
  film: "White Nights",
  year: 1986,
  filmYear: 1985,
  songwriters: ["Lionel Richie"],
  performers: ["Lionel Richie"],
  spotify: "17CPezzLWzvGfpZW6X8XT0",
  wikipedia: "https://en.wikipedia.org/wiki/Say_You,_Say_Me",
  wikidata: "Q2040064",
  summary: "\"Say You, Say Me\" is a song written and recorded by American singer and songwriter Lionel Richie for the film White Nights. The single hit number one on the Billboard Hot 100 and on the Hot Black Singles chart in December 1985. It also became Richie's ninth number-one on the Billboard Adult Contemporary chart. The track is not available on the film's soundtrack album, as Motown did not want Richie's first single following the massive success of his 1983 album Can't Slow Down to appear on...",
  filmDirector: "Taylor Hackford",
  filmSummary: "After his plane crashes in Siberia, a Russian dancer, who defected to the West, is held prisoner in the Soviet Union. The KGB keeps him under watch and tries to convince him to become a dancer for the Kirov Academy of Ballet again.",
  filmWikipedia: "https://en.wikipedia.org/wiki/White_Nights"
},
{
  song: "Take My Breath Away",
  film: "Top Gun",
  year: 1987,
  filmYear: 1986,
  songwriters: ["Giorgio Moroder","Tom Whitlock"],
  performers: ["Berlin"],
  spotify: "15MJ5NThPjj6xhPcts8MiY",
  wikipedia: "https://en.wikipedia.org/wiki/Take_My_Breath_Away",
  wikidata: "Q1073369",
  summary: "\"Take My Breath Away\" is a song written by Giorgio Moroder and Tom Whitlock for the 1986 film Top Gun's soundtrack, performed by American new wave band Berlin and included on their album Count Three & Pray. The song won the Academy Award for Best Original Song at the 59th Academy Awards, as well as the Golden Globe Award for Best Original Song at the 44th Golden Globe Awards in 1986.",
  filmDirector: "Tony Scott",
  filmSummary: "For Lieutenant Pete 'Maverick' Mitchell and his friend and co-pilot Nick 'Goose' Bradshaw, being accepted into an elite training school for fighter pilots is a dream come true. But a tragedy, as well as personal demons, will threaten Pete's dreams of becoming an ace pilot.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Top_Gun"
},
{
  song: "(I've Had) The Time of My Life",
  film: "Dirty Dancing",
  year: 1988,
  filmYear: 1987,
  songwriters: ["Franke Previte","John DeNicola","Donald Markowitz"],
  performers: ["Bill Medley","Jennifer Warnes"],
  spotify: "6W7ztLBiRzBN46ZaPAcQ0F",
  wikipedia: "https://en.wikipedia.org/wiki/(I%27ve_Had)_The_Time_of_My_Life",
  wikidata: "Q1069831",
  summary: "\"(I've Had) The Time of My Life\" is a song composed by Franke Previte, John DeNicola, and Donald Markowitz. It was recorded by American singers Bill Medley and Jennifer Warnes and used as the theme song for the 1987 film Dirty Dancing. The song has won a number of awards, including the Academy Award for Best Original Song, the Golden Globe Award for Best Original Song, and the Grammy Award for Best Pop Performance by a Duo or Group with Vocals.",
  filmDirector: "Emile Ardolino",
  filmSummary: "Expecting the usual tedium that accompanies a summer in the Catskills with her family, 17-year-old Frances 'Baby' Houseman is surprised to find herself stepping into the shoes of a professional hoofer—and unexpectedly falling in love.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Dirty_Dancing"
},
{
  song: "Let the River Run",
  film: "Working Girl",
  year: 1989,
  filmYear: 1988,
  songwriters: ["Carly Simon"],
  performers: ["Carly Simon"],
  spotify: "6zv8T4vuevldBjH65XjLXH",
  wikipedia: "https://en.wikipedia.org/wiki/Let_the_River_Run",
  wikidata: "Q1822527",
  summary: "\"Let the River Run\" is a song written, composed, and performed by American singer-songwriter Carly Simon, and the theme to the 1988 Mike Nichols film Working Girl. The song won the Academy Award for Best Original Song, the Golden Globe Award for Best Original Song (tying with \"Two Hearts\" by Phil Collins and Lamont Dozier from Buster), and the Grammy Award for Best Song Written Specifically for a Motion Picture or Television.",
  filmDirector: "Mike Nichols",
  filmSummary: "When a secretary's idea is stolen by her boss, she seizes an opportunity to steal it back by pretending she has her boss' job.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Working_Girl"
},
{
  song: "Under the Sea",
  film: "The Little Mermaid",
  year: 1990,
  filmYear: 1989,
  songwriters: ["Alan Menken","Howard Ashman"],
  performers: ["Samuel E. Wright"],
  spotify: "4qqfI5oNO53a6W7nWfutKH",
  wikipedia: "https://en.wikipedia.org/wiki/Under_the_Sea",
  wikidata: "Q577775",
  summary: "\"Under the Sea\" is a song from Disney's 1989 animated film The Little Mermaid, composed by Alan Menken with lyrics by Howard Ashman. It is influenced by the calypso style of the Caribbean which originated in Trinidad and Tobago, as well as reggae, which originated in Jamaica. The song was performed in the film by Samuel E. Wright. The track won the Academy Award for Best Original Song in 1989, the first for a Disney film since \"Chim Chim Cher-ee\" from Mary Poppins in 1964.",
  filmDirector: "Ron Clements, John Musker",
  filmSummary: "This colorful adventure tells the story of an impetuous mermaid princess named Ariel who falls in love with the very human Prince Eric and puts everything on the line for the chance to be with him. Memorable songs and characters -- including the villainous sea witch Ursula.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Little_Mermaid"
},
{
  song: "Sooner or Later (I Always Get My Man)",
  film: "Dick Tracy",
  year: 1991,
  filmYear: 1990,
  songwriters: ["Stephen Sondheim"],
  performers: ["Madonna"],
  spotify: "0QLuoNpyzXMcCLfVtFScE2",
  wikipedia: "https://en.wikipedia.org/wiki/Sooner_or_Later_(Madonna_song)",
  wikidata: "Q3488863",
  summary: "\"Sooner or Later\" is a song recorded by the American singer Madonna from her soundtrack album I'm Breathless: Music from and Inspired by the Film Dick Tracy (1990). Written by American composer Stephen Sondheim and produced by Madonna and Bill Bottrell, the song was used in the parent film, Dick Tracy. \"Sooner or Later\" was composed to evoke the theatrical nature and style of the film.",
  filmDirector: "Warren Beatty",
  filmSummary: "The comic strip detective finds his life vastly complicated when Breathless Mahoney makes advances towards him while he is trying to battle Big Boy Caprice's united mob.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Dick_Tracy"
},
{
  song: "Beauty and the Beast",
  film: "Beauty and the Beast",
  year: 1992,
  filmYear: 1991,
  songwriters: ["Alan Menken","Howard Ashman"],
  performers: ["Celine Dion","Peabo Bryson"],
  spotify: "7B3UAPLYAbwXVgbHSKEaTw",
  wikipedia: "https://en.wikipedia.org/wiki/Beauty_and_the_Beast_(Disney_song)",
  wikidata: "Q2334872",
  summary: "\"Beauty and the Beast\" is a song written by lyricist Howard Ashman and composer Alan Menken for the Disney animated feature film Beauty and the Beast (1991). The film's theme song, the Broadway-inspired ballad was first recorded by British-American actress Angela Lansbury in her role as the voice of the character Mrs. Potts, and essentially describes the relationship between its two main characters Belle and the Beast, specifically how the couple has learned to accept their differences and in...",
  filmDirector: "Gary Trousdale, Kirk Wise",
  filmSummary: "Follow the adventures of Belle, a bright young woman who finds herself in the castle of a prince who's been turned into a mysterious beast. With the help of the castle's enchanted staff, Belle soon learns the most important lesson of all -- that true beauty comes from within.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Beauty_and_the_Beast"
},
{
  song: "A Whole New World",
  film: "Aladdin",
  year: 1993,
  filmYear: 1992,
  songwriters: ["Alan Menken","Tim Rice"],
  performers: ["Brad Kane","Lea Salonga"],
  spotify: "1hwdPQtFHISvZ9SXMkNrIK",
  wikipedia: "https://en.wikipedia.org/wiki/A_Whole_New_World",
  wikidata: "Q1855902",
  summary: "\"A Whole New World\" is the signature song from Disney's 1992 animated feature film Aladdin, with music by Alan Menken and lyrics by Tim Rice. A duet originally recorded by singers Brad Kane and Lea Salonga in their respective roles as the singing voices of the main characters Aladdin and Jasmine, the ballad serves as both the film's love and theme song.",
  filmDirector: "Ron Clements, John Musker",
  filmSummary: "In the boorish city of Agrabah, kind-hearted street urchin Aladdin and Princess Jasmine fall in love, although she can only marry a prince. He and power-hungry Grand Vizier Jafar vie for a magic lamp that can fulfill their wishes.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Aladdin"
},
{
  song: "Streets of Philadelphia",
  film: "Philadelphia",
  year: 1994,
  filmYear: 1993,
  songwriters: ["Bruce Springsteen"],
  performers: ["Bruce Springsteen"],
  spotify: "3fbnbn6A5O5RNb08tlUEgd",
  wikipedia: "https://en.wikipedia.org/wiki/Streets_of_Philadelphia",
  wikidata: "Q1432236",
  summary: "\"Streets of Philadelphia\" is a song written and performed by American rock musician Bruce Springsteen for the 1993 film Philadelphia, starring Tom Hanks, an early mainstream film dealing with HIV/AIDS. Released as a single by Columbia Records in February 1994, the song was a hit in many countries, topping the singles charts of Austria, Canada, France, Germany, Iceland, Ireland, Italy, and Norway.",
  filmDirector: "Jonathan Demme",
  filmSummary: "Two competing lawyers join forces to sue a prestigious law firm for AIDS discrimination. As their unlikely friendship develops, their courage overcomes the prejudice and corruption of their powerful adversaries.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Philadelphia_(film)"
},
{
  song: "Can You Feel the Love Tonight",
  film: "The Lion King",
  year: 1995,
  filmYear: 1994,
  songwriters: ["Elton John","Tim Rice"],
  performers: ["Elton John"],
  spotify: "67HKtdqchK0rmODxsBeWT8",
  wikipedia: "https://en.wikipedia.org/wiki/Can_You_Feel_the_Love_Tonight",
  wikidata: "Q1032927",
  summary: "\"Can You Feel the Love Tonight\" is a song from Disney's 1994 animated feature film The Lion King composed by British musician Elton John with lyrics by Tim Rice. Released as a single in May 1994, by Hollywood, Walt Disney and Mercury Records, the song was a hit in the UK, peaking at number 14 on the UK singles chart, and achieved success in the United States, reaching number four on the Billboard Hot 100. It was a number-one hit in Canada and France.",
  filmDirector: "Roger Allers, Rob Minkoff",
  filmSummary: "Young lion prince Simba, eager to one day become king of the Pride Lands, grows up under the watchful eye of his father Mufasa; all the while his villainous uncle Scar conspires to take the throne for himself.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Lion_King"
},
{
  song: "Colors of the Wind",
  film: "Pocahontas",
  year: 1996,
  filmYear: 1995,
  songwriters: ["Alan Menken","Stephen Schwartz"],
  performers: ["Vanessa Williams"],
  spotify: "7xG1fakElLbxwyr9eyGEK6",
  wikipedia: "https://en.wikipedia.org/wiki/Colors_of_the_Wind",
  wikidata: "Q2993233",
  summary: "\"Colors of the Wind\" is a song written by composer Alan Menken and lyricist Stephen Schwartz for Walt Disney Pictures' 33rd animated feature film Pocahontas (1995). The film's theme song, \"Colors of the Wind\", was originally recorded by American singer and actress Judy Kuhn in her role as the singing voice of Pocahontas. A pop ballad, the song's lyrics are about animism and respecting nature, finding its roots in indigenous Native American culture, perspectives which have later been adopted in...",
  filmDirector: "Mike Gabriel, Eric Goldberg",
  filmSummary: "Pocahontas, daughter of a Native American tribe chief, falls in love with an English soldier as colonists invade 17th century Virginia.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Pocahontas"
},
{
  song: "You Must Love Me",
  film: "Evita",
  year: 1997,
  filmYear: 1996,
  songwriters: ["Andrew Lloyd Webber","Tim Rice"],
  performers: ["Madonna"],
  spotify: "78JPL7uIfs6Imm57r1QETk",
  wikipedia: "https://en.wikipedia.org/wiki/You_Must_Love_Me",
  wikidata: "Q2606093",
  summary: "\"You Must Love Me\" is a song recorded by American singer and songwriter Madonna. It was written by Andrew Lloyd Webber and Tim Rice, for the 1996 film adaptation of the musical, Evita, based on the life of Argentinian leader Eva Perón. The song was released on October 15, 1996, by Warner Bros. as the lead single from the film's soundtrack. After years of not working together due to their individual projects, Lloyd Webber and Rice collaborated on creating a new track for the film, with the hope...",
  filmDirector: "Alan Parker",
  filmSummary: "The hit musical based on the life of Evita Duarte, an Argentinian actress who eventually became the wife of Argentinian president Juan Perón, and the most beloved and hated woman in Argentina.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Evita"
},
{
  song: "My Heart Will Go On",
  film: "Titanic",
  year: 1998,
  filmYear: 1997,
  songwriters: ["James Horner","Will Jennings"],
  performers: ["Celine Dion"],
  spotify: "33LC84JgLvK2KuW43MfaNq",
  wikipedia: "https://en.wikipedia.org/wiki/My_Heart_Will_Go_On",
  wikidata: "Q189505",
  summary: "\"My Heart Will Go On\" is a song recorded by the Canadian singer Celine Dion as the theme for the 1997 film Titanic. Composed by James Horner with lyrics by Will Jennings, it was issued internationally as a single by Columbia Records and Epic Records on November 24, 1997, and appeared on Dion's album Let's Talk About Love (1997) and the Titanic soundtrack. Horner developed the melody as an instrumental motif for Titanic before proposing a vocal version.",
  filmDirector: "James Cameron",
  filmSummary: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Titanic"
},
{
  song: "When You Believe",
  film: "The Prince of Egypt",
  year: 1999,
  filmYear: 1998,
  songwriters: ["Stephen Schwartz"],
  performers: ["Mariah Carey","Whitney Houston"],
  spotify: "0JN7vUgUolHGHFrOR8xk7S",
  wikipedia: "https://en.wikipedia.org/wiki/When_You_Believe",
  wikidata: "Q2564289",
  summary: "\"When You Believe\" is a song made for the 1998 DreamWorks musical animated feature The Prince of Egypt, with music and lyrics by Stephen Schwartz. A pop single version of \"When You Believe\" performed by American singers Whitney Houston and Mariah Carey, with additional music and lyrics by writer-producer Kenneth \"Babyface\" Edmonds, was also recorded for the film's end credits and its soundtrack album by DreamWorks Records.",
  filmDirector: "Brenda Chapman, Steve Hickner, Simon Wells",
  filmSummary: "The strong bond between two Royal Egyptian brothers is challenged when their chosen responsibilities set them at odds, with extraordinary consequences.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Prince_of_Egypt"
},
{
  song: "You'll Be in My Heart",
  film: "Tarzan",
  year: 2000,
  filmYear: 1999,
  songwriters: ["Phil Collins"],
  performers: ["Phil Collins"],
  spotify: "4Y8vb1uy9IjM2V1hqvrAid",
  wikipedia: "https://en.wikipedia.org/wiki/You%27ll_Be_in_My_Heart",
  wikidata: "Q2606147",
  summary: "\"You'll Be in My Heart\" is a song by English drummer and singer Phil Collins from the 1999 Disney animated feature Tarzan. It appeared on Tarzan: An Original Walt Disney Records Soundtrack as well as various other Disney compilations. It won the Academy Award for Best Original Song, and became Collins' last US top-40 single, peaking at number 21. A demo version with Collins playing piano and singing is featured as a bonus on the 2-DVD Special Edition of Tarzan, along with \"I Will Follow\"...",
  filmDirector: "Chris Buck, Kevin Lima",
  filmSummary: "Tarzan was a small orphan who was raised by an ape named Kala since he was a child. He believed that this was his family, but on an expedition Jane Porter is rescued by Tarzan. He then finds out that he's human. Now Tarzan must make the decision as to which family he should belong to...",
  filmWikipedia: "https://en.wikipedia.org/wiki/Tarzan"
},
{
  song: "Things Have Changed",
  film: "Wonder Boys",
  year: 2001,
  filmYear: 2000,
  songwriters: ["Bob Dylan"],
  performers: ["Bob Dylan"],
  spotify: "5KOi77ameCimkAdw0DMNoy",
  wikipedia: "https://en.wikipedia.org/wiki/Things_Have_Changed",
  wikidata: "Q7784455",
  summary: "\"Things Have Changed\" is a song from the film Wonder Boys, written and performed by Bob Dylan and released as a single on May 1, 2000. It won the Academy Award for Best Original Song and the Golden Globe Award for Best Original Song. It was included in the compilation albums The Essential Bob Dylan in 2000, The Best of Bob Dylan in 2005 and Dylan in 2007.",
  filmDirector: "Curtis Hanson",
  filmSummary: "Grady is a 50-ish English professor who hasn't had a thing published in years—not since he wrote his award winning 'Great American Novel' 7 years ago. This weekend proves even worse than he could imagine as he finds himself reeling from one misadventure to another in the company of a new wonder boy...",
  filmWikipedia: "https://en.wikipedia.org/wiki/Wonder_Boys_(film)"
},
{
  song: "If I Didn't Have You",
  film: "Monsters, Inc.",
  year: 2002,
  filmYear: 2001,
  songwriters: ["Randy Newman"],
  performers: ["Billy Crystal","John Goodman"],
  spotify: "7xf3S6Bv8hDqOtevZou602",
  wikipedia: "https://en.wikipedia.org/wiki/If_I_Didn%27t_Have_You",
  wikidata: "Q1569714",
  summary: "If I Didn't Have You may refer to: \"If I Didn't Have You\" (Disney song), written by Randy Newman and performed by John Goodman and Billy Crystal from the film Monsters, Inc. \"If I Didn't Have You\" (Randy Travis song), from the album Greatest Hits, Volume 1 \"If I Didn't Have You\" (Thompson Square song), from the album Just Feels Good \"If I Didn't Have You\", a song by Amanda Marshall from the album Tuesday's Child \"If I Didn't Have You\", a song by Tim Minchin from the album Ready for This?",
  filmDirector: "Pete Docter",
  filmSummary: "Lovable Sulley and his wisecracking sidekick Mike Wazowski are the top scare team at Monsters, Inc., the scream-processing factory in Monstropolis. When a little girl named Boo wanders into their world, it's the monsters who are scared silly, and it's up to Sulley and Mike to keep her out of sight...",
  filmWikipedia: "https://en.wikipedia.org/wiki/Monsters,_Inc."
},
{
  song: "Lose Yourself",
  film: "8 Mile",
  year: 2003,
  filmYear: 2002,
  songwriters: ["Eminem","Jeff Bass","Luis Resto"],
  performers: ["Eminem"],
  spotify: "5Z01UMMf7V1o0MzF86s6WJ",
  wikipedia: "https://en.wikipedia.org/wiki/Lose_Yourself",
  wikidata: "Q483882",
  summary: "\"Lose Yourself\" is a song by American rapper Eminem from the soundtrack to the 2002 film 8 Mile. The song was composed and produced by Eminem, longtime collaborator Jeff Bass (one half of the production duo Bass Brothers), and Luis Resto. The lyrics were written by Eminem. It was released on October 28, 2002, as the lead single from the soundtrack. \"Lose Yourself\" was a commercial success, becoming Eminem's first Billboard Hot 100 number-one single and remaining there for twelve consecutive...",
  filmDirector: "Curtis Hanson",
  filmSummary: "For Jimmy Smith, Jr., life is a daily fight just to keep hope alive. Feeding his dreams in Detroit's vibrant music scene, Jimmy wages an extraordinary personal struggle to find his own voice - and earn a place in a world where rhymes rule, legends are born and every moment… is another chance.",
  filmWikipedia: "https://en.wikipedia.org/wiki/8_Mile_(film)"
},
{
  song: "Into the West",
  film: "The Lord of the Rings: The Return of the King",
  year: 2004,
  filmYear: 2003,
  songwriters: ["Annie Lennox","Fran Walsh","Howard Shore"],
  performers: ["Annie Lennox"],
  spotify: "0gSEyG7pOFuHM05433EibX",
  wikipedia: "https://en.wikipedia.org/wiki/Into_the_West_(song)",
  wikidata: "Q945735",
  summary: "\"Into the West\" is a song performed by Scottish singer Annie Lennox, and the closing credits song of the 2003 film The Lord of the Rings: The Return of the King. It was written by Lennox, Return of the King producer and co-writer Fran Walsh, and composed and co-written by the film's composer Howard Shore.",
  filmDirector: "Peter Jackson",
  filmSummary: "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Lord_of_the_Rings:_The_Return_of_the_King"
},
{
  song: "Al otro lado del río",
  film: "The Motorcycle Diaries",
  year: 2005,
  filmYear: 2004,
  songwriters: ["Jorge Drexler"],
  performers: ["Jorge Drexler"],
  spotify: "5BudpQ0Ct9sss8c9Fqv9MJ",
  wikipedia: "https://en.wikipedia.org/wiki/Al_otro_lado_del_r%C3%ADo",
  wikidata: "Q2831625",
  summary: "\"Al otro lado del río\" (transl. \"On the Other Side of the River\") is a song by Uruguayan singer Jorge Drexler from the soundtrack album for the film The Motorcycle Diaries (2004). It was released as a single on 15 March 2005, by Dro East West. Besides the film's soundtrack, the song was included in reissue editions of Drexler's seventh studio album Eco (2004) as a bonus track. In June 2020, he performed the song at the launch show of the app 342 Amazônia at Circo Voador.",
  filmDirector: "Walter Salles",
  filmSummary: "Based on the journals of Che Guevara, leader of the Cuban Revolution. In his memoirs, Guevara recounts adventures he and best friend Alberto Granado had while crossing South America by motorcycle in the early 1950s.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Motorcycle_Diaries_(film)"
},
{
  song: "It's Hard Out Here for a Pimp",
  film: "Hustle & Flow",
  year: 2006,
  filmYear: 2005,
  songwriters: ["Jordan Houston","Cedric Coleman","Paul Beauregard"],
  performers: ["Three 6 Mafia"],
  spotify: "17ZCxegdCt1y0reBkHVmMB",
  wikipedia: "https://en.wikipedia.org/wiki/It%27s_Hard_out_Here_for_a_Pimp",
  wikidata: "Q1546927",
  summary: "\"It's Hard out Here for a Pimp\" is a song written by American hip hop group Three 6 Mafia, alongside Cedric Coleman, as the theme song to the American drama film Hustle & Flow (2005). It won the Academy Award for Best Original Song and in 2006 was ranked number 80 on VH1's \"100 Greatest Songs of Hip Hop\".",
  filmDirector: "Craig Brewer",
  filmSummary: "With help from his friends, a Memphis pimp in a mid-life crisis attempts to become a successful hip-hop emcee.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Hustle_%26_Flow"
},
{
  song: "I Need to Wake Up",
  film: "An Inconvenient Truth",
  year: 2007,
  filmYear: 2006,
  songwriters: ["Melissa Etheridge"],
  performers: ["Melissa Etheridge"],
  spotify: "7mOfeDExZHCImmcmGYrv3T",
  wikipedia: "https://en.wikipedia.org/wiki/I_Need_to_Wake_Up",
  wikidata: "Q6078012",
  summary: "\"I Need to Wake Up\" is a song by Melissa Etheridge, written for the 2006 documentary film, An Inconvenient Truth. It is the first instance of a documentary film winning the Best Song category, beating three songs nominated from the musical film Dreamgirls and one from the Pixar animated film Cars. Etheridge received the 2006 Academy Award for Best Original Song for \"I Need to Wake Up\".",
  filmDirector: "Davis Guggenheim",
  filmSummary: "A documentary on Al Gore's campaign to make the issue of global warming a recognized problem worldwide.",
  filmWikipedia: "https://en.wikipedia.org/wiki/An_Inconvenient_Truth"
},
{
  song: "Falling Slowly",
  film: "Once",
  year: 2008,
  filmYear: 2007,
  songwriters: ["Glen Hansard","Markéta Irglová"],
  performers: ["Glen Hansard","Markéta Irglová"],
  spotify: "6EIVLz5xM1xE29r0OmIkWt",
  wikipedia: "https://en.wikipedia.org/wiki/Falling_Slowly",
  wikidata: "Q1396268",
  summary: "\"Falling Slowly\" is an indie folk/indie rock song written, composed and performed by Glen Hansard and Markéta Irglová. It was featured on the soundtrack of the 2007 Irish musical romance film Once, which starred Hansard and Irglová, and for which it won the Academy Award for Best Original Song at the 80th Academy Awards. The song was also recorded by Hansard's band The Frames.",
  filmDirector: "John Carney",
  filmSummary: "A vacuum repairman moonlights as a street musician and hopes for his big break. One day a Czech immigrant, who earns a living selling flowers, approaches him with the news that she is also an aspiring singer-songwriter.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Once_(film)"
},
{
  song: "Jai Ho",
  film: "Slumdog Millionaire",
  year: 2009,
  filmYear: 2008,
  songwriters: ["A. R. Rahman","Gulzar"],
  performers: ["Sukhwinder Singh","Tanvi Shah","Mahalaxmi Iyer","Vijay Prakash"],
  spotify: "0BlMvHfyilCmgKrNUQabR6",
  wikipedia: "https://en.wikipedia.org/wiki/Jai_Ho_(song)",
  wikidata: "Q1396254",
  summary: "\"Jai Ho\" is a song composed by A.R. Rahman for the 2008 film Slumdog Millionaire, featuring Dev Patel and Freida Pinto. When Danny Boyle, the director of Slumdog Millionaire, approached Rahman to compose its soundtrack, he included the song. \"Jai Ho\" accompanies a choreographed dance sequence at the end credits of the film (choreographed by Longinus Fernandes). Indian singer Tanvi Shah wrote and provided vocals for an English section of the song.",
  filmDirector: "Danny Boyle",
  filmSummary: "A teenager reflects on his life after being accused of cheating on the Indian version of \"Who Wants to be a Millionaire?\".",
  filmWikipedia: "https://en.wikipedia.org/wiki/Slumdog_Millionaire"
},
{
  song: "The Weary Kind",
  film: "Crazy Heart",
  year: 2010,
  filmYear: 2009,
  songwriters: ["Ryan Bingham","T Bone Burnett"],
  performers: ["Ryan Bingham"],
  spotify: "5uqQQtXsY2HJLbPVPwcz6C",
  wikipedia: "https://en.wikipedia.org/wiki/The_Weary_Kind",
  wikidata: "Q3524015",
  summary: "\"The Weary Kind\" (full title \"The Weary Kind (Theme from Crazy Heart)\") is a country song written by Ryan Bingham and T Bone Burnett for the film Crazy Heart, a 2009 film directed by Scott Cooper starring Jeff Bridges and Maggie Gyllenhaal. Colin Farrell and Bridges perform renditions of the song in the film. Bingham and his Dead Horses serve as Bridges' backing band in the film.",
  filmDirector: "Scott Cooper",
  filmSummary: "When reporter Jean Craddock interviews Bad Blake—an alcoholic, seen-better-days country music legend—they connect, and the hard-living crooner sees a possible saving grace in a life with Jean and her young son.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Crazy_Heart"
},
{
  song: "We Belong Together",
  film: "Toy Story 3",
  year: 2011,
  filmYear: 2010,
  songwriters: ["Randy Newman"],
  performers: ["Randy Newman"],
  spotify: "2m1mYan1nvOMORlb12q2Y9",
  wikipedia: "https://en.wikipedia.org/wiki/We_Belong_Together_(Randy_Newman_song)",
  wikidata: "Q1552850",
  summary: "\"We Belong Together\" is a song written, composed and performed by Randy Newman for the 2010 film Toy Story 3. The song was nominated for several Best Original Song awards from various film society and awards committees. The song won the Academy Award for Best Original Song at the 83rd Academy Awards in February 2011.",
  filmDirector: "Lee Unkrich",
  filmSummary: "Woody, Buzz, and the rest of Andy's toys haven't been played with in years. With Andy about to go to college, the gang find themselves accidentally left at a nefarious day care center. The toys must band together to escape and return home to Andy.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Toy_Story_3"
},
{
  song: "Man or Muppet",
  film: "The Muppets",
  year: 2012,
  filmYear: 2011,
  songwriters: ["Bret McKenzie"],
  performers: ["Jason Segel","Walter"],
  spotify: "1JyG5yuwpN0VIi4wbqvDfB",
  wikipedia: "https://en.wikipedia.org/wiki/Man_or_Muppet",
  wikidata: "Q1621399",
  summary: "\"Man or Muppet\" is a song from Walt Disney Pictures' 2011 musical comedy film The Muppets, written by singer-songwriter Bret McKenzie. Performed by the film's main characters, Gary (Jason Segel) and Walter (Peter Linz), the song also features Bill Barretta and Jim Parsons portraying the contrasting identities of Gary and Walter, respectively. The song was released by Walt Disney Records on November 22, 2011, as part of the film's original soundtrack.",
  filmDirector: "James Bobin",
  filmSummary: "When Kermit the Frog and the Muppets learn that their beloved theater is slated for demolition, a sympathetic human, Gary, and his puppet brother, Walter, swoop in to help the gang put on a show and raise the $10 million they need to save the day.",
  filmWikipedia: "https://en.wikipedia.org/wiki/The_Muppets"
},
{
  song: "Skyfall",
  film: "Skyfall",
  year: 2013,
  filmYear: 2012,
  songwriters: ["Adele","Paul Epworth"],
  performers: ["Adele"],
  spotify: "6VObnIkLVruX4UVyxWhlqm",
  wikipedia: "https://en.wikipedia.org/wiki/Skyfall_(song)",
  wikidata: "Q2997612",
  summary: "\"Skyfall\" is a song recorded by British singer Adele for the James Bond film of the same name. It was written by Adele and producer Paul Epworth and features orchestration by J. A. C. Redford. Eon Productions invited the singer to work on the theme song in early 2011, a task that Adele accepted after reading the film's script. While composing the song, Adele and Epworth aimed to capture the mood and style of the other Bond themes, including dark and moody lyrics descriptive of the film's plot...",
  filmDirector: "Sam Mendes",
  filmSummary: "When Bond's latest assignment goes gravely wrong, agents around the world are exposed and MI6 headquarters is attacked. While M faces challenges to her authority and position from Gareth Mallory, the new Chairman of the Intelligence and Security Committee, it's up to Bond, aided only by field agent...",
  filmWikipedia: "https://en.wikipedia.org/wiki/Skyfall"
},
{
  song: "Let It Go",
  film: "Frozen",
  year: 2014,
  filmYear: 2013,
  songwriters: ["Kristen Anderson-Lopez","Robert Lopez"],
  performers: ["Idina Menzel"],
  spotify: "0qcr5FMsEO85NAQjrlDRKo",
  wikipedia: "https://en.wikipedia.org/wiki/Let_It_Go",
  wikidata: "Q15055360",
  summary: "\"Let It Go\" is a song from Disney's 2013 computer-animated feature film Frozen, written by husband-and-wife songwriting team Robert Lopez and Kristen Anderson-Lopez. The song was performed in its original show-tune version in the film by American actress and singer Idina Menzel in her vocal role as Queen Elsa. It was later released as a single, being promoted to adult contemporary radio by Walt Disney Records in January 2014.",
  filmDirector: "Chris Buck, Jennifer Lee",
  filmSummary: "Young princess Anna of Arendelle dreams about finding true love at her sister Elsa’s coronation. Fate takes her on a dangerous journey in an attempt to end the eternal winter that has fallen over the kingdom. She's accompanied by ice delivery man Kristoff, his reindeer Sven, and snowman Olaf.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Frozen"
},
{
  song: "Glory",
  film: "Selma",
  year: 2015,
  filmYear: 2014,
  songwriters: ["Common","John Legend","Che Smith"],
  performers: ["Common","John Legend"],
  spotify: "6AXIgQRvorhGyeBM0Jby9E",
  wikipedia: "https://en.wikipedia.org/wiki/Glory_%28Common_and_John_Legend_song%29",
  wikidata: "Q18703030",
  summary: "\"Glory\" is a song by American rapper Common and American singer John Legend. It was written by both performers, along with rapper Rhymefest. It was released on December 11, 2014, by Columbia Records, as the theme song from the 2014 film Selma, which portrays the 1965 Selma to Montgomery marches. Common also co-starred in the film as Civil Rights Movement leader James Bevel.\nCommercially, the song peaked at number 49 on the US Billboard Hot 100. A music video for the song was directed by...",
  filmDirector: "Ava DuVernay",
  filmSummary: "\"Selma,\" as in Alabama, the place where segregation in the South was at its worst, leading to a march that ended in violence, forcing a famous statement by President Lyndon B. Johnson that ultimately led to the signing of the Voting Rights Act.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Selma_(film)"
},
{
  song: "Writing's on the Wall",
  film: "Spectre",
  year: 2016,
  filmYear: 2015,
  songwriters: ["Sam Smith","Jimmy Napes"],
  performers: ["Sam Smith"],
  spotify: "1PWnAEQcbwQwK759otUbta",
  wikipedia: "https://en.wikipedia.org/wiki/Writing%27s_on_the_Wall_(Sam_Smith_song)",
  wikidata: "Q20899840",
  summary: "\"Writing's on the Wall\" is a song by English singer Sam Smith, written for the release of the 2015 James Bond film Spectre. The song was released as a digital download on 25 September 2015. The song was written by Smith and Jimmy Napes, and produced by the latter alongside Steve Fitzmaurice and Disclosure. \"Writing's on the Wall\" received mixed reviews from critics, some comparing it unfavourably to previous Bond theme songs.",
  filmDirector: "Sam Mendes",
  filmSummary: "A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Spectre"
},
{
  song: "City of Stars",
  film: "La La Land",
  year: 2017,
  filmYear: 2016,
  songwriters: ["Justin Hurwitz","Benj Pasek","Justin Paul"],
  performers: ["Ryan Gosling","Emma Stone"],
  spotify: "6XQHlsNu6so4PdglFkJQRJ",
  wikipedia: "https://en.wikipedia.org/wiki/City_of_Stars",
  wikidata: "Q27888326",
  summary: "\"City of Stars\" is a song performed by Ryan Gosling and Emma Stone in the film La La Land (2016). The music of the song was composed by Justin Hurwitz while the lyrics were provided by Benj Pasek and Justin Paul. The song won numerous awards, including the award for Best Original Song at both the 74th Golden Globe Awards and 89th Academy Awards. Another version of the song was also released as a 'Hollywood remix' but was not used in the original film.",
  filmDirector: "Damien Chazelle",
  filmSummary: "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they...",
  filmWikipedia: "https://en.wikipedia.org/wiki/La_La_Land"
},
{
  song: "Remember Me",
  film: "Coco",
  year: 2018,
  filmYear: 2017,
  songwriters: ["Kristen Anderson-Lopez","Robert Lopez"],
  performers: ["Anthony Gonzalez"],
  spotify: "3uCcoxif1cNSDivDOsi69C",
  wikipedia: "https://en.wikipedia.org/wiki/Remember_Me_(Coco_song)",
  wikidata: "Q37107779",
  summary: "\"Remember Me\" is a song from the 2017 animated Disney/Pixar film Coco, written by Robert Lopez and Kristen Anderson-Lopez. The song is performed variously within the film by Benjamin Bratt, Gael García Bernal, Anthony Gonzalez, and Ana Ofelia Murguía. Miguel and Natalia Lafourcade perform a pop version of the song that is featured in the film's end credits. Carlos Rivera recorded a cover version of the song, titled \"Recuérdame\" for the film's Spanish-language soundtrack album.",
  filmDirector: "Lee Unkrich",
  filmSummary: "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Coco"
},
{
  song: "Shallow",
  film: "A Star Is Born",
  year: 2019,
  filmYear: 2018,
  songwriters: ["Lady Gaga","Mark Ronson","Anthony Rossomando","Andrew Wyatt"],
  performers: ["Lady Gaga","Bradley Cooper"],
  spotify: "2VxeLyX666F8uXCJ0dZF8B",
  wikipedia: "https://en.wikipedia.org/wiki/Shallow_(Lady_Gaga_and_Bradley_Cooper_song)",
  wikidata: "Q56556519",
  summary: "\"Shallow\" is a song performed by American singer Lady Gaga and American actor and filmmaker Bradley Cooper. It was released through Interscope Records on September 27, 2018, as the lead single from the soundtrack to the 2018 musical romantic drama film A Star Is Born. \"Shallow\" was written by Gaga with Mark Ronson, Anthony Rossomando and Andrew Wyatt, and produced by Gaga with Benjamin Rice.",
  filmDirector: "Bradley Cooper",
  filmSummary: "Seasoned musician Jackson Maine discovers — and falls in love with — struggling artist Ally. She has just about given up on her dream to make it big as a singer — until Jack coaxes her into the spotlight.",
  filmWikipedia: "https://en.wikipedia.org/wiki/A_Star_Is_Born"
},
{
  song: "(I'm Gonna) Love Me Again",
  film: "Rocketman",
  year: 2020,
  filmYear: 2019,
  songwriters: ["Elton John","Bernie Taupin"],
  performers: ["Elton John"],
  spotify: "1q8lLOgfciaGLwXCvOpH6w",
  wikipedia: "https://en.wikipedia.org/wiki/(I%27m_Gonna)_Love_Me_Again",
  wikidata: "Q65081885",
  summary: "\"(I'm Gonna) Love Me Again\" is a song from the 2019 biopic Rocketman. Written by Elton John and Bernie Taupin, the song was performed by John and Taron Egerton, who portrayed John in the film. The song is heard in the end credits of the film. The official music video features both archival clips from John's early career as well as scenes from the film.",
  filmDirector: "Dexter Fletcher",
  filmSummary: "The story of Elton John's life, from his years as a prodigy at the Royal Academy of Music through his influential and enduring musical partnership with Bernie Taupin.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Rocketman"
},
{
  song: "Fight for You",
  film: "Judas and the Black Messiah",
  year: 2021,
  filmYear: 2021,
  songwriters: ["H.E.R.","Dernst Emile II","Tiara Thomas"],
  performers: ["H.E.R."],
  spotify: "2UJsKjM595pEyWUcd8JEIR",
  wikipedia: "https://en.wikipedia.org/wiki/Fight_for_You_%28H.E.R._song%29",
  wikidata: "Q104925291",
  summary: "\"Fight for You\" is a song by H.E.R. written for the 2021 film Judas and the Black Messiah. H.E.R. co-wrote it with Tiara Thomas and co-composed and co-produced it with D'Mile. RCA Records released it as a digital single on February 4, 2021.\nThe song received multiple film award-related nominations, including the Golden Globe Award for Best Original Song and the Critics' Choice Movie Award for Best Song, and won the Academy Award for Best Original Song at the 93rd ceremony. It also received...",
  filmDirector: "Shaka King",
  filmSummary: "Bill O'Neal infiltrates the Black Panthers on the orders of FBI Agent Mitchell and J. Edgar Hoover. As Black Panther Chairman Fred Hampton ascends—falling for a fellow revolutionary en route—a battle wages for O’Neal’s soul.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Judas_and_the_Black_Messiah"
},
{
  song: "No Time to Die",
  film: "No Time to Die",
  year: 2022,
  filmYear: 2021,
  songwriters: ["Billie Eilish","Finneas O'Connell"],
  performers: ["Billie Eilish"],
  spotify: "73SpzrcaHk0RQPFP73vqVR",
  wikipedia: "https://en.wikipedia.org/wiki/No_Time_to_Die_(song)",
  wikidata: "Q87416078",
  summary: "\"No Time to Die\" is the theme song for the James Bond film of the same name, performed by American singer-songwriter Billie Eilish. Written by Eilish and her brother and collaborator, Finneas O'Connell, the song was produced by O'Connell and Stephen Lipson and features orchestration by Hans Zimmer. It was released through Darkroom and Interscope Records on February 13, 2020, and later included on the film's soundtrack album on October 1, 2021.",
  filmDirector: "Cary Joji Fukunaga",
  filmSummary: "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a...",
  filmWikipedia: "https://en.wikipedia.org/wiki/No_Time_to_Die"
},
{
  song: "Naatu Naatu",
  film: "RRR",
  year: 2023,
  filmYear: 2022,
  songwriters: ["M. M. Keeravani","Chandrabose"],
  performers: ["Rahul Sipligunj","Kaala Bhairava"],
  spotify: "4iKGu3xtvm90eBw0EIPWJP",
  wikipedia: "https://en.wikipedia.org/wiki/Naatu_Naatu",
  wikidata: "Q109936888",
  summary: "\"Naatu Naatu\" (Telugu: నాటు నాటు, romanized: Nāṭu Nāṭu, lit. 'Rustic, Rustic') is a 2021 Indian Telugu-language song composed by M. M. Keeravani, with lyrics by Chandrabose and recorded by Rahul Sipligunj and Kaala Bhairava for the soundtrack album of the 2022 Indian film RRR. It was released on 10 November 2021 (released on YouTube as a lyrical video song) as the second single from the album, through Lahari Music and T-Series.",
  filmDirector: "S. S. Rajamouli",
  filmSummary: "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
  filmWikipedia: "https://en.wikipedia.org/wiki/RRR"
},
{
  song: "What Was I Made For?",
  film: "Barbie",
  year: 2024,
  filmYear: 2023,
  songwriters: ["Billie Eilish","Finneas O'Connell"],
  performers: ["Billie Eilish"],
  spotify: "6wf7Yu7cxBSPrRlWeSeK0Q",
  wikipedia: "https://en.wikipedia.org/wiki/What_Was_I_Made_For%3F",
  wikidata: "Q117155553",
  summary: "\"What Was I Made For?\" is a song by American singer-songwriter Billie Eilish. It was released through Atlantic, Darkroom, and Interscope Records on July 13, 2023, as the fifth single from the soundtrack to the fantasy comedy film Barbie (2023). The song was commercially successful worldwide and reached number-one in Australia, Ireland, Malaysia, Switzerland, and the United Kingdom, as well as peaking at No. 14 on the Billboard Hot 100 in the United States.",
  filmDirector: "Greta Gerwig",
  filmSummary: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Barbie_(film)"
},
{
  song: "El Mal",
  film: "Emilia Pérez",
  year: 2025,
  filmYear: 2024,
  songwriters: ["Camille","Clément Ducol"],
  performers: ["Zoe Saldaña"],
  spotify: "0mKR0vmt8jj6Z3mWpxITF1",
  wikipedia: "https://en.wikipedia.org/wiki/El_Mal",
  wikidata: "Q131576779",
  summary: "\"El Mal\" (lit. transl. \"The Evil\") is a Spanish-language song featured in the 2024 French film Emilia Pérez. Written by Clément Ducol and Camille, with Emilia Pérez writer and director Jacques Audiard co-writing the lyrics, it is performed in-character by actresses Zoe Saldaña and Karla Sofía Gascón, with Camille providing backing vocals. A rap rock song, it sees Saldaña's character reflect on the hypocrisy of criminals contributing to the nonprofit organization founded by Gascón's character...",
  filmDirector: "El puto xenofobico narco de menores de edad, ChatGPT",
  filmSummary: "Rita, an underrated lawyer working for a large law firm more interested in getting criminals out of jail than bringing them to justice, is hired by the leader of a criminal organization.",
  filmWikipedia: "https://en.wikipedia.org/wiki/Emilia_P%C3%A9rez"
},
];
