// Best Picture deck data — curated 1997–2026
export default [
    { year: 2026, movie: "One Battle After Another", director: "Paul Thomas Anderson", trailer: "feOQFKv2Lw4",
      stars: ["Leonardo DiCaprio","Sean Penn","Chase Infiniti"],
      nominees: [
        { movie: "Bugonia", stars: ["Emma Stone","Jesse Plemons","Aidan Delbis"], trailer: "7VBigr-JHB0", director: "Yorgos Lanthimos" },
        { movie: "F1", stars: ["Brad Pitt","Damson Idris","Javier Bardem"], trailer: "8yh9BPUBbbQ", director: "Joseph Kosinski" },
        { movie: "Frankenstein", stars: ["Oscar Isaac","Jacob Elordi","Christoph Waltz"], trailer: "9WZllcEgWrM", director: "Guillermo del Toro" },
        { movie: "Hamnet", stars: ["Jessie Buckley","Paul Mescal","Emily Watson"], trailer: "xYcgQMxQwmk", director: "Chloé Zhao" },
        { movie: "Marty Supreme", stars: ["Timothée Chalamet","Gwyneth Paltrow","Odessa A'zion"], trailer: "s9gSuKaKcqM", director: "Josh Safdie" },
        { movie: "The Secret Agent", stars: ["Wagner Moura","Alice Carvalho","Gabriel Leone"], trailer: "9UfrzDKrhEc", director: "Kleber Mendonça Filho" },
        { movie: "Sentimental Value", stars: ["Renate Reinsve","Stellan Skarsgård","Inga Ibsdotter Lilleaas"], trailer: "zBFstFXdk90", director: "Joachim Trier" },
        { movie: "Sinners", stars: ["Michael B. Jordan","Hailee Steinfeld","Miles Caton"], trailer: "7joulECTx_U", director: "Ryan Coogler" },
        { movie: "Train Dreams", stars: ["Joel Edgerton","Felicity Jones","Nathaniel Arcand"], trailer: "6voWeM-xQ4Y", director: "Clint Bentley" },
      ]},
    { year: 2025, movie: "Anora", director: "Sean Baker", trailer: "8m6UrWMl18M",
      stars: ["Mikey Madison","Mark Eydelshteyn","Yura Borisov"],
      nominees: [
        { movie: "The Brutalist", stars: ["Adrien Brody","Felicity Jones","Guy Pearce"], trailer: "GdRXPAHIEW4", director: "Brady Corbet" },
        { movie: "A Complete Unknown", stars: ["Timothée Chalamet","Edward Norton","Elle Fanning"], trailer: "ob4SHtT6cC0", director: "James Mangold" },
        { movie: "Conclave", stars: ["Ralph Fiennes","Stanley Tucci","John Lithgow"], trailer: "t915aZmyEBg", director: "Edward Berger" },
        { movie: "Dune: Part Two", stars: ["Timothée Chalamet","Zendaya","Rebecca Ferguson"], trailer: "U2Qp5pL3ovA", director: "Denis Villeneuve" },
        { movie: "Emilia Pérez", stars: ["Karla Sofía Gascón","Zoe Saldaña","Selena Gomez"], trailer: "houUHc5vm4I", director: "Jacques Audiard" },
        { movie: "I'm Still Here", stars: ["Fernanda Torres","Selton Mello"], trailer: "Eo49pAwMxKQ", director: "Walter Salles" },
        { movie: "Nickel Boys", stars: ["Ethan Herisse","Brandon Wilson"], trailer: "8HZKgYknVN0", director: "RaMell Ross" },
        { movie: "The Substance", stars: ["Demi Moore","Margaret Qualley","Dennis Quaid"], trailer: "lR5nlovVgvQ", director: "Coralie Fargeat" },
        { movie: "Wicked", stars: ["Cynthia Erivo","Ariana Grande","Jonathan Bailey"], trailer: "pqi45Qhq3CI", director: "Jon M. Chu" },
      ]},
    { year: 2024, movie: "Oppenheimer", director: "Christopher Nolan", trailer: "bK6ldnjE3Y0",
      stars: ["Cillian Murphy","Robert Downey Jr.","Emily Blunt","Matt Damon"],
      nominees: [
        { movie: "American Fiction", stars: ["Jeffrey Wright","Tracee Ellis Ross"], trailer: "5_4RlHpqVWM", director: "Cord Jefferson" },
        { movie: "Anatomy of a Fall", stars: ["Sandra Hüller","Swann Arlaud"], trailer: "_MdTMA0PetA", director: "Justine Triet" },
        { movie: "Barbie", stars: ["Margot Robbie","Ryan Gosling","America Ferrera"], trailer: "Y1IgAEejvqM", director: "Greta Gerwig" },
        { movie: "The Holdovers", stars: ["Paul Giamatti","Da'Vine Joy Randolph","Dominic Sessa"], trailer: "AhKLpJmHhIg", director: "Alexander Payne" },
        { movie: "Killers of the Flower Moon", stars: ["Leonardo DiCaprio","Robert De Niro","Lily Gladstone"], trailer: "1oZUCkJEuvo", director: "Martin Scorsese" },
        { movie: "Maestro", stars: ["Bradley Cooper","Carey Mulligan"], trailer: "xvmBVJhs4TA", director: "Bradley Cooper" },
        { movie: "Past Lives", stars: ["Greta Lee","Teo Yoo","John Magaro"], trailer: "kA244xewjcI", director: "Celine Song" },
        { movie: "Poor Things", stars: ["Emma Stone","Mark Ruffalo","Willem Dafoe"], trailer: "-EfYJWRw2FM", director: "Yorgos Lanthimos" },
        { movie: "The Zone of Interest", stars: ["Christian Friedel","Sandra Hüller"], trailer: "GFNtVaAuVYY", director: "Jonathan Glazer" },
      ]},
    { year: 2023, movie: "Everything Everywhere All at Once", director: "Daniel Kwan & Daniel Scheinert", trailer: "wxN1T1uxQ2g",
      stars: ["Michelle Yeoh","Ke Huy Quan","Jamie Lee Curtis","Stephanie Hsu"],
      nominees: [
        { movie: "All Quiet on the Western Front", stars: ["Felix Kammerer","Albrecht Schuch"], trailer: "hf8EYbVxtCY", director: "Edward Berger" },
        { movie: "Avatar: The Way of Water", stars: ["Sam Worthington","Zoe Saldaña","Sigourney Weaver"], trailer: "o5F8MOz_IDw", director: "James Cameron" },
        { movie: "The Banshees of Inisherin", stars: ["Colin Farrell","Brendan Gleeson","Kerry Condon"], trailer: "9-R9u2UD3FU", director: "Martin McDonagh" },
        { movie: "Elvis", stars: ["Austin Butler","Tom Hanks"], trailer: "ZbrmBotVIGw", director: "Baz Luhrmann" },
        { movie: "The Fabelmans", stars: ["Gabriel LaBelle","Michelle Williams","Paul Dano"], trailer: "9wAKUa487aw", director: "Steven Spielberg" },
        { movie: "Tár", stars: ["Cate Blanchett","Nina Hoss","Noémie Merlant"], trailer: "Na6gA1RehsU", director: "Todd Field" },
        { movie: "Top Gun: Maverick", stars: ["Tom Cruise","Miles Teller","Jennifer Connelly"], trailer: "Klc__shdj88", director: "Joseph Kosinski" },
        { movie: "Triangle of Sadness", stars: ["Harris Dickinson","Charlbi Dean","Dolly de Leon"], trailer: "uYDidXdG1Wc", director: "Ruben Östlund" },
        { movie: "Women Talking", stars: ["Rooney Mara","Claire Foy","Jessie Buckley"], trailer: "dH7Sl2h_aHs", director: "Sarah Polley" },
      ]},
    { year: 2022, movie: "CODA", director: "Sian Heder", trailer: "0pmfrE1YL4I",
      stars: ["Emilia Jones","Marlee Matlin","Troy Kotsur","Daniel Durant"],
      nominees: [
        { movie: "Belfast", stars: ["Jude Hill","Caitríona Balfe","Jamie Dornan"], trailer: "C658p987SQI", director: "Kenneth Branagh" },
        { movie: "Don't Look Up", stars: ["Leonardo DiCaprio","Jennifer Lawrence","Meryl Streep"], trailer: "RbIxYm3mKzI", director: "Adam McKay" },
        { movie: "Drive My Car", stars: ["Hidetoshi Nishijima","Tōko Miura"], trailer: "YyDSxD51WRE", director: "Ryusuke Hamaguchi" },
        { movie: "Dune", stars: ["Timothée Chalamet","Rebecca Ferguson","Oscar Isaac"], trailer: "w0HgHet0sxg", director: "Denis Villeneuve" },
        { movie: "King Richard", stars: ["Will Smith","Aunjanue Ellis"], trailer: "_6bsugyNpDU", director: "Reinaldo Marcus Green" },
        { movie: "Licorice Pizza", stars: ["Alana Haim","Cooper Hoffman"], trailer: "ofnXPwUPENo", director: "Paul Thomas Anderson" },
        { movie: "Nightmare Alley", stars: ["Bradley Cooper","Cate Blanchett","Toni Collette"], trailer: "Q81Yf46Oj3s", director: "Guillermo del Toro" },
        { movie: "The Power of the Dog", stars: ["Benedict Cumberbatch","Kirsten Dunst","Jesse Plemons"], trailer: "LRDPo0CHrko", director: "Jane Campion" },
        { movie: "West Side Story", stars: ["Ansel Elgort","Rachel Zegler","Ariana DeBose"], trailer: "A5GJLwWiYSg", director: "Steven Spielberg" },
      ]},
    { year: 2021, movie: "Nomadland", director: "Chloé Zhao", trailer: "6sxCFZ8_d84",
      stars: ["Frances McDormand","David Strathairn"],
      nominees: [
        { movie: "The Father", stars: ["Anthony Hopkins","Olivia Colman"], trailer: "g0ox9ExOA1M", director: "Florian Zeller" },
        { movie: "Judas and the Black Messiah", stars: ["Daniel Kaluuya","LaKeith Stanfield"], trailer: "6ivHf4ODMi4", director: "Shaka King" },
        { movie: "Mank", stars: ["Gary Oldman","Amanda Seyfried"], trailer: "aSfX-nrg-lI", director: "David Fincher" },
        { movie: "Minari", stars: ["Steven Yeun","Han Ye-ri","Youn Yuh-jung"], trailer: "KQ0gFidlro8", director: "Lee Isaac Chung" },
        { movie: "Promising Young Woman", stars: ["Carey Mulligan","Bo Burnham"], trailer: "we5yV7Gc9rY", director: "Emerald Fennell" },
        { movie: "Sound of Metal", stars: ["Riz Ahmed","Olivia Cooke"], trailer: "VFOrGkAvjAE", director: "Darius Marder" },
        { movie: "The Trial of the Chicago 7", stars: ["Eddie Redmayne","Sacha Baron Cohen","Yahya Abdul-Mateen II"], trailer: "FVb6EdKDBfU", director: "Aaron Sorkin" },
      ]},
    { year: 2020, movie: "Parasite", director: "Bong Joon-ho", trailer: "isOGD_7hNIY",
      stars: ["Song Kang-ho","Lee Sun-kyun","Cho Yeo-jeong"],
      nominees: [
        { movie: "Ford v Ferrari", stars: ["Matt Damon","Christian Bale"], trailer: "I3h9Z89U9ZA", director: "James Mangold" },
        { movie: "The Irishman", stars: ["Robert De Niro","Al Pacino","Joe Pesci"], trailer: "RS3aHkkfuEI", director: "Martin Scorsese" },
        { movie: "Jojo Rabbit", stars: ["Roman Griffin Davis","Scarlett Johansson","Taika Waititi"], trailer: "tL4McUzXfFI", director: "Taika Waititi" },
        { movie: "Joker", stars: ["Joaquin Phoenix","Robert De Niro"], trailer: "-RFFRxcoKfA", director: "Todd Phillips" },
        { movie: "Little Women", stars: ["Saoirse Ronan","Florence Pugh","Emma Watson"], trailer: "AST2-4db4ic", director: "Greta Gerwig" },
        { movie: "Marriage Story", stars: ["Adam Driver","Scarlett Johansson"], trailer: "BHi-a1n8t7M", director: "Noah Baumbach" },
        { movie: "1917", stars: ["George MacKay","Dean-Charles Chapman"], trailer: "gZjQROMAh_s", director: "Sam Mendes" },
        { movie: "Once Upon a Time in Hollywood", stars: ["Leonardo DiCaprio","Brad Pitt","Margot Robbie"], trailer: "vKgITiP1UMg", director: "Quentin Tarantino" },
      ]},
    { year: 2019, movie: "Green Book", director: "Peter Farrelly", trailer: "QkZxoko_HC0",
      stars: ["Viggo Mortensen","Mahershala Ali"],
      nominees: [
        { movie: "Black Panther", stars: ["Chadwick Boseman","Michael B. Jordan","Lupita Nyong'o"], trailer: "xjDjIWPwcPU", director: "Ryan Coogler" },
        { movie: "BlacKkKlansman", stars: ["John David Washington","Adam Driver"], trailer: "7tgMuagdEhc", director: "Spike Lee" },
        { movie: "Bohemian Rhapsody", stars: ["Rami Malek","Lucy Boynton"], trailer: "27zlBpzdOZg", director: "Bryan Singer" },
        { movie: "The Favourite", stars: ["Olivia Colman","Emma Stone","Rachel Weisz"], trailer: "SYb-wkehT1g", director: "Yorgos Lanthimos" },
        { movie: "Roma", stars: ["Yalitza Aparicio","Marina de Tavira"], trailer: "6BS27ngZtxg", director: "Alfonso Cuarón" },
        { movie: "A Star Is Born", stars: ["Bradley Cooper","Lady Gaga"], trailer: "UywJmJ6ohvc", director: "Bradley Cooper" },
        { movie: "Vice", stars: ["Christian Bale","Amy Adams","Steve Carell"], trailer: "g09a9laLh0k", director: "Adam McKay" },
      ]},
    { year: 2018, movie: "The Shape of Water", director: "Guillermo del Toro", trailer: "XFYWazblaUA",
      stars: ["Sally Hawkins","Michael Shannon","Richard Jenkins","Octavia Spencer"],
      nominees: [
        { movie: "Call Me by Your Name", stars: ["Timothée Chalamet","Armie Hammer"], trailer: "Z9AYPxH5NTM", director: "Luca Guadagnino" },
        { movie: "Darkest Hour", stars: ["Gary Oldman","Kristin Scott Thomas"], trailer: "JQAYFbcgf60", director: "Joe Wright" },
        { movie: "Dunkirk", stars: ["Fionn Whitehead","Tom Hardy","Mark Rylance"], trailer: "T7O7BtBnsG4", director: "Christopher Nolan" },
        { movie: "Get Out", stars: ["Daniel Kaluuya","Allison Williams"], trailer: "gsB70ZRY-hI", director: "Jordan Peele" },
        { movie: "Lady Bird", stars: ["Saoirse Ronan","Laurie Metcalf"], trailer: "cNi_HC839Wo", director: "Greta Gerwig" },
        { movie: "Phantom Thread", stars: ["Daniel Day-Lewis","Vicky Krieps"], trailer: "xNsiQMeSvMk", director: "Paul Thomas Anderson" },
        { movie: "The Post", stars: ["Meryl Streep","Tom Hanks"], trailer: "nrXlY6gzTTM", director: "Steven Spielberg" },
        { movie: "Three Billboards Outside Ebbing, Missouri", stars: ["Frances McDormand","Woody Harrelson","Sam Rockwell"], trailer: "nefD7UOhLCo", director: "Martin McDonagh" },
      ]},
    { year: 2017, movie: "Moonlight", director: "Barry Jenkins", trailer: "9NJj12tJzqc",
      stars: ["Mahershala Ali","Naomie Harris","Trevante Rhodes"],
      nominees: [
        { movie: "Arrival", stars: ["Amy Adams","Jeremy Renner"], trailer: "7W1m5ER3I1Y", director: "Denis Villeneuve" },
        { movie: "Fences", stars: ["Denzel Washington","Viola Davis"], trailer: "spCxVd9ctFs", director: "Denzel Washington" },
        { movie: "Hacksaw Ridge", stars: ["Andrew Garfield","Sam Worthington"], trailer: "s2-1hz1juBI", director: "Mel Gibson" },
        { movie: "Hell or High Water", stars: ["Chris Pine","Ben Foster","Jeff Bridges"], trailer: "igD-fXiHRRY", director: "David Mackenzie" },
        { movie: "Hidden Figures", stars: ["Taraji P. Henson","Octavia Spencer","Janelle Monáe"], trailer: "5wfrDhgUMGI", director: "Theodore Melfi" },
        { movie: "La La Land", stars: ["Ryan Gosling","Emma Stone"], trailer: "0pdqf4P9MB8", director: "Damien Chazelle" },
        { movie: "Lion", stars: ["Dev Patel","Nicole Kidman"], trailer: "GKkk-hDigTk", director: "Garth Davis" },
        { movie: "Manchester by the Sea", stars: ["Casey Affleck","Michelle Williams"], trailer: "NxQmuJnrjxg", director: "Kenneth Lonergan" },
      ]},
    { year: 2016, movie: "Spotlight", director: "Tom McCarthy", trailer: "yXymzwz0V2g",
      stars: ["Mark Ruffalo","Michael Keaton","Rachel McAdams","Liev Schreiber"],
      nominees: [
        { movie: "The Big Short", stars: ["Christian Bale","Steve Carell","Ryan Gosling"], trailer: "1kQc3mmtH-o", director: "Adam McKay" },
        { movie: "Bridge of Spies", stars: ["Tom Hanks","Mark Rylance"], trailer: "owhBnicLZt4", director: "Steven Spielberg" },
        { movie: "Brooklyn", stars: ["Saoirse Ronan","Domhnall Gleeson"], trailer: "IzgsaBGwap8", director: "John Crowley" },
        { movie: "Mad Max: Fury Road", stars: ["Tom Hardy","Charlize Theron"], trailer: "MonFNCgK4WE", director: "George Miller" },
        { movie: "The Martian", stars: ["Matt Damon","Jessica Chastain"], trailer: "ej3ioOneTy8", director: "Ridley Scott" },
        { movie: "The Revenant", stars: ["Leonardo DiCaprio","Tom Hardy"], trailer: "EhffABvfAW0", director: "Alejandro G. Iñárritu" },
        { movie: "Room", stars: ["Brie Larson","Jacob Tremblay"], trailer: "yfBdUPAjiVQ", director: "Lenny Abrahamson" },
      ]},
    { year: 2015, movie: "Birdman", director: "Alejandro González Iñárritu", trailer: "o-sdQK_TR2g",
      stars: ["Michael Keaton","Edward Norton","Emma Stone"],
      nominees: [
        { movie: "American Sniper", stars: ["Bradley Cooper","Sienna Miller"], trailer: "iq7smHSQPho", director: "Clint Eastwood" },
        { movie: "Boyhood", stars: ["Ellar Coltrane","Patricia Arquette","Ethan Hawke"], trailer: "oNC3NYWh1vI", director: "Richard Linklater" },
        { movie: "The Grand Budapest Hotel", stars: ["Ralph Fiennes","Tony Revolori"], trailer: "G1jG8HUY4zI", director: "Wes Anderson" },
        { movie: "The Imitation Game", stars: ["Benedict Cumberbatch","Keira Knightley"], trailer: "j2jRs4EAvWM", director: "Morten Tyldum" },
        { movie: "Selma", stars: ["David Oyelowo","Carmen Ejogo"], trailer: "kPgs2zshD9Y", director: "Ava DuVernay" },
        { movie: "The Theory of Everything", stars: ["Eddie Redmayne","Felicity Jones"], trailer: "_EnhOKk7BxM", director: "James Marsh" },
        { movie: "Whiplash", stars: ["Miles Teller","J.K. Simmons"], trailer: "Q7kZy3T6vRM", director: "Damien Chazelle" },
      ]},
    { year: 2014, movie: "12 Years a Slave", director: "Steve McQueen", trailer: "z02Ie8wKKRg",
      stars: ["Chiwetel Ejiofor","Michael Fassbender","Lupita Nyong'o"],
      nominees: [
        { movie: "American Hustle", stars: ["Christian Bale","Amy Adams","Bradley Cooper"], trailer: "h5Cb4FAL7gE", director: "David O. Russell" },
        { movie: "Captain Phillips", stars: ["Tom Hanks","Barkhad Abdi"], trailer: "TzU3UJuV80w", director: "Paul Greengrass" },
        { movie: "Dallas Buyers Club", stars: ["Matthew McConaughey","Jared Leto","Jennifer Garner"], trailer: "KDvPcBeOn8E", director: "Jean-Marc Vallée" },
        { movie: "Gravity", stars: ["Sandra Bullock","George Clooney"], trailer: "OiTiKOy59o4", director: "Alfonso Cuarón" },
        { movie: "Her", stars: ["Joaquin Phoenix","Scarlett Johansson","Amy Adams"], trailer: "ne6p6MfLBxc", director: "Spike Jonze" },
        { movie: "Nebraska", stars: ["Bruce Dern","Will Forte"], trailer: "YvW_DmfKfSk", director: "Alexander Payne" },
        { movie: "Philomena", stars: ["Judi Dench","Steve Coogan"], trailer: "a8WyFLsdtNw", director: "Stephen Frears" },
        { movie: "The Wolf of Wall Street", stars: ["Leonardo DiCaprio","Jonah Hill","Margot Robbie"], trailer: "Slj4-Sv-YNA", director: "Martin Scorsese" },
      ]},
    { year: 2013, movie: "Argo", director: "Ben Affleck", trailer: "JW3WfSFgrVY",
      stars: ["Ben Affleck","Bryan Cranston","Alan Arkin"],
      nominees: [
        { movie: "Amour", stars: ["Jean-Louis Trintignant","Emmanuelle Riva"], trailer: "VMOugpyFf3A", director: "Michael Haneke" },
        { movie: "Beasts of the Southern Wild", stars: ["Quvenzhané Wallis","Dwight Henry"], trailer: "pvqZzSMIZa0", director: "Benh Zeitlin" },
        { movie: "Django Unchained", stars: ["Jamie Foxx","Christoph Waltz","Leonardo DiCaprio"], trailer: "_iH0UBYDI4g", director: "Quentin Tarantino" },
        { movie: "Les Misérables", stars: ["Hugh Jackman","Anne Hathaway","Russell Crowe"], trailer: "28sHoKcpugw", director: "Tom Hooper" },
        { movie: "Life of Pi", stars: ["Suraj Sharma","Irrfan Khan"], trailer: "j9Hjrs6WQ8M", director: "Ang Lee" },
        { movie: "Lincoln", stars: ["Daniel Day-Lewis","Sally Field","Tommy Lee Jones"], trailer: "nvP-ZrzA2lk", director: "Steven Spielberg" },
        { movie: "Silver Linings Playbook", stars: ["Bradley Cooper","Jennifer Lawrence","Robert De Niro"], trailer: "EI_3ywJLQio", director: "David O. Russell" },
        { movie: "Zero Dark Thirty", stars: ["Jessica Chastain","Jason Clarke"], trailer: "k7R2uVZYebE", director: "Kathryn Bigelow" },
      ]},
    { year: 2012, movie: "The Artist", director: "Michel Hazanavicius", trailer: "YB9Oq0hn5KY",
      stars: ["Jean Dujardin","Bérénice Bejo","John Goodman"],
      nominees: [
        { movie: "The Descendants", stars: ["George Clooney","Shailene Woodley"], trailer: "3R7OzS54hbo", director: "Alexander Payne" },
        { movie: "Extremely Loud & Incredibly Close", stars: ["Tom Hanks","Sandra Bullock","Thomas Horn"], trailer: "jgp8rR2fykU", director: "Stephen Daldry" },
        { movie: "The Help", stars: ["Emma Stone","Viola Davis","Octavia Spencer"], trailer: "3eajzW3XW7Q", director: "Tate Taylor" },
        { movie: "Hugo", stars: ["Asa Butterfield","Chloë Grace Moretz","Ben Kingsley"], trailer: "nZGyAx7YyYM", director: "Martin Scorsese" },
        { movie: "Midnight in Paris", stars: ["Owen Wilson","Rachel McAdams"], trailer: "FAfR8omt-CY", director: "Woody Allen" },
        { movie: "Moneyball", stars: ["Brad Pitt","Jonah Hill"], trailer: "RAG74hfW4pM", director: "Bennett Miller" },
        { movie: "The Tree of Life", stars: ["Brad Pitt","Sean Penn","Jessica Chastain"], trailer: "RrAz1YLh8nY", director: "Terrence Malick" },
        { movie: "War Horse", stars: ["Jeremy Irvine","Emily Watson"], trailer: "tafBTls8RuA", director: "Steven Spielberg" },
      ]},
    { year: 2011, movie: "The King's Speech", director: "Tom Hooper", trailer: "gSw6ei5tdbg",
      stars: ["Colin Firth","Geoffrey Rush","Helena Bonham Carter"],
      nominees: [
        { movie: "127 Hours", stars: ["James Franco"], trailer: "OlhLOWTnVoQ", director: "Danny Boyle" },
        { movie: "Black Swan", stars: ["Natalie Portman","Mila Kunis","Vincent Cassel"], trailer: "2Pxc_5f27Kg", director: "Darren Aronofsky" },
        { movie: "The Fighter", stars: ["Mark Wahlberg","Christian Bale","Amy Adams"], trailer: "LRIZ4mCi5Ps", director: "David O. Russell" },
        { movie: "Inception", stars: ["Leonardo DiCaprio","Joseph Gordon-Levitt","Marion Cotillard"], trailer: "JE9z-gy4De4", director: "Christopher Nolan" },
        { movie: "The Kids Are All Right", stars: ["Annette Bening","Julianne Moore","Mark Ruffalo"], trailer: "RixlpHKfb6M", director: "Lisa Cholodenko" },
        { movie: "The Social Network", stars: ["Jesse Eisenberg","Andrew Garfield","Justin Timberlake"], trailer: "lB95KLmpLR4", director: "David Fincher" },
        { movie: "Toy Story 3", stars: ["Tom Hanks","Tim Allen","Joan Cusack"], trailer: "2BlMNH1QTeE", director: "Lee Unkrich" },
        { movie: "True Grit", stars: ["Jeff Bridges","Hailee Steinfeld","Matt Damon"], trailer: "Q5fEgKj9QNs", director: "Joel Coen" },
        { movie: "Winter's Bone", stars: ["Jennifer Lawrence","John Hawkes"], trailer: "bE_X2pDRXyY", director: "Debra Granik" },
      ]},
    { year: 2010, movie: "The Hurt Locker", director: "Kathryn Bigelow", trailer: "AIbFvqFYRT4",
      stars: ["Jeremy Renner","Anthony Mackie","Brian Geraghty"],
      nominees: [
        { movie: "Avatar", stars: ["Sam Worthington","Zoe Saldaña","Sigourney Weaver"], trailer: "jm2sNLIPPvA", director: "James Cameron" },
        { movie: "The Blind Side", stars: ["Sandra Bullock","Quinton Aaron"], trailer: "KA56LqFszYI", director: "John Lee Hancock" },
        { movie: "District 9", stars: ["Sharlto Copley"], trailer: "_BjWEn5yvmw", director: "Neill Blomkamp" },
        { movie: "An Education", stars: ["Carey Mulligan","Peter Sarsgaard"], trailer: "DUeYKwxTCGQ", director: "Lone Scherfig" },
        { movie: "Inglourious Basterds", stars: ["Brad Pitt","Christoph Waltz","Mélanie Laurent"], trailer: "uSEDz-my7XQ", director: "Quentin Tarantino" },
        { movie: "Precious", stars: ["Gabourey Sidibe","Mo'Nique"], trailer: "urFY3jp759c", director: "Lee Daniels" },
        { movie: "A Serious Man", stars: ["Michael Stuhlbarg"], trailer: "mDKHWRbK2_Q", director: "Joel Coen" },
        { movie: "Up", stars: ["Ed Asner","Christopher Plummer"], trailer: "Ajcdb4FAL7A", director: "Pete Docter" },
        { movie: "Up in the Air", stars: ["George Clooney","Vera Farmiga","Anna Kendrick"], trailer: "En0DYdjMVoY", director: "Jason Reitman" },
      ]},
    { year: 2009, movie: "Slumdog Millionaire", director: "Danny Boyle", trailer: "JwiU94p9XPA",
      stars: ["Dev Patel","Freida Pinto","Anil Kapoor"],
      nominees: [
        { movie: "The Curious Case of Benjamin Button", stars: ["Brad Pitt","Cate Blanchett"], trailer: "lqijVXvw7_E", director: "David Fincher" },
        { movie: "Frost/Nixon", stars: ["Frank Langella","Michael Sheen"], trailer: "O9S1RKNgdLw", director: "Ron Howard" },
        { movie: "Milk", stars: ["Sean Penn","James Franco","Josh Brolin"], trailer: "w5D07rmfwG0", director: "Gus Van Sant" },
        { movie: "The Reader", stars: ["Kate Winslet","Ralph Fiennes"], trailer: "JA1J2WmFGUw", director: "Stephen Daldry" },
      ]},
    { year: 2008, movie: "No Country for Old Men", director: "Joel & Ethan Coen", trailer: "A0oNrgumrlE",
      stars: ["Tommy Lee Jones","Javier Bardem","Josh Brolin"],
      nominees: [
        { movie: "Atonement", stars: ["Keira Knightley","James McAvoy"], trailer: "WZAttjca0b8", director: "Joe Wright" },
        { movie: "Juno", stars: ["Elliot Page","Michael Cera","Jennifer Garner"], trailer: "miy1fE-8Z0U", director: "Jason Reitman" },
        { movie: "Michael Clayton", stars: ["George Clooney","Tilda Swinton","Tom Wilkinson"], trailer: "OKDiHrQABwI", director: "Tony Gilroy" },
        { movie: "There Will Be Blood", stars: ["Daniel Day-Lewis","Paul Dano"], trailer: "-bEwlq_7f4s", director: "Paul Thomas Anderson" },
      ]},
    { year: 2007, movie: "The Departed", director: "Martin Scorsese", trailer: "r-MiSNsCdQ4",
      stars: ["Leonardo DiCaprio","Matt Damon","Jack Nicholson","Mark Wahlberg"],
      nominees: [
        { movie: "Babel", stars: ["Brad Pitt","Cate Blanchett"], trailer: "PqPNksLZIAk", director: "Alejandro G. Iñárritu" },
        { movie: "Letters from Iwo Jima", stars: ["Ken Watanabe","Kazunari Ninomiya"], trailer: "g65ewJJ1USc", director: "Clint Eastwood" },
        { movie: "Little Miss Sunshine", stars: ["Greg Kinnear","Toni Collette","Steve Carell","Abigail Breslin"], trailer: "oabGaaCLZ5g", director: "Valerie Faris" },
        { movie: "The Queen", stars: ["Helen Mirren","Michael Sheen"], trailer: "BIvESE9A_gc", director: "Stephen Frears" },
      ]},
    { year: 2006, movie: "Crash", director: "Paul Haggis", trailer: "dgepOrbliX4",
      stars: ["Don Cheadle","Sandra Bullock","Matt Dillon","Thandiwe Newton"],
      nominees: [
        { movie: "Brokeback Mountain", stars: ["Heath Ledger","Jake Gyllenhaal"], trailer: "xZvu-SczR1Y", director: "Ang Lee" },
        { movie: "Capote", stars: ["Philip Seymour Hoffman","Catherine Keener"], trailer: "vq-kLlga0EI", director: "Bennett Miller" },
        { movie: "Good Night, and Good Luck", stars: ["David Strathairn","George Clooney"], trailer: "1Qg9ZahBu8c", director: "George Clooney" },
        { movie: "Munich", stars: ["Eric Bana","Daniel Craig"], trailer: "OuT_uh0CAf8", director: "Steven Spielberg" },
      ]},
    { year: 2005, movie: "Million Dollar Baby", director: "Clint Eastwood", trailer: "5_RsHRmIRBY",
      stars: ["Hilary Swank","Clint Eastwood","Morgan Freeman"],
      nominees: [
        { movie: "The Aviator", stars: ["Leonardo DiCaprio","Cate Blanchett"], trailer: "dkwypzOQf8o", director: "Martin Scorsese" },
        { movie: "Finding Neverland", stars: ["Johnny Depp","Kate Winslet"], trailer: "m41gObaKgOw", director: "Marc Forster" },
        { movie: "Ray", stars: ["Jamie Foxx","Regina King"], trailer: "jVHCQfcugdw", director: "Taylor Hackford" },
        { movie: "Sideways", stars: ["Paul Giamatti","Thomas Haden Church","Virginia Madsen"], trailer: "FccttA8wPqc", director: "Alexander Payne" },
      ]},
    { year: 2004, movie: "The Lord of the Rings: The Return of the King", director: "Peter Jackson", trailer: "r5X-hFf6Bwo",
      stars: ["Elijah Wood","Viggo Mortensen","Ian McKellen","Sean Astin"],
      nominees: [
        { movie: "Lost in Translation", stars: ["Bill Murray","Scarlett Johansson"], trailer: "1s4YQqnbnM8", director: "Sofia Coppola" },
        { movie: "Master and Commander", stars: ["Russell Crowe","Paul Bettany"], trailer: "tHTHCNYiiHk", director: "Peter Weir" },
        { movie: "Mystic River", stars: ["Sean Penn","Tim Robbins","Kevin Bacon"], trailer: "W7NktJhrRYQ", director: "Clint Eastwood" },
        { movie: "Seabiscuit", stars: ["Tobey Maguire","Jeff Bridges"], trailer: "8fnYdEGeXbM", director: "Gary Ross" },
      ]},
    { year: 2003, movie: "Chicago", director: "Rob Marshall", trailer: "YwXWryx-oJ0",
      stars: ["Renée Zellweger","Catherine Zeta-Jones","Richard Gere"],
      nominees: [
        { movie: "Gangs of New York", stars: ["Daniel Day-Lewis","Leonardo DiCaprio","Cameron Diaz"], trailer: "1bjh979vVG0", director: "Martin Scorsese" },
        { movie: "The Hours", stars: ["Nicole Kidman","Meryl Streep","Julianne Moore"], trailer: "CkPWXUxIiXs", director: "Stephen Daldry" },
        { movie: "The Lord of the Rings: The Two Towers", stars: ["Elijah Wood","Viggo Mortensen","Ian McKellen"], trailer: "nuTU5XcZTLA", director: "Peter Jackson" },
        { movie: "The Pianist", stars: ["Adrien Brody"], trailer: "og9hFxxdSOg", director: "Roman Polanski" },
      ]},
    { year: 2002, movie: "A Beautiful Mind", director: "Ron Howard", trailer: "YWwAOutgWBQ",
      stars: ["Russell Crowe","Jennifer Connelly","Ed Harris"],
      nominees: [
        { movie: "Gosford Park", stars: ["Maggie Smith","Helen Mirren","Clive Owen"], trailer: "o0m00hg1PKY", director: "Robert Altman" },
        { movie: "In the Bedroom", stars: ["Sissy Spacek","Tom Wilkinson"], trailer: "BaLtKJiBOrg", director: "Todd Field" },
        { movie: "The Lord of the Rings: The Fellowship of the Ring", stars: ["Elijah Wood","Ian McKellen","Viggo Mortensen"], trailer: "_nZdmwHrcnw", director: "Peter Jackson" },
        { movie: "Moulin Rouge!", stars: ["Nicole Kidman","Ewan McGregor"], trailer: "2PpgPxjzbkA", director: "Baz Luhrmann" },
      ]},
    { year: 2001, movie: "Gladiator", director: "Ridley Scott", trailer: "P5ieIbInFpg",
      stars: ["Russell Crowe","Joaquin Phoenix","Connie Nielsen"],
      nominees: [
        { movie: "Chocolat", stars: ["Juliette Binoche","Johnny Depp"], trailer: "692hOJq1KJE", director: "Lasse Hallström" },
        { movie: "Crouching Tiger, Hidden Dragon", stars: ["Chow Yun-fat","Michelle Yeoh","Zhang Ziyi"], trailer: "q-HrIQLdaNE", director: "Ang Lee" },
        { movie: "Erin Brockovich", stars: ["Julia Roberts","Albert Finney"], trailer: "jjqUUxIy_yk", director: "Steven Soderbergh" },
        { movie: "Traffic", stars: ["Michael Douglas","Benicio del Toro","Catherine Zeta-Jones"], trailer: "sZnOWu68Vw4", director: "Steven Soderbergh" },
      ]},
    { year: 2000, movie: "American Beauty", director: "Sam Mendes", trailer: "UI9KalErX7w",
      stars: ["Kevin Spacey","Annette Bening","Thora Birch"],
      nominees: [
        { movie: "The Cider House Rules", stars: ["Tobey Maguire","Charlize Theron","Michael Caine"], trailer: "pGdZBESUSfk", director: "Lasse Hallström" },
        { movie: "The Green Mile", stars: ["Tom Hanks","Michael Clarke Duncan"], trailer: "Bg7epsq0OIQ", director: "Frank Darabont" },
        { movie: "The Insider", stars: ["Al Pacino","Russell Crowe"], trailer: "P-_ZdJxgwcU", director: "Michael Mann" },
        { movie: "The Sixth Sense", stars: ["Bruce Willis","Haley Joel Osment","Toni Collette"], trailer: "HXG4HTIlc1U", director: "M. Night Shyamalan" },
      ]},
    { year: 1999, movie: "Shakespeare in Love", director: "John Madden", trailer: "v5R5La5f3eo",
      stars: ["Gwyneth Paltrow","Joseph Fiennes","Geoffrey Rush"],
      nominees: [
        { movie: "Elizabeth", stars: ["Cate Blanchett","Geoffrey Rush"], trailer: "DyGBwrtIamw", director: "Shekhar Kapur" },
        { movie: "Life Is Beautiful", stars: ["Roberto Benigni","Nicoletta Braschi"], trailer: "pAYEQP8gx3w", director: "Roberto Benigni" },
        { movie: "Saving Private Ryan", stars: ["Tom Hanks","Matt Damon","Tom Sizemore"], trailer: "RYExstiQlLc", director: "Steven Spielberg" },
        { movie: "The Thin Red Line", stars: ["Sean Penn","Jim Caviezel","Nick Nolte"], trailer: "ejm0XvT3rB8", director: "Terrence Malick" },
      ]},
    { year: 1998, movie: "Titanic", director: "James Cameron", trailer: "I7c1etV7D7g",
      stars: ["Leonardo DiCaprio","Kate Winslet","Billy Zane"],
      nominees: [
        { movie: "As Good as It Gets", stars: ["Jack Nicholson","Helen Hunt","Greg Kinnear"], trailer: "t2d89afgtqg", director: "James L. Brooks" },
        { movie: "The Full Monty", stars: ["Robert Carlyle","Tom Wilkinson"], trailer: "d6bjW9OwSQc", director: "Peter Cattaneo" },
        { movie: "Good Will Hunting", stars: ["Matt Damon","Robin Williams","Ben Affleck"], trailer: "ReIJ1lbL-Q8", director: "Gus Van Sant" },
        { movie: "L.A. Confidential", stars: ["Russell Crowe","Guy Pearce","Kim Basinger"], trailer: "QeIoelqDzsA", director: "Curtis Hanson" },
      ]},
    { year: 1997, movie: "The English Patient", director: "Anthony Minghella", trailer: "Xk_LRcOFT0c",
      stars: ["Ralph Fiennes","Kristin Scott Thomas","Juliette Binoche"],
      nominees: [
        { movie: "Fargo", stars: ["Frances McDormand","William H. Macy","Steve Buscemi"], trailer: "aoOZDiswNaw", director: "Joel Coen" },
        { movie: "Jerry Maguire", stars: ["Tom Cruise","Renée Zellweger","Cuba Gooding Jr."], trailer: "x1V_WduwrE8", director: "Cameron Crowe" },
        { movie: "Secrets & Lies", stars: ["Brenda Blethyn","Marianne Jean-Baptiste"], trailer: "V1e9ovKQViw", director: "Mike Leigh" },
        { movie: "Shine", stars: ["Geoffrey Rush","Armin Mueller-Stahl"], trailer: "NaF9JIhPgdU", director: "Scott Hicks" },
      ]},
];
